2004Scape/Server

data/src/obj.def
=> Update obj.def ITEM WEIGHTS

data/config/obj-spawns.csv
Pretty accurate so far. Probably not much left missing
=> Obj Spawns v5

src/enum/ClientProt.js
This is the client code:
rep++?
=> Add fix to ANTICHEAT_SIDEBAR_INPUT ClientProtSize from -1 to 1.

data/src/scripts/engine.rs2, src/lostcity/engine/ScriptOpcodes.js, src/lostcity/engine/ScriptRunner.js, src/lostcity/engine/ScriptState.js, src/lostcity/engine/World.js, src/lostcity/entity/EntityQueueRequest.js, src/lostcity/entity/Npc.js, src/lostcity/entity/Player.js
This allows up to 2 active players and npcs in a script state instead of just "subject" and "target". Queues also are handled more properly now.
=> refactor: cleanup ScriptState

.gitignore, README.md, package-lock.json
=> build: 🔧 add package-lock.json to source control

src/lostcity/cache/NpcType.ts, src/lostcity/cache/ObjType.ts, src/lostcity/entity/Player.ts
Got a bit done on this, ObjType causes some errors in the `Player` class (`invSet`, `decodeIn`, `onCheat` and `invAdd`) functions
- Line `558`: `Argument of type 'ObjType' is not assignable to parameter of type 'ScriptArgument[]'`
- Line `662`: `Argument of type 'ObjType' is not assignable to parameter of type 'ScriptArgument[]'`
- Line `798`: `'objType' is possibly 'null'`
- Line `1946`: `Type 'number | undefined' is not assignable to type 'string | number'`
I'm pretty sure I've converted the TS correctly but I don't want to change engine code without getting some input 💬 
There are two causes:
- `ScriptRunner.init` is being passed an `ObjType` as a `ScriptArgument`. Is this permitted? It seems like `ScriptArguments` can only be `number` or `string`.
- `invAdd` and `invSet` call …
=> refactor: conver NpcType and ObjType to ts

data/src/scripts/_unpack/all.loc, data/src/scripts/general/barrels.rs2, data/src/scripts/general/bookcases.rs2, data/src/scripts/general/chests.loc, data/src/scripts/general/chests.param, data/src/scripts/general/chests.rs2, data/src/scripts/general/crates.rs2, data/src/scripts/general/drawers.loc, data/src/scripts/general/drawers.param, data/src/scripts/general/drawers.rs2, data/src/scripts/general/haybales.loc, data/src/scripts/general/haybales.rs2, data/src/scripts/general/manholes.loc, data/src/scripts/general/manholes.rs2, data/src/scripts/general/pickables.rs2, data/src/scripts/general/sacks.rs2
Searching empty crates/sacks.
Opening drawers/chests & searching/closing them.
Manhole covers for Varrock & Ardougne with working teleport. Pickables - missing cabbages, otherwise potatoes, onion & grain implemented. (Missing force walk). Haybales searchable.
Bookshelves searchable.
=> Minor misc. location functionality implemented.

src/rsmod/PathFinder.test.ts, src/rsmod/reach/ReachStrategyTest.test.ts, src/rsmod/reach/RectangleBoundaryUtils.test.ts
port `ReachStrategyTest` from Kotlin
=> test: add tests to ReachStrategy class

data/src/scripts/general/scripts/quests.rs2, data/src/scripts/quests/quest_cook/scripts/quest_cook.rs2, data/src/scripts/quests/quest_doric/scripts/quest_doric.rs2, data/src/scripts/quests/quest_hetty/scripts/quest_hetty.rs2, data/src/scripts/quests/quest_romeojuliet/scripts/quest_romeojuliet.rs2, data/src/scripts/quests/quest_runemysteries/scripts/quest_runemysteries.rs2
adjusted ~send_quest_complete proc to take int for scale of obj on interface.
=> ~send_quest_complete adjustment.

data/pack/obj.pack, data/src/scripts/_unpack/all.npc, data/src/scripts/areas/area_lumbridge/configs/lumbridge.npc, data/src/scripts/areas/area_lumbridge/scripts/father_urhney.rs2, data/src/scripts/quests/quest_priest/configs/priest.npc, data/src/scripts/quests/quest_priest/configs/priest.obj, data/src/scripts/quests/quest_priest/scripts/quest_priest.rs2
* Changed amulet check to just check if it's equipped and not specific slot.
* Added zone check for all 4 zones the restless ghost can be in when removing.
* Added skeleton spawning when picking up the skull. (Using unimplemented npc_add)
* Renamed _ghostspeak_amulet_ to _amulet_of_ghostspeak_
* Moved _father_aereck_ & _father_arhneey_ to lumbridge.npc
* Moved _restless_ghost_ & _skeleton_ to priest.npc
* Updated father_urhney.rs2 to use renamed _amulet_of_ghostspeak_.
=> Quest priest update

data/src/scripts/quests/quest_priest/scripts/quest_priest.rs2
=> Priest Quest typo fix

src/lostcity/engine/collision/CollisionManager.ts, src/lostcity/entity/Entity.ts, src/lostcity/entity/Loc.ts, src/lostcity/entity/Npc.ts, src/lostcity/entity/Obj.ts, src/lostcity/entity/Player.ts
- Fix for lands on bridges collision not properly applied to the correct plane.
- Update Entity constructors to remove the default values for constructor properties.
- Updated properties to include their correct types.
- Added a `if (this.client != null) {` check in `encodeOut` function.
=> Engine/Collision Lands Fix

data/src/scripts/_unpack/all.npc, src/lostcity/engine/script/handlers/PlayerOps.ts, src/lostcity/entity/Npc.ts, src/lostcity/entity/PathingEntity.ts, src/lostcity/entity/Player.ts
- Npcs also keep their current walk step if blocked by player for example now. Unless does randomWalk() again.
=> Add multi direction support for walk step traversing.

data/src/scripts/player/scripts/global.rs2, data/src/scripts/quests/quest_gobdip/scripts/quest_gobdip.rs2
=> Add fixes for Goblin Diplomacy quest

data/src/scripts/engine.rs2, data/src/scripts/general_use/scripts/spade.rs2, data/src/scripts/interface_bank/scripts/bank.rs2, data/src/scripts/interface_bank/scripts/bank_deposit.rs2, data/src/scripts/minigames/game_trail/scripts/trail_clue_helper.rs2, data/src/scripts/player/scripts/drop.rs2, data/src/scripts/player/scripts/equip.rs2, data/src/scripts/player/scripts/inventory.rs2, data/src/scripts/shop/scripts/shop.rs2, data/src/scripts/skill_cooking/scripts/cooking_fire/cooking_fire.rs2, data/src/scripts/skill_cooking/scripts/cooking_inv/scripts/cakes/cakes.rs2, data/src/scripts/skill_cooking/scripts/cooking_inv/scripts/dough/dough.rs2, data/src/scripts/skill_cooking/scripts/cooking_inv/scripts/gnome_cooking/gnome_cooking.rs2, data/src/scripts/skill_cooking/scripts/cooking_inv/scripts/pies/pies.rs2, data/src/scripts/skill_cooking/scripts/cooking_inv/scripts/pizza/pizza.rs2, data/src/scripts/skill_cooking/scripts/cooking_inv/scripts/stew/stew.rs2, data/src/scripts/skill_cooking/scripts/cooking_inv/scripts/ugthanki_kebab/ugthanki_kebab.rs2, data/src/scripts/skill_cooking/scripts/cooking_range/cooking_range.rs2, data/src/scripts/skill_crafting/scripts/gem/gem.rs2, data/src/scripts/skill_crafting/scripts/jewellery/stringing.rs2, data/src/scripts/skill_crafting/scripts/leather/leather.rs2, data/src/scripts/skill_crafting/scripts/pottery/pottery.rs2, data/src/scripts/skill_fishing/scripts/fishing_spots/oil_rod_fishing.rs2, data/src/scripts/skill_smithing/configs/smithing/smithing.dbrow, data/src/scripts/skill_smithing/configs/smithing/smithing.dbtable, data/src/scripts/skill_smithing/scripts/smithing/smithing.rs2, docs/scripts.md, src/lostcity/engine/script/ScriptOpcode.ts, src/lostcity/engine/script/handlers/InvOps.ts, src/lostcity/engine/script/handlers/PlayerOps.ts
Impacts:
- oil_rod_fishing.rs2
- equip.rs2
- cooking_fire.rs2
- cakes.rs2
- dough.rs2
- gnome_cooking.rs2
- pies.rs2
- pizza.rs2
- stew.rs2
- ugthanki_kebab.rs2
- cooking_range.rs2
- gem.rs2
- stringing.rs2
- leather.rs2
- pottery.rs2
=> Update inv_getobj and create inv_getobj_deprecated

data/src/scripts/general_use/scripts/spade.rs2, data/src/scripts/minigames/game_trail/configs/trail.param, data/src/scripts/minigames/game_trail/configs/trail_easy.obj, data/src/scripts/minigames/game_trail/configs/trail_hard.obj, data/src/scripts/minigames/game_trail/configs/trail_medium.obj, data/src/scripts/minigames/game_trail/scripts/trail_clue_helper.rs2, src/lostcity/engine/script/handlers/InvOps.ts, src/lostcity/entity/Player.ts
The `inv_add` command itself does the overflow dropping already.
=> Update InvOps#invAdd, Player#invAdd and Player#invMoveFromSlot

data/src/scripts/_unpack/all.npc, data/src/scripts/areas/area_alkharid/scripts/border_gate.rs2, data/src/scripts/areas/area_draynor/scripts/morgan.rs2, data/src/scripts/general/scripts/sequence.rs2, data/src/scripts/interface_bank/configs/banker.npc, data/src/scripts/interface_chat/scripts/chat.rs2, data/src/scripts/interface_controls/configs/player_controls.constant, data/src/scripts/interface_controls/scripts/player_controls.rs2, data/src/scripts/player/combat - melee/scripts/opnpc2.rs2, data/src/scripts/player/scripts/logout.rs2, data/src/scripts/quests/quest_demon/configs/demon.npc, data/src/scripts/quests/quest_priest/configs/priest.npc, data/src/scripts/quests/quest_vampire/configs/quest_vampire.npc, src/lostcity/engine/script/ScriptProvider.ts, src/lostcity/engine/script/handlers/InvOps.ts, src/lostcity/engine/script/handlers/LocOps.ts, src/lostcity/engine/script/handlers/NpcOps.ts, src/lostcity/engine/script/handlers/ObjOps.ts, src/lostcity/engine/script/handlers/PlayerOps.ts, src/lostcity/engine/script/handlers/ServerOps.ts, src/lostcity/entity/Npc.ts, src/lostcity/entity/PathingEntity.ts, src/lostcity/entity/Player.ts, src/lostcity/entity/Position.ts
- `RESUME_PAUSEBUTTON` script state packet check.
- `RESUME_P_COUNTDIALOG` script state packet check.
- Fix to lumbridge toll gate.
- Fix to not walking to floor obj.
- Fix to logout.
- Npc retreating.
- Fix to walking a tile when doing operable actions.
- Fix Vampire Slayer dialogue line.
=> 🐛Bug fixes 

data/src/scripts/general/scripts/combat/combat.rs2, data/src/scripts/general/scripts/combat/npc_combat.rs2, src/lostcity/engine/script/handlers/NpcOps.ts, src/lostcity/entity/Npc.ts, src/lostcity/entity/PathingEntity.ts
- Also fixes some of the base `npc_combat.rs2` script that was suggested.
- Cleaned up the walk steps code.
=> fix: Npc Cardinal Step

data/src/scripts/areas/area_ardougne_east/scripts/captain_barnaby.rs2, data/src/scripts/areas/area_karamja/scripts/customs_officer.rs2, data/src/scripts/interface_boat/scripts/sail.rs2
fixes the customs officers in brimhaven, also fix for incorrect messages
=> fix: Customs officer fix

src/lostcity/util/CodeTimer.js, src/lostcity/util/PackFile.ts
This will help to keep an eye on individual packing steps
=> feat: add timers for "validate" steps in pack

src/jagex2/io/BZip2.js, src/lostcity/cache/DbRowType.ts, src/lostcity/cache/DbTableType.ts, src/lostcity/cache/IfType.ts, src/lostcity/cache/ParamHelper.ts, src/lostcity/engine/Inventory.ts, src/lostcity/engine/WorldList.ts, src/lostcity/engine/script/ScriptRunner.ts, src/lostcity/engine/script/ScriptState.ts, src/lostcity/engine/script/handlers/DbOps.ts, src/lostcity/engine/script/handlers/NpcOps.ts, src/lostcity/entity/Player.ts, src/lostcity/server/WSServer.ts, src/lostcity/tools/packinterface/Unpack.js, src/lostcity/tools/server/scripts/symbols.js
Solves about 20 warnings in total, most of the remaining warnings are for unused variables
=> refactor: resolve a number of lint warnings

data/src/scripts/_unpack/all.npc, data/src/scripts/quests/quest_vampire/scripts/count_draynor.rs2, data/src/scripts/skill_combat/configs/combat.param, data/src/scripts/skill_combat/configs/npc_combat.param, data/src/scripts/skill_combat/configs/ranged/bows.obj, data/src/scripts/skill_combat/scripts/npc/npc_combat_melee.rs2, data/src/scripts/skill_combat/scripts/npc/npc_death.rs2, data/src/scripts/skill_combat/scripts/player/player_combat.rs2, data/src/scripts/skill_combat/scripts/player/player_combat_stat.rs2, data/src/scripts/skill_combat/scripts/player/player_melee.rs2, data/src/scripts/skill_combat/scripts/player/player_ranged.rs2, data/src/scripts/skill_fishing/scripts/fishing.rs2, src/lostcity/engine/script/handlers/NpcOps.ts, src/lostcity/engine/script/handlers/PlayerOps.ts, src/lostcity/entity/Npc.ts, src/lostcity/entity/Player.ts
- Remove unnecessary combat params.
- Fix to Fishing using null namedobj.
- Add `deathanim_delay` param for npcs.
=> fix: AP Interactions and Combat Ranging

data/src/scripts/skill_woodcutting/scripts/cut.rs2, src/lostcity/engine/script/handlers/ServerOps.ts, src/lostcity/entity/Npc.ts, src/lostcity/entity/PathingEntity.ts, src/lostcity/entity/Player.ts
- Fixes Woodcutting trying to trigger off of the stump.
- Updates `map_blocked` command.
- Fixes coord facing for interactions and cleans up some of that code.
=> fix: Woodcuting & map_blocked

data/src/scripts/_unpack/all.loc, data/src/scripts/areas/area_brimhaven/scripts/pirate_guard.rs2, data/src/scripts/general/scripts/misc/coord_procs.rs2, data/src/scripts/ladders+stairs/scripts/stairs.rs2, data/src/scripts/npc/scripts/pirate.rs2
Adds a missing staircase in Draynor.
Partially fixes the coord_tostring proc.
Adds dialogue to 'pirate_guard' & 'npc_183' (Pirate).
Add missing 'bookcase' category to 'loc_393'.
=> Misc fixes and small content additions.

data/src/scripts/engine.rs2, data/src/scripts/interface_bank/scripts/bank.rs2, data/src/scripts/interface_bank/scripts/bank_deposit.rs2, data/src/scripts/player/scripts/equip.rs2, data/src/scripts/shop/scripts/shop.rs2, src/lostcity/engine/Inventory.ts, src/lostcity/engine/collision/WallCollider.ts, src/lostcity/engine/script/ScriptOpcode.ts, src/lostcity/engine/script/handlers/PlayerOps.ts, src/lostcity/entity/Player.ts
- Engine validates inv slots
- Engine validates pathfinder distance
- Removes `last_verifyobj`
- Packet validates before modifying player runtime props.
=> feat: inv slot engine validating & other

data/src/scripts/ladders+stairs/scripts/stairs.rs2
All staircases in Varrock complete.
All staircases in Falador complete.
Staircase in Brimhaven added.
Staircase in Rogues Castle added.
All staircases in Tree Gnome Stronghold added.
=> feat: Stairs all around the map.

data/src/scripts/doors/scripts/doubledoors.rs2
The original impl did not account for all angles and etc etc.
=> fix: doubledoors.rs2 

data/src/scripts/quests/quest_zanaris/configs/zanaris.obj, data/src/scripts/skill_combat/configs/magic/staves.obj
=> fix: basic staves readyanims

src/lostcity/engine/World.ts, src/lostcity/engine/collision/CollisionManager.ts, src/lostcity/engine/script/handlers/ServerOps.ts, src/lostcity/entity/Npc.ts, src/lostcity/entity/PathingEntity.ts
- Use `LineValidator` over `LinePathFinder` for unnecessary alloc.
- Adds `forceapproach` flags for checking `inOperableDistance` for locs.
=> refactor: lineofwalk and lineofsight

data/src/scripts/quests/quest_doric/scripts/quest_doric.rs2, data/src/scripts/skill_smithing/scripts/smithing/smithing.rs2
Wired up doric's anvil and fixed off by one errors for bronze bars.
=> fix: Smithing Fixes

data/src/scripts/skill_mining/scripts/mine.rs2
Needed to make mining slightly passive aggressive about your abilities.
=> fix: Update mining text

data/src/scripts/areas/area_taverly/scripts/crystal_chest.rs2, data/src/scripts/ladders+stairs/scripts/stairs.rs2, data/src/scripts/minigames/game_trail/scripts/trail_clue_drop.rs2
feat: Al Kharid General Store staircase added.
=> feat: Misc fixes and content.

data/src/scripts/levelrequire/scripts/tier60.rs2, data/src/scripts/player/scripts/global.rs2, data/src/scripts/tutorial/scripts/tutorial.rs2, src/lostcity/db/types.ts, src/lostcity/entity/Npc.ts
- Fixes npcs using ap improperly checking if in ap distance to target.
- Fixes quest list not updating when sending the tabs.
- Fixes the levelrequire for dragon spear and dragon med helm.
=> fix: npc approach distance

prisma/migrations/20231227162751_npc_hiscore/migration.sql, prisma/schema.prisma, src/lostcity/db/types.ts
Should the table name be plural or not? Who knows.
=> feat: Added NPC hiscore migration

data/src/scripts/_unpack/all.npc, data/src/scripts/ladders+stairs/scripts/stairs.rs2, data/src/scripts/quests/quest_imp/scripts/quest_imp.rs2
* Removed double dialogue from Imp Catcher
* Added animations to White Knights
* Added Dark Wizard's Tower stairs
* Added Crafting Guild Stairs
=> fix: Misc bug fixes

data/src/scripts/areas/area_taverly/scripts/sanfew.rs2, data/src/scripts/areas/area_varrock/configs/varrock.npc, data/src/scripts/areas/area_varrock/scripts/tea_seller.rs2, data/src/scripts/quests/quest_druid/scripts/quest_druid.rs2
issue fixes from wilaim and EclecticImpling
- tea shop sell prices scaled to 600% instead of 60%
- dialogue typos
- fixed some additional dialogue mistakes
=> fix: issue fixes

data/src/scripts/quests/quest_priest/scripts/quest_priest.rs2
Fixes softlock issue posted on Discord by Walen [Thread](https://discord.com/channels/953326730632904844/1195432328089063555)
=> fix: Priest quest softlock when completing

data/src/scripts/_unpack/all.npc, data/src/scripts/areas/area_desert/configs/desert.npc, data/src/scripts/areas/area_wilderness/configs/bandit_camp.npc, data/src/scripts/minigames/game_ranging/configs/ranging.npc, data/src/scripts/quests/quest_arthur/configs/keep_le_faye.npc, data/src/scripts/quests/quest_tree/configs/gnome_battlefield.npc, data/src/scripts/tutorial/configs/tutorial.npc, src/lostcity/cache/SpotanimType.ts, src/lostcity/engine/World.ts, src/lostcity/engine/script/handlers/ServerOps.ts, src/lostcity/entity/Player.ts, src/lostcity/server/ServerProt.ts, src/lostcity/tools/packconfig/SpotAnimConfig.ts
This is more of a hotfix release so I won’t be drafting a full post around it. It’s higher-priority (can’t log in new accounts / can break world) so it can’t wait a day or two
fixes: Tutorial island crash, Holy water crash, and continues to flesh out huntmodes.
=> fix: Resolved a couple bugs causing client crashes

src/lostcity/engine/World.ts
fixes the issue where static objs won't respawn
=> fix: respawn for static objs

package-lock.json, package.json, src/lostcity/cache/Component.test.ts
- Fixes the npc sizing problem for the `NaiveDestination` that Kris told us about.
- See https://github.com/2004scape/rsmod-pathfinder/commit/3fc315008f6d52c9947a9d577938d15c5821c47a
=> chore: update rsmod dependency

data/src/scripts/general/scripts/free_to_play.rs2, data/src/scripts/interface_bank/scripts/bank.rs2
=> fix: message for full bank in F2P

data/src/scripts/drop tables/scripts/black_dragon.rs2, data/src/scripts/drop tables/scripts/red_dragon.rs2, data/src/scripts/levelup/scripts/levelup_unlocks_fishing.rs2, data/src/scripts/levelup/scripts/levelup_unlocks_fletching.rs2, data/src/scripts/levelup/scripts/levelup_unlocks_herblore.rs2, data/src/scripts/levelup/scripts/levelup_unlocks_ranged.rs2, data/src/scripts/levelup/scripts/levelup_unlocks_runecrafting.rs2, data/src/scripts/levelup/scripts/levelup_unlocks_smithing.rs2
=> fix: accuracy improvements for levelup rewards

data/pack/varp.pack, data/src/scripts/_unpack/all.varp, data/src/scripts/engine.rs2, data/src/scripts/skill_combat/configs/magic/magic_combat_spells.dbrow, data/src/scripts/skill_combat/scripts/player/auto_cast.rs2, data/src/scripts/skill_combat/scripts/player/auto_retaliate.rs2, data/src/scripts/skill_combat/scripts/player/player_combat.rs2, data/src/scripts/skill_combat/scripts/player/player_magic.rs2, data/src/scripts/skill_combat/scripts/player/weapon_category.rs2, data/src/scripts/skill_magic/configs/magic.dbtable, src/lostcity/engine/script/ScriptOpcode.ts, src/lostcity/engine/script/ScriptOpcodePointers.ts, src/lostcity/engine/script/handlers/PlayerOps.ts, src/lostcity/entity/Player.ts
- p_opnpct command
- proper autocast delay
- manual cast works when action delayed
- removed %autocast_delay and %spell varp
=> fix: Magic autocast fix

data/src/scripts/_unpack/all.npc, data/src/scripts/quests/quest_grail/scripts/quest_grail.rs2, data/src/scripts/skill_agility/scripts/wilderness_course.rs2, src/lostcity/cache/NpcType.ts, src/lostcity/entity/Npc.ts, src/lostcity/tools/packconfig/NpcConfig.ts
- patrol mode support (added the mode to the witch in witches house)
- fix 0 damage in wilderness agil course
- fix grail zoom on reward interface
=> feat: patrol mode support + couple fixes

data/src/scripts/_unpack/all.npc, data/src/scripts/areas/area_alkharid/scripts/shantay_pass.rs2, data/src/scripts/areas/area_varrock/scripts/apothecary.rs2, data/src/scripts/drop tables/scripts/dwarf.rs2, data/src/scripts/drop tables/scripts/man.rs2, data/src/scripts/minigames/game_trail/scripts/trail_clue_drop.rs2, data/src/scripts/skill_magic/configs/magic_spells.dbrow
feat: Scorpions don't drop bones.
feat: `npc_120` (Dwarf) droptable added.
fix: Formatting in `man.rs2`.
chore: Cleaned up comment in Trail code.
fix: Watchtower Teleport corrected, no longer going to quest instance of the tower.
fix: Shantay Pass loc check corrected.
fix: Apothecary requires 5 coins for strength potion now.
=> misc: Fixes all around, droptables and whatnot.

data/src/scripts/player/scripts/damage.rs2
=> fix: item on death oversight

data/src/scripts/player/scripts/damage.rs2
remind me to test stuff before i ever PR
=> fix: item on death oversight oversight

data/src/scripts/skill_magic/scripts/spells/enchant.rs2
=> fix: amulet of glory p_choice text change

src/lostcity/engine/WorldList.ts, src/lostcity/util/Environment.ts, src/lostcity/util/TryParse.test.ts, src/lostcity/util/TryParse.ts
- Add try parse util methods for parsing environment variables with default values
- Environment module now has true typing
- Assign missing types to world list
=> refactor: add try parse util methods and add World interface for world list

.husky/commit-msg, .husky/pre-commit, commitlint.config.ts, package-lock.json, package.json
- Lint staged JavaScript and TypeScript files
- Add conventional commit linting
- Output todo comments on staged files
- Sort staged package.json changes
=> chore: lint staged files

data/src/scripts/_test/scripts/engine/debug_huntall.rs2, data/src/scripts/engine.rs2, src/lostcity/engine/script/ScriptIterators.ts, src/lostcity/engine/script/ScriptState.ts, src/lostcity/engine/script/handlers/LocOps.ts, src/lostcity/engine/script/handlers/NpcOps.ts, src/lostcity/engine/script/handlers/ServerOps.ts, src/lostcity/entity/Npc.ts
- Implements the following commands: `huntall`, `huntnext` and `npc_sethunt`.
- Refactors the iterators used for finding hunt, loc and npc.
=> feat: hunt commands

data/src/scripts/engine.rs2, src/jagex2/Trig.test.ts, src/jagex2/Trig.ts, src/lostcity/engine/script/handlers/NumberOps.ts
- Implements the following commands: `sin_deg`, `cos_deg`, `atan2_deg` and `addpercent`
=> feat: trig commands

data/src/pack/obj.pack, data/src/scripts/_test/scripts/cheats/cheat_bank.rs2, data/src/scripts/_test/scripts/cheats/cheat_consume.rs2, data/src/scripts/_unpack/all.obj, data/src/scripts/general_use/configs/holiday.obj, data/src/scripts/player/configs/consumption/consume_effects.dbrow, data/src/scripts/player/configs/consumption/consume_messages.dbrow, data/src/scripts/player/configs/consumption/consume_normal.dbrow, data/src/scripts/skill_cooking/configs/cooking_generic/cooking.obj, data/src/scripts/skill_cooking/configs/cooking_inv/configs/wine/wine.obj
795=war_ship
1037=bunny_ears
1053=green_halloween_mask
1054=cert_green_halloween_mask
1055=blue_halloween_mask
1056=cert_blue_halloween_mask
1057=red_halloween_mask
1058=cert_red_halloween_mask
981=disk_of_returning
982=cert_disk_of_returning
1961=easter_egg
1962=cert_easter_egg
1989=half_full_wine_jug
1990=cert_half_full_wine_jug
=> chore: rename remaining holiday items

src/lostcity/entity/Npc.ts, src/lostcity/entity/PathingEntity.ts
- Was checking for `null` should be `CollisionFlag.NULL`
=> fix: blockWalkFlag check on Npcs

src/lostcity/engine/script/handlers/NpcOps.ts, src/lostcity/entity/Npc.ts, src/lostcity/entity/PathingEntity.ts, src/lostcity/entity/Player.ts
- Limit waypoints to 25 (failsafe)
- Auto converts rsmod path values to Int32
=> refactor: PathingEntity waypoints

data/src/scripts/_test/scripts/cheats/cheat_macro_event.rs2, data/src/scripts/macro events/scripts/general/macro_event_drunken_dwarf.rs2, data/src/scripts/macro events/scripts/general/macro_event_genie.rs2, data/src/scripts/macro events/scripts/general/macro_event_mysterious_old_man.rs2, data/src/scripts/macro events/scripts/general/macro_event_swarm.rs2, data/src/scripts/macro events/scripts/general/macro_event_triffid.rs2, data/src/scripts/macro events/scripts/macro_events.rs2
fixes npc_delay bug in the login script
=> fix: use ai_queue for general random events greeting the player

data/src/scripts/skill_combat/scripts/player/player_combat.rs2, data/src/scripts/skill_combat/scripts/player/player_melee.rs2, data/src/scripts/skill_combat/scripts/player/player_ranged.rs2, src/lostcity/engine/script/handlers/PlayerOps.ts, src/lostcity/entity/NetworkPlayer.ts, src/lostcity/entity/PathingEntity.ts, src/lostcity/entity/Player.ts
- passes all of these tests: https://github.com/2004scape/Server/wiki/OP-AP-Testing-Scenarios
- fixes ranged
- fixes fishing
- etc
=> fix(engine): interactions

data/src/scripts/skill_combat/scripts/npc/npc_combat.rs2
fixes npc's getting flinched constantly before their first attack
=> fix: additional logic for npc_out_of_combat

data/src/scripts/_unpack/all.hunt, data/src/scripts/_unpack/all.npc, data/src/scripts/npc/scripts/highwayman.rs2
- `[ranged]` Hunt config is not constant.
=> feat(content): Stand and deliver!

data/src/scripts/general_use/configs/water_sources.obj, data/src/scripts/general_use/configs/water_sources.param, data/src/scripts/general_use/scripts/water_sources.rs2, data/src/scripts/skill_cooking/scripts/cooking_inv/scripts/dough/dough.rs2, data/src/scripts/tutorial/scripts/skills/tut_cooking.rs2
also adds opheldu trigger for tutorial_pot_of_flour
=> fix(content): bucket of water not always deleting when making dough

data/src/scripts/areas/area_alkharid/scripts/tanner.rs2
https://web.archive.org/web/20040804232357/http://runehq.com/viewcityguide.php?id=00390
=> fix(content): tanner dialogue changed to fit new evidence

src/lostcity/engine/script/handlers/PlayerOps.ts, src/lostcity/entity/NetworkPlayer.ts, src/lostcity/entity/Npc.ts, src/lostcity/entity/Player.ts
=> fix(engine): stop pathing towards target npc if the target uid is no longer found

data/src/scripts/macro events/scripts/fishing/macro_event_river_troll.rs2, data/src/scripts/macro events/scripts/general/macro_event_drunken_dwarf.rs2, data/src/scripts/macro events/scripts/general/macro_event_swarm.rs2, data/src/scripts/macro events/scripts/general/macro_event_triffid.rs2, data/src/scripts/macro events/scripts/mining/macro_event_rock_golem.rs2, data/src/scripts/macro events/scripts/prayer/macro_event_shade.rs2, data/src/scripts/macro events/scripts/prayer/macro_event_zombie.rs2, data/src/scripts/macro events/scripts/thieving/macro_event_watchman.rs2, data/src/scripts/macro events/scripts/woodcutting/macro_event_dryad.rs2
matches this [video](https://youtu.be/tw66JWQzpD0?t=32) from sept 22, 2006
https://github.com/2004scape/Server/assets/61213166/2ecc7dc9-2eab-4442-93b3-18907b0d6d46
=> fix(content): allow dangerous randoms to interupt player combat

data/src/scripts/skill_fishing/scripts/fishing_spots/net_harpoon_fishing.rs2
https://youtu.be/fWox14AFvEM?t=299
=> fix(content): missing sounds for casket opening

src/lostcity/engine/script/handlers/NpcOps.ts, src/lostcity/entity/Npc.ts, src/lostcity/entity/PathingEntity.ts
- Type `targetOp` as `ServerTriggerType | NpcMode` and npc uses that now.
=> fix(engine): npc mode not being used

src/lostcity/entity/Npc.ts, src/lostcity/entity/PathingEntity.ts
- It was being set then was being cleared.
=> fix(engine): operation order for npc default and no modes

src/lostcity/network/225/incoming/prot/ClientProt.ts
```java
public static final int[] anIntArray89 = new int[] {
95, 218, 67, 50, 253, 222, 194, 60, 101, 128,
8, 251, 92, 111, 24, 33, 223, 66, 232, 59,
227, 113, 153, 105, 126, 98, 167, 102, 177, 238,
62, 190, 147, 23, 150, 151, 156, 144, 193, 155,
81, 0, 198, 22, 137, 210, 179, 16, 168, 170,
32, 181, 248, 141, 58, 87, 208, 106, 180, 191,
221, 241, 40, 176, 196, 154, 65, 145, 230, 78,
30, 161, 188, 41, 14, 129, 18, 199, 47, 247,
225, 34, 51, 10, 159, 75, 12, 56, 61, 31,
39, 91, 46, 242, 134, 5, 122, 123, 209, 228,
104, 195, 21, 3, 11, 44, 107, 172, 6, 186,
110, 215, 205, 103, 27, 185, 124, 77, 252, 117,
86, 115, 127, 207, 52, 79, 43, 97, 219, 116,
169, 7, 118, 162, 108, 36, 20, 233, 88, 135,
80, 19, 42, 237, 57, 152, 71, 9, 250, 17,
4, 119, 234, 130, 26, 200, 189, 163, 254, 245,
197, 171, …
```
=> fix: swap packet "index"

neptune.toml, src/lostcity/network/225/incoming/prot/ClientProt.ts
=> fix: reorder packets and fix typo

data/src/scripts/_unpack/all.npc
- They should not be hunting at all.
=> fix(content): basic wizard npc hunting players

src/lostcity/entity/MoveStrategy.ts, src/lostcity/entity/NetworkPlayer.ts, src/lostcity/entity/Npc.ts, src/lostcity/entity/PathingEntity.ts, src/lostcity/entity/Player.ts, src/lostcity/network/225/incoming/handler/ClientCheatHandler.ts
- Creates `::fly` and `::naive` engine cheats.
=> feat(engine): move strategies

data/src/scripts/engine.rs2, data/src/scripts/minigames/game_partyroom/scripts/partyroom.rs2, data/src/scripts/minigames/game_trail/scripts/trail_clue_drop.rs2, data/src/scripts/player/scripts/damage.rs2, data/src/scripts/skill_combat/scripts/npc/npc_combat.rs2, data/src/scripts/skill_combat/scripts/player/player_ranged.rs2, data/src/scripts/skill_combat/scripts/pvp/pvp_ranged.rs2, data/src/scripts/skill_firemaking/scripts/achey.rs2, data/src/scripts/skill_firemaking/scripts/firemaking.rs2, data/src/scripts/tutorial/scripts/skills/tut_firemaking.rs2, src/lostcity/engine/World.ts, src/lostcity/engine/script/ScriptOpcode.ts, src/lostcity/engine/script/ScriptOpcodePointers.ts, src/lostcity/engine/script/handlers/InvOps.ts, src/lostcity/engine/script/handlers/ObjOps.ts, src/lostcity/engine/script/handlers/PlayerOps.ts
- Implements `obj_addall` & `obj_addunsafe`
- Implements `both_dropslot`
- Fixes `both_heropoints`
- Changes `obj_add` and `obj_addall` to input `namedobj` instead of `obj`
- Implements `inv_dropall`
=> feat(engine): new commands

data/src/scripts/minigames/game_gnomeball/scripts/gnomeball.rs2, data/src/scripts/minigames/game_gnomeball/scripts/gnomeball_pass.rs2, data/src/scripts/minigames/game_gnomeball/scripts/gnomeball_referee.rs2, data/src/scripts/skill_combat/scripts/combat.rs2
- fix not being able to pass the ball outside of games
- fix referee missing npc_anim
- fix gnomeball should have unarmed attack anims
=> fix(content): gnomeball fixes

data/src/scripts/_test/scripts/engine/debug.rs2, data/src/scripts/_test/scripts/engine/debug_addobj.rs2, src/lostcity/cache/config/ObjType.ts, src/lostcity/engine/GameMap.ts, src/lostcity/engine/Inventory.ts, src/lostcity/engine/World.ts, src/lostcity/engine/WorldStat.ts, src/lostcity/engine/script/handlers/DebugOps.ts, src/lostcity/engine/script/handlers/ServerOps.ts, src/lostcity/entity/NetworkPlayer.ts, src/lostcity/entity/Player.ts, src/lostcity/network/225/incoming/handler/OpHeldUHandler.ts, src/lostcity/network/225/incoming/handler/OpLocUHandler.ts, src/lostcity/network/225/incoming/handler/OpNpcUHandler.ts, src/lostcity/network/225/incoming/handler/OpObjUHandler.ts, src/lostcity/network/225/incoming/handler/OpPlayerUHandler.ts
- Move debug commands from `ServerOps` to `DebugOps`
- Refactor `World` class and separate parts out of the cycle function.
- Create `WorldStat` and track last cycle and this cycle stats.
- World `invs` and `newPlayers` are refactored into a `Set`
=> refactor(engine): world

data/src/scripts/minigames/game_ranging/scripts/ranging_guild_door.rs2, data/src/scripts/quests/quest_arena/scripts/quest_arena.rs2, data/src/scripts/quests/quest_waterfall/scripts/quest_waterfall.rs2, data/src/scripts/skill_agility/scripts/agility.rs2, data/src/scripts/skill_agility/scripts/shortcuts.rs2
* change forcewalk proc to correctly force walking speed
* add (authentic) typo to waterfall quest
=> fix(content): change forcewalk proc to force walking speed

data/src/scripts/_unpack/all.loc, data/src/scripts/general_use/configs/hopper.loc, data/src/scripts/general_use/configs/hopper.param, data/src/scripts/general_use/scripts/windmills.rs2, data/src/scripts/quests/quest_cook/scripts/quest_cook.rs2
- fix cook range working during quest
- fix typo in cooks assistant
- add functionality to other hoppers
=> fix(content): cooks fixes, other hoppers

src/lostcity/entity/BuildArea.ts, src/lostcity/entity/Player.ts, src/lostcity/network/225/outgoing/codec/PlayerInfoEncoder.ts
- Based on the last map_clock the appearance was changed now.
=> fix(engine): appearance caching not accounting for the entire block

src/lostcity/engine/World.ts, src/lostcity/engine/zone/Zone.ts, src/lostcity/engine/zone/ZoneEntityList.ts, src/lostcity/entity/EntityList.ts, src/lostcity/entity/NetworkPlayer.ts, src/lostcity/entity/Npc.ts, src/lostcity/entity/Player.ts, src/lostcity/network/225/outgoing/codec/NpcInfoEncoder.ts
- Refactors zone objs and locs to use `ZoneEntityList`.
- Simplifies some of the code into this new class.
- Limits the number of objs and locs in a zone.
=> feat(engine): ZoneEntityList

src/lostcity/entity/Npc.ts
https://github.com/user-attachments/assets/9f9cf5a3-b911-4ace-8d3f-8dbfbc11a182
https://github.com/user-attachments/assets/6aabe3db-5307-43a2-bf6d-e65750bce9c2
=> fix(engine): remove maxrange corners when npc is op

data/src/scripts/areas/area_wilderness/scripts/wilderness_warning.rs2
1:1 with these videos:
- https://youtu.be/CI7BfqmDeWk?t=101
- https://youtu.be/OTeZs6SIyx4?t=61
- https://youtu.be/dpOJn0HyTx4?t=52
- https://youtu.be/jdcT9ogpMwE?t=104
=> feat(content): wildy warning

data/src/scripts/quests/quest_mcannon/scripts/locs/mcannon_broken_cannon.rs2
Was checking the incorrect constant for incrementing the progress.
=> fix(content): Dwarf Cannon Broken Cannon Fix

data/src/scripts/general_use/scripts/hammer.rs2, data/src/scripts/skill_crafting/scripts/gem/uncut_gem.rs2, data/src/scripts/skill_fletching/scripts/bolts.rs2
Only works on:
- Jade/Uncut
- Opal/Uncut
- Red Topaz/Uncut
=> feat(content): opheldu for hammer on gems

data/src/scripts/quests/quest_gobdip/scripts/quest_gobdip.rs2
=> fix: missing linebreak in gobdip quest

data/src/pack/obj.pack, data/src/scripts/_unpack/all.obj, data/src/scripts/quests/quest_seaslug/scripts/quest_seaslug.rs2
update obj name and change script to use corrrect glass, also only need 1 script cause engine will handle other order
=> fix(content): fix seaslug glass script

data/src/pack/npc.pack, data/src/scripts/_unpack/all.npc, data/src/scripts/areas/area_taverly/dungeon/configs/taverly_dungeon.npc, data/src/scripts/areas/area_taverly/dungeon/scripts/jailer.rs2, data/src/scripts/areas/area_taverly/dungeon/scripts/lord_daquarius.rs2
He does not have an npc chat head.
=> feat(content): lord daquarius

data/src/scripts/_test/scripts/engine/debug_killme.rs2, data/src/scripts/_unpack/all.hunt, data/src/scripts/_unpack/all.npc, data/src/scripts/areas/area_desert/configs/desert.npc, data/src/scripts/areas/area_draynor/configs/draynor.npc, data/src/scripts/areas/area_wilderness/configs/bandit_camp.npc, data/src/scripts/areas/area_wilderness/configs/king_black_dragon.hunt, data/src/scripts/areas/area_wizard_tower/configs/wizard_tower.npc, data/src/scripts/quests/quest_arena/configs/quest_arena.npc, data/src/scripts/quests/quest_arthur/configs/keep_le_faye.npc, data/src/scripts/quests/quest_dragon/configs/quest_dragon.npc, data/src/scripts/quests/quest_tree/configs/gnome_battlefield.npc, src/lostcity/cache/config/NpcType.ts, src/lostcity/entity/NetworkPlayer.ts, src/lostcity/entity/Npc.ts
=> fix: August 7th Alpha Hotfix 1

src/lostcity/engine/script/ScriptIterators.ts, src/lostcity/engine/script/handlers/ServerOps.ts
I'd like to do a bit more refactoring on these in future and remove some of the duplication
=> fix(engine): remove op2 check from `.hunt` files

data/src/scripts/quests/quest_fluffs/scripts/pet.rs2
- added a message box for when a cat becomes overgrown (from osrs)
- removed an outdated todo
=> fix(content): remove two todos from cat code

src/lostcity/engine/zone/Zone.ts
- The fix was moving `this.shared = null;` into the `reset` function which is the reliable way for us to clear them, since `computeShared` relies on players loaded zones (unreliable if they teleport away).
- 
- Just did some light renaming and documentation.
=> fix(engine): enclosed zone updates improperly cleared

data/src/scripts/quests/quest_haunted/configs/quest_haunted.obj
=> fix(content): poison and fish_food objs untradable

data/src/scripts/_test/scripts/engine/debug_addobj.rs2, src/lostcity/engine/zone/Zone.ts
- Adds the additional check since these would be the shared/partial updates in this case.
=> fix(engine): zones sending duplicate events

data/src/scripts/areas/area_varrock/scripts/gertrude.rs2, data/src/scripts/quests/quest_fluffs/scripts/quest_fluffs.rs2
- Minor dialogue/message corrections
- Cat meows twice as intended when obtained
- Added missing message for quest reward
- Added various linebreaks (guesses based on rsc dialogue breaks, only present where they would make sense)
=> fix(content): gertrude's cat tweaks

data/src/scripts/_unpack/all.loc, data/src/scripts/areas/area_varrock/scripts/gertrude.rs2, data/src/scripts/quests/quest_fluffs/configs/quest_fluffs.loc, data/src/scripts/quests/quest_fluffs/scripts/pet.rs2, data/src/scripts/quests/quest_fluffs/scripts/quest_fluffs.rs2
- clean up redundant/invalid comments
- add some image references
- more authenticity changes
- added searching for the other crates in lumberyard
- added use raw fish on fluffs (authentic, unsure what items can be used)
=> fix(content): more gertrude's cat tweaks

data/src/scripts/_test/scripts/engine/debug_npc.rs2, data/src/scripts/quests/quest_chompybird/configs/quest_chompybird.npc, data/src/scripts/quests/quest_chompybird/configs/quest_chompybird.varn, data/src/scripts/quests/quest_chompybird/scripts/bloated_toad.rs2, data/src/scripts/quests/quest_chompybird/scripts/bugs.rs2, data/src/scripts/quests/quest_chompybird/scripts/chompy_bird.rs2, data/src/scripts/quests/quest_chompybird/scripts/fycie.rs2, data/src/scripts/quests/quest_chompybird/scripts/quest_chompybird.rs2, data/src/scripts/quests/quest_chompybird/scripts/rantz.rs2, data/src/scripts/quests/quest_chompybird/scripts/raw_chompy.rs2, data/src/scripts/skill_combat/scripts/npc/npc_combat.rs2, src/lostcity/engine/script/ScriptOpcodePointers.ts
Quest is basically complete, needs a bit of polish in places
Some after-quest interactions still required
See #799 , #800 , #801
=> feat(content): finish main quest_chompybird

src/lostcity/engine/World.ts, src/lostcity/entity/Npc.ts
matches osrs behavior where imps can tele on first tick of respawn
=> fix(engine): timers will now tick during npc respawn

data/src/scripts/quests/quest_sheepherder/scripts/npcs/councillor_halgrive.rs2, data/src/scripts/quests/quest_sheepherder/scripts/npcs/doctor_orbon.rs2
Sheep herder dialogue with councillor halgrive and doctor orbon
=> fix(content): sheep herder dialogue 

data/src/scripts/player/scripts/consumption/effects/scripts/consume_effects.rs2, data/src/scripts/quests/quest_fluffs/configs/quest_fluffs.npc, data/src/scripts/skill_cooking/scripts/cooking_inv/scripts/pizza/pizza.rs2
+ fix 2 messages with no punctuation
=> fix(content): fix cats blocking npc movement

data/src/scripts/minigames/game_partyroom/scripts/partyroom.rs2
Necromancer and Invrigar combat scripts
=> feat(content): Necromancer tower

package.json, src/lostcity/engine/World.ts, src/lostcity/friends.ts, src/lostcity/network/225/incoming/handler/FriendListAddHandler.ts, src/lostcity/network/225/incoming/handler/FriendListDelHandler.ts, src/lostcity/network/225/incoming/prot/ClientProtRepository.ts, src/lostcity/server/FriendsServer.ts, src/lostcity/server/FriendsServerRepository.ts, src/lostcity/server/FriendsThread.ts, src/lostcity/util/Environment.ts
Only has "add"/"delete" friend, and online/world status
Still TODO:
- PMing
- Ignore list
- Private chat status
=> feat(engine): Friends Server V1

data/src/scripts/quests/quest_ball/scripts/witches_experiement.rs2
https://www.youtube.com/watch?v=aywWq4h1G8E&t=476s, tries to opplayer2, since in combat it should not attack
=> fix(content): witch's experiment will no longer attack instantly

data/src/scripts/areas/area_karamja/scripts/trufitus.rs2, data/src/scripts/drop tables/scripts/jogre.rs2, data/src/scripts/general/configs/quest.constant, data/src/scripts/quests/quest_junglepotion/configs/quest_junglepotion.constant, data/src/scripts/quests/quest_junglepotion/scripts/quest_junglepotion.rs2, data/src/scripts/skill_herblore/configs/herbs.obj
corrected mesanims/bits of dialogue, freespace/stage check when collecting herbs, end stage is 12 instead of 11
=> fix(content): junglepotion changes

data/src/scripts/skill_combat/scripts/npc/npc_death.rs2, data/src/scripts/skill_cooking/scripts/cooking.rs2
- extra delay in npc_death didnt match osrs
=> fix(content): npc_death timing fix and cooking mes

src/lostcity/engine/World.ts, src/lostcity/entity/Player.ts, src/lostcity/network/225/incoming/handler/ChatSetModeHandler.ts, src/lostcity/network/incoming/model/ChatSetMode.ts, src/lostcity/network/outgoing/model/ChatFilterSettings.ts, src/lostcity/server/FriendsServer.ts, src/lostcity/server/FriendsServerRepository.ts, src/lostcity/server/FriendsThread.ts, src/lostcity/util/ChatModes.ts
=> feat(engine): respect "Private chat" setting for world visibility on friends list

data/src/scripts/general_use/scripts/pickables.rs2
=> fix(content): update flax picking timing

data/src/pack/npc.pack, data/src/scripts/_unpack/all.npc, data/src/scripts/areas/area_entrana/scripts/monk_entrana.rs2, data/src/scripts/areas/monastery/scripts/monk.rs2, data/src/scripts/areas/monastery/scripts/prayer_guild.rs2, data/src/scripts/engine.rs2, data/src/scripts/interface_chat/scripts/chat.rs2
- add applayer2/opplayer2 check to chatnpc so combat doesn't stop when talking (OSRS behaviour)
- remove retreat from monks
- add spotanim to monk healing during combat
- mesanim fixes for monk dialogue
- entrana monk dialogue/combat script
=> fix(content): mode check in chatnpc, monk changes

data/src/scripts/general_use/scripts/tables.rs2
Fixes:
https://github.com/user-attachments/assets/d3412987-6703-43e2-8030-6b886774f49e
=> fix(content): Account for loc angle when placing items on tables

data/src/scripts/macro events/scripts/general/macro_event_genie.rs2, data/src/scripts/macro events/scripts/general/macro_event_mysterious_old_man.rs2, data/src/scripts/skill_combat/scripts/player/player_magic.rs2, data/src/scripts/skill_combat/scripts/pvp/pvp_magic.rs2, data/src/scripts/tutorial/scripts/skills/tut_player_magic.rs2
- fixes bug when casting magic on defensive mode and nothing in right hand
- genie and mysterious old man spawn matched to this [video](https://www.youtube.com/watch?v=el-h9hbSH80&t=293s)
=> fix(content): casting magic bug and genie/MOM fix

src/lostcity/entity/PathingEntity.ts
https://github.com/user-attachments/assets/8dc2c502-1dd9-4183-a216-9db779940634
matches with this youtube video: https://youtu.be/F_Kx8UWvDk8
=> fix(engine): Only set player movespeed for telejump

data/src/scripts/skill_fletching/configs/arrows/arrows.dbrow, data/src/scripts/skill_fletching/configs/fletching.dbtable, data/src/scripts/skill_fletching/scripts/arrows.rs2
https://youtu.be/iWPhF6tUUSs?t=282 (different than osrs)
=> fix(content): match old arrow fletching mes

data/src/scripts/_unpack/all.npc, src/lostcity/entity/Npc.ts, src/lostcity/entity/PathingEntity.ts
2004scape:
https://github.com/user-attachments/assets/02f6b9fc-1614-4e1e-aec6-8ae085a90730
OSRS:
https://github.com/user-attachments/assets/adebeb8d-4fc1-4f0a-97a3-ab45853a266e
2005:
https://youtu.be/8AFed6tyOp8?t=231
=> fix(content): check huntTarget for hunts and newTargetTick for player hunts in multi

data/src/scripts/npc/scripts/monk_of_zamorak.rs2, data/src/scripts/quests/quest_dragon/scripts/melzar_the_mad.rs2
they now zap a little more like they do in osrs
=> fix(content): monk of zamorak zapping

src/lostcity/entity/Npc.ts
Before:
https://github.com/user-attachments/assets/066b4805-ee85-4b8e-b232-ed177cd90853
After:
https://github.com/user-attachments/assets/7033ae4a-ab69-48bf-9b40-720126774583
=> fix(engine): clearWaypoints before setting to default mode for playerFaceModes

.gitattributes
no more annoying changes every time the pack runs
=> chore(engine): set `eol=lf` for `.pack` files in `.gitattributes`

data/src/scripts/areas/area_ardougne_east/scripts/captain_barnaby.rs2, data/src/scripts/areas/area_draynor/configs/draynor.npc, data/src/scripts/areas/area_karamja/scripts/customs_officer.rs2, data/src/scripts/areas/area_lumbridge/configs/lumbridge.npc, data/src/scripts/areas/area_port_sarim/scripts/sailors.rs2, data/src/scripts/areas/area_wilderness/scripts/king_black_dragon.rs2, data/src/scripts/levelup/scripts/levelup_unlocks_crafting.rs2, data/src/scripts/minigames/game_trawler/scripts/murphy_at_sea.rs2, data/src/scripts/minigames/game_trawler/scripts/trawler_flood.rs2, data/src/scripts/minigames/game_trawler/scripts/trawler_sink.rs2, data/src/scripts/minigames/game_trawler/scripts/trawler_win.rs2, data/src/scripts/player/configs/consumption/consume_messages.dbrow, data/src/scripts/skill_fishing/configs/fishing.npc, data/src/scripts/skill_smithing/scripts/smithing/smithing.rs2, data/src/scripts/tutorial/scripts/skills/tut_smithing.rs2, data/src/scripts/tutorial/scripts/tut_chatbox_steps.rs2
- Smithing on first smith didnt have an extra delay after smithing the item. To match this video: https://youtu.be/vQixsBb7wPQ?t=95 (level up occurs 3 ticks after item is received) 
- Fishing spots in the fisher realm were incorrectly coded as net/harpoon
- Remove area checks in the fishing trawler teleport queues to match: https://youtu.be/RZwuEjlkVhY?t=148
- Check for lowmemory was missing, im not sure to keep the "memery" typo since this is an rs2 beta screenshot
- "You pay the 30 coins and board the ship." -> "You pay the 30 coins..." "and board the ship."
- Double space after "beer."
- Blue period at the end 
- Ned not restricted to outdoors
- Kbd poison and icy attack flipped, (Poison attack should be from its left side)
- Kbd fire blast spot anim on impact
=> fix(content): misc fixes and mes adjustments

data/src/scripts/areas/monastery/scripts/abbot_langley.rs2, data/src/scripts/general/configs/jingle.constant, data/src/scripts/levelup/configs/levelup.dbrow, data/src/scripts/macro events/scripts/general/macro_event_genie.rs2, data/src/scripts/macro events/scripts/mining/macro_event_gas.rs2, data/src/scripts/quests/quest_mcannon/scripts/npcs/dwarf_commander.rs2, data/src/scripts/quests/quest_zanaris/scripts/quest_zanaris.rs2, data/src/scripts/skill_woodcutting/scripts/woodcut.rs2
- dwarf cannon dialogue fixes
- firemaking -> fire making (pre 2005?)
- axe req message for wcing
- macro gas mes
=> fix(content): dwarf cannon dialogue fixes, mes adjustments

data/src/scripts/interface_chat/scripts/chat.rs2, data/src/scripts/levelup/scripts/levelup_unlocks_woodcutting.rs2, data/src/scripts/quests/quest_fluffs/scripts/pet.rs2, data/src/scripts/skill_cooking/scripts/cooking.rs2, data/src/scripts/skill_crafting/configs/spinning/spinning.struct, data/src/scripts/skill_prayer/scripts/prayers/clarity.rs2, data/src/scripts/skill_prayer/scripts/prayers/improvedreflexes.rs2, data/src/scripts/skill_prayer/scripts/prayers/incrediblereflexes.rs2, data/src/scripts/skill_prayer/scripts/prayers/protectfrommagic.rs2, data/src/scripts/skill_prayer/scripts/prayers/protectfrommelee.rs2, data/src/scripts/skill_prayer/scripts/prayers/protectfrommissiles.rs2, data/src/scripts/skill_prayer/scripts/prayers/protectitems.rs2, data/src/scripts/skill_prayer/scripts/prayers/rapidheal.rs2, data/src/scripts/skill_prayer/scripts/prayers/rapidrestore.rs2, data/src/scripts/skill_prayer/scripts/prayers/rockskin.rs2, data/src/scripts/skill_prayer/scripts/prayers/steelskin.rs2, data/src/scripts/skill_prayer/scripts/prayers/strengthburst.rs2, data/src/scripts/skill_prayer/scripts/prayers/superhumanstrength.rs2, data/src/scripts/skill_prayer/scripts/prayers/thickskin.rs2, data/src/scripts/skill_prayer/scripts/prayers/ultimatestrength.rs2
- Update cooking on fire message
- Update woodcutting level-up messages
- Update [Bowstring message](https://youtu.be/HQEpeWAUMbI?si=1OHnT82XJvqdt3TT&t=49)
- [Update message for trying to pick up someone's cat](https://youtu.be/WsvTr-1bZwM?t=175)
- Update coloring on low level message for Prayer
=> fix(content): authentic messages

data/src/scripts/areas/area_wizard_tower/scripts/wizard_grayzag.rs2, data/src/scripts/quests/quest_dragon/configs/quest_dragon.npc, data/src/scripts/quests/quest_dragon/scripts/melzar_the_mad.rs2, data/src/scripts/skill_firemaking/scripts/achey.rs2, data/src/scripts/skill_firemaking/scripts/firemaking.rs2
- fix: achey fm's special inv script was missing the roll check
- fix: relighting after failing the fm roll was too fast
- fix: melzar missing attackrange
- refactor: remove grayzag ap
=> fix(content): achey fm, relighting fm, grayzag, and melzar fixes

data/src/scripts/general/scripts/quests.rs2, data/src/scripts/quests/quest_hero/scripts/npcs/trobert.rs2
- ID papers were not able to re obtain for heroes quest
- Fix quest tab colors for big chompy bird hunting
=> fix(content): quest tab colors for chompy, heroes fix

data/src/scripts/drop tables/scripts/shared_droptables.rs2, data/src/scripts/general/configs/quest.constant
also added legends quest requirement to accessing mega rare table from gem drop table
=> fix(content): Ring of Wealth doesn't affect mega rare drop table

data/src/scripts/skill_herblore/configs/brewing/brew_potion.struct, data/src/scripts/skill_herblore/scripts/brewing/brew_potion.rs2
Fixed:
https://github.com/user-attachments/assets/6a9518e6-9f5b-42d2-940e-1a2bfcafe6ea
Current (broken):
https://github.com/user-attachments/assets/42055365-0e71-4257-a907-1e28e154ee49
=> fix(content): fix brewing for secondaries with multiple mixes

data/src/scripts/areas/area_karamja/scripts/trufitus.rs2, data/src/scripts/skill_fishing/scripts/fishing_spots/cage_harpoon_fishing.rs2, data/src/scripts/skill_fishing/scripts/fishing_spots/lure_bait_fishing.rs2, data/src/scripts/skill_fishing/scripts/fishing_spots/net_bait_fishing.rs2, data/src/scripts/skill_fishing/scripts/fishing_spots/net_harpoon_fishing.rs2, data/src/scripts/skill_fishing/scripts/fishing_spots/oil_rod_fishing.rs2
* Fishing spots work again!
* A dialogue branch in Shilo Village was ending early
=> fix: October 11th Alpha Hotfixes

data/src/scripts/interface_trade/scripts/trade.rs2, data/src/scripts/minigames/game_duelarena/scripts/duel_arena.rs2
before fix:
https://github.com/user-attachments/assets/9b63a28d-0b8d-4440-bfad-f4bd1d4cdca2
after fix:
https://github.com/user-attachments/assets/d9c2fa06-129f-4e62-a327-049fc18a0fc9
=> fix(content): missing p_stopaction for trading and dueling

data/src/pack/obj.pack, data/src/scripts/_unpack/all.obj, data/src/scripts/quests/quest_itwatchtower/configs/explodingvial.obj, data/src/scripts/quests/quest_itwatchtower/configs/quest_itwatchtower.obj, data/src/scripts/quests/quest_itwatchtower/scripts/ogre_potion.rs2, data/src/scripts/skill_herblore/configs/brewing/brew_potion.param, data/src/scripts/skill_herblore/configs/brewing/brew_potion.struct, data/src/scripts/skill_herblore/configs/brewing/potions_additives.obj, data/src/scripts/skill_herblore/configs/herbs.obj, data/src/scripts/skill_herblore/scripts/brewing/brew_potion.rs2, data/src/scripts/skill_herblore/scripts/grinding/grind_ingredient.rs2, data/src/scripts/skill_herblore/scripts/herblore.rs2, data/src/scripts/skill_prayer/configs/bones.obj
Used for watchtower quest, but you can brew them before/during/after completion
https://github.com/user-attachments/assets/82ccd80f-d480-47e5-814b-b980b5349d86
=> feat(content): Ogre potion brewing

data/src/pack/varp.pack, data/src/scripts/_unpack/all.varp, data/src/scripts/areas/area_wilderness/configs/wilderness.varp, data/src/scripts/areas/area_wilderness/scripts/wilderness_warning.rs2, data/src/scripts/engine.rs2, data/src/scripts/music/scripts/move.rs2, data/src/scripts/quests/quest_ikov/scripts/ikov_dungeon.rs2, data/src/scripts/skill_combat/scripts/pvp/pvp_combat.rs2, src/lostcity/engine/script/handlers/PlayerOps.ts, src/lostcity/entity/PathingEntity.ts, src/lostcity/entity/Player.ts
=> fix(engine): remove inauthentic last_coord command

data/src/pack/loc.pack, data/src/scripts/_unpack/all.loc, data/src/scripts/areas/area_gnome/configs/brimstail_cave.loc, data/src/scripts/areas/area_gnome/scripts/brimstail.rs2, data/src/scripts/areas/area_gnome/scripts/brimstail_cave.rs2, data/src/scripts/skill_runecraft/configs/runecraft.constant, data/src/scripts/skill_runecraft/scripts/essence_mine.rs2
https://discord.com/channels/953326730632904844/1297693881789583421
=> feat(content): brimstail cave

data/src/scripts/_unpack/all.npc, data/src/scripts/interface_bank/scripts/bank.rs2, data/src/scripts/skill_runecraft/scripts/runecraft.rs2
=> fix(content): missing mes's for rc and bank

package.json, src/lostcity/engine/GameMap.ts, src/lostcity/engine/Login.ts, src/lostcity/engine/World.ts, src/lostcity/engine/script/ScriptIterators.ts, src/lostcity/engine/script/handlers/PlayerOps.ts, src/lostcity/engine/script/handlers/ServerOps.ts, src/lostcity/entity/Npc.ts, src/lostcity/entity/PathingEntity.ts, src/lostcity/network/225/incoming/handler/ClientCheatHandler.ts
- Updates rsmod-pathfinder to 5.0.4 rust implementation.
- I simplified a bunch of functions/commands by consolidating similar rsmod uses together into `GameMap` class.
- This will making anything with pathfinding/collision/lines to be 2X faster than the AssemblyScript implementation from before. It's also 5X faster than the original TypeScript implementation from last year.
- This causes the world to take a few more seconds to start but the performance is worth it.
- More info can be found here: https://github.com/2004Scape/rsmod-pathfinder
- Fixes #956
- Closes #139
=> chore(engine): update rsmod-pathfinder dependency fixes #956

data/src/pack/varp.pack, data/src/scripts/_test/scripts/cheats/cheat_bank.rs2, data/src/scripts/_unpack/all.varp, data/src/scripts/areas/area_alkharid/scripts/shantay_pass.rs2, data/src/scripts/areas/area_desert/configs/desert_heat_zones.dbrow, data/src/scripts/areas/area_desert/scripts/desert_heat.rs2, data/src/scripts/macro events/scripts/woodcutting/macro_event_lost_axe.rs2, data/src/scripts/music/scripts/move.rs2, src/lostcity/engine/script/handlers/InvOps.ts
also inv_changeslot implementation (todo: need more information about the command)
=> feat(content): Desert heat

data/src/scripts/_test/scripts/cheats/cheat_help.rs2, data/src/scripts/_test/scripts/cheats/cheat_quest.rs2, data/src/scripts/areas/area_varrock/scripts/gertrude.rs2, data/src/scripts/quests/quest_fluffs/scripts/quest_fluffs.rs2
Little bit of organization for ::help
Fix a few errors in quest cheat command
=> feat(content): Update cheat and help menu

src/lostcity/engine/World.ts
movement related bug:
https://github.com/user-attachments/assets/26656573-f53f-43c8-864f-ec68c81ae7f5
follow unaffected:
https://github.com/user-attachments/assets/7ea107ce-7ee1-486d-bc2f-d545a76f0ad2
=> fix(engine): fixes #974

data/src/scripts/player/scripts/changestat.rs2, src/lostcity/engine/script/ServerTriggerType.ts, src/lostcity/engine/script/handlers/PlayerOps.ts, src/lostcity/entity/Player.ts
=> feat(engine): changestat implementation

src/lostcity/entity/PathingEntity.ts, src/lostcity/network/225/incoming/handler/OpHeldHandler.ts, src/lostcity/network/225/incoming/handler/OpHeldTHandler.ts, src/lostcity/network/225/incoming/handler/OpHeldUHandler.ts
Osrs:
https://github.com/user-attachments/assets/2c58827b-fe64-4b06-ac28-ab4a7953d1ab
Ours before fix:
https://github.com/user-attachments/assets/4668992d-f748-4997-8203-9eeef982dde9
Ours after fix:
https://github.com/user-attachments/assets/4139f305-857d-4b0f-901a-f09b4a692146
=> fix(engine): shouldnt continue to face entity after opheld

.env.example, package.json, src/lostcity/app.ts, src/lostcity/engine/World.ts, src/lostcity/prometheus.ts, src/lostcity/util/Environment.ts, src/lostcity/web.ts
Adds some basic prometheus metrics and an export endpoint
=> feat: prometheus metrics

.env.example, data/src/pack/npc.pack, data/src/pack/seq.pack, data/src/scripts/_unpack/all.seq, data/src/scripts/macro events/configs/antimacro.npc, package.json, src/lostcity/app.ts, src/lostcity/engine/World.ts, src/lostcity/prometheus.ts, src/lostcity/util/Environment.ts, src/lostcity/web.ts
Last feature for this week. Setting up recording metrics for our infrastructure!
=> feat: Prometheus metrics logging

.env.example, src/engine/World.ts, src/engine/entity/Player.ts, src/engine/entity/PlayerLoading.ts, src/network/rs225/client/handler/ClientCheatHandler.ts, src/server/logger/LoggerThread.ts, src/server/login/LoginClient.ts, src/server/login/LoginServer.ts, src/server/login/LoginThread.ts
=> feat: In-game moderation

data/src/scripts/interface_bank/scripts/bank.rs2, data/src/scripts/shop/scripts/shop.rs2, data/src/scripts/skill_magic/scripts/spells/alchemy.rs2, prisma/migrations/20250102101711_session_event_type/migration.sql, prisma/schema.prisma, src/db/types.ts, src/engine/World.ts, src/engine/entity/NetworkPlayer.ts, src/engine/entity/Player.ts, src/engine/script/handlers/InvOps.ts, src/engine/script/handlers/ObjOps.ts, src/engine/script/handlers/PlayerOps.ts, src/network/rs225/client/handler/ClientCheatHandler.ts, src/network/rs225/client/handler/OpHeldHandler.ts, src/network/rs225/client/handler/OpHeldTHandler.ts, src/network/rs225/client/handler/OpHeldUHandler.ts, src/server/logger/LoggerClient.ts, src/server/logger/LoggerServer.ts, src/server/logger/LoggerThread.ts, src/server/tcp/TcpServer.ts, src/server/ws/WSServer.ts
Additional logging:
- bank withdraw/deposit
- shop buy/sell
- high/low alch
- all opheld triggers
=> feat(engine): Storing session events by type

data/src/scripts/_unpack/all.loc, data/src/scripts/areas/area_port_sarim/scripts/dock_ladder.rs2, data/src/scripts/areas/area_yanille/configs/agility_dungeon.loc, data/src/scripts/drop tables/scripts/giant.rs2, data/src/scripts/general_use/configs/chests.loc, data/src/scripts/interface_trade/scripts/trade.rs2, data/src/scripts/login_logout/login.rs2, data/src/scripts/skill_cooking/scripts/cooking_inv/scripts/wine/wine.rs2, data/src/scripts/skill_crafting/configs/jewellery/jewellery.param, data/src/scripts/skill_crafting/configs/jewellery/jewellery.struct, data/src/scripts/skill_crafting/scripts/jewellery/jewellery.rs2, data/src/scripts/skill_crafting/scripts/jewellery/stringing.rs2, data/src/scripts/skill_magic/scripts/spells/superheat.rs2, data/src/scripts/skill_smithing/scripts/smelting/smelting.rs2
=> fix(content): trading, missing triggers, misc mes's

data/src/scripts/interface_bank/scripts/banker.rs2
Transcribed from https://classic.runescape.wiki/w/Transcript:Banker with mesanims taken from RS3
Closes #1046
=> fix(content): Add 'bank of varrock' banker dialog

src/engine/World.ts
It measures the time taken from the end of the last tick, to the start of the next tick.
From my testing on my pc, it ranges from ~5-15ms from the end to the start like that.
This keeps the game ticking, on average, the same time frame from when the app starts.
In the `before` picture, you can see how the date time slowly increases like 10ms every tick, while the `after` is kept around the same.
=> fix(engine): tick drift

data/src/scripts/skill_fishing/scripts/fishing_spots/lure_bait_fishing.rs2
- Allow fishing with feathers to continue if the last fish will replace your last feather.
- Allow fishing with bait to continue if the last fish will replace your last bait.
- None besides memories in discord
=> fix(content): allow 1 bait fishing

data/src/scripts/login_logout/login.rs2
I've encountered several people who weren't aware of this so I think we should add it back in. Better late than never!
=> fix(content): alpha 2.0 login mes

src/engine/entity/NetworkPlayer.ts
I think we can do it only when the player actually moves to a different zone. So I moved the logic to under `if (this.lastZone !== zone) {` condition where the zone triggers occur.
Also removed some redundant calculations.
=> refactor(engine): only update active zones when you change zones

data/src/scripts/interface_bank/scripts/bank.rs2
https://oldschool.runescape.wiki/w/Update:Patch_Notes_(13_June_2013)
=> fix(content): banking ana in a barrel

data/src/scripts/minigames/game_ranging/scripts/competition_judge.rs2
- add dialogue to buy arrows during a target session
- adjust dialogue based off:
=> fix(content): change comp judge dialogue (range guild)

data/src/scripts/_test/scripts/cheats/cheat_interactions.rs2, data/src/scripts/_test/scripts/engine/debug_huntall.rs2, data/src/scripts/_test/scripts/engine/debug_npc_huntall.rs2, data/src/scripts/areas/area_barbarian_village/scripts/beer_barrels.rs2, data/src/scripts/general/configs/hunt.constant, data/src/scripts/general/scripts/flavour_text/ducks.rs2, data/src/scripts/minigames/game_gnomeball/scripts/gnomeball.rs2, data/src/scripts/npc/scripts/barbarian.rs2, data/src/scripts/quests/quest_chompybird/scripts/bloated_toad.rs2, data/src/scripts/quests/quest_chompybird/scripts/rantz.rs2, data/src/scripts/quests/quest_cog/scripts/locs/quest_cog_food_trough.rs2, data/src/scripts/quests/quest_vampire/scripts/quest_vampire.rs2, src/engine/script/handlers/NpcOps.ts, src/engine/script/handlers/ServerOps.ts
- On OSRS, they only scream when they attack you with melee. They do not scream when you are attacking at range.
- When you use the empty glass on the barrel, many of them within a distance yell at you and try to engage combat.
- I refactored some constants out of some of the code.
----
=> feat(content): barbarians

data/src/scripts/areas/area_gnome/scripts/gnome_glider.rs2
Switches gnome chat head to player chat head
=> fix(content): gnome pilot chat fix

data/src/scripts/quests/quest_hero/scripts/npcs/grip.rs2
=> fix(content): heroes quest typo

data/src/scripts/areas/area_entrana/scripts/high_priest.rs2, data/src/scripts/areas/area_varrock/scripts/katrine.rs2, data/src/scripts/areas/area_varrock/scripts/straven.rs2, data/src/scripts/areas/areas_heroes_guild/scripts/achietties.rs2, data/src/scripts/minigames/game_trawler/scripts/murphy.rs2, data/src/scripts/quests/quest_chompybird/scripts/ogre_bow.rs2, data/src/scripts/quests/quest_hero/scripts/npcs/grip.rs2, data/src/scripts/quests/quest_zombiequeen/scripts/quest_zombiequeen.rs2
- corrected linebreaks in some quest dialogues according to old screenshots
- fixed instances of "theif"
- decapitalized certain instances of "Master Thief"
- replaced discord image links with imgur links
=> fix(content): authentic dialogues

data/src/scripts/areas/area_varrock/scripts/bartender.rs2
i used labels from an example from another NPC, where it asks a question and takes you back to previous multiple choice, but with difference choices as you progress. if there is a better way to do this i'd be interested in learning... but it works!
used RSProx to get the correct anims
=> fix(content): dancing donkey inn bartender dialogue

data/src/scripts/skill_combat/scripts/pvp/pvp_magic.rs2
this matches player_magic.rs2 and now works as expected
=> fix(content): mage arena spells in pvp

data/src/scripts/quests/quest_priest/scripts/quest_priest.rs2
- add oploc2 interaction to closed coffin during restless ghost
- change ghost to spawn before mesbox when searching
=> fix(content): Restless ghost coffin fix

data/src/scripts/skill_combat/scripts/player/player_combat.rs2
todo: engine work to default varns to null
=> fix(content): readd macro_event target check

data/src/scripts/drop tables/scripts/greater_demon.rs2
Fire rune 76 -> 75
Thread 1 -> 10
=> fix(content): greater demon drop table

data/src/scripts/tutorial/scripts/tutorial.rs2, src/engine/entity/Player.ts, src/engine/script/ScriptProvider.ts
Needs a new compiler release with https://github.com/LostCityRS/RuneScriptKt/pull/1 before merging.
=> fix(engine): Run if_close triggers directly without protected access

data/src/scripts/skill_cooking/scripts/cooking_guild.rs2
double spaces replaced with linebreaks, matches rsc
=> fix(content): head chef dialogue

src/engine/entity/Npc.ts
NPCs regen stats on their first turn alive in OSRS
PROOF:
https://gyazo.com/8f635f8e785bb7b7bf27cf08341ee4ad
=> fix(engine): Match NPC HP regen with RS2 behavior + conform to prettier stylings

data/src/scripts/quests/quest_grandtree/scripts/charlie.rs2, data/src/scripts/quests/quest_grandtree/scripts/shipyard_worker.rs2
as per comments, tick delays corrected
=> fix(content): grand tree tick delays: charlie, shipyard_worker

data/src/scripts/areas/area_ardougne_west/scripts/darkmage.rs2
aligned tick delay with comment `// 3t`
=> fix(content): darkmage tick delay

data/src/scripts/quests/quest_zombiequeen/scripts/quest_zombiequeen.rs2
ticks aligned with comments following delay fix
=> fix(content): shilo village tick delays

data/src/scripts/skill_combat/scripts/player/player_magic.rs2
https://github.com/user-attachments/assets/a5ba55b1-dcc8-436b-afd5-f51d7576b005
https://github.com/user-attachments/assets/4afd2036-32d5-4ea2-98f8-04e01fd61070
=> fix(content): remove opnpct triggers for spells to match osrs

src/network/rs225/client/handler/ClientCheatHandler.ts
Otherwise (for instance me) it's not clear whether you really had permission to run the command, or whether you got something wrong. This makes it clear what happened.
```
::ban
::kick
::mute
```
=> fix(engine): mod :: commands give text feedback

data/src/maps/labels.txt, data/src/scripts/areas/area_taverly/dungeon/scripts/jail_doors.rs2, data/src/scripts/areas/area_taverly/dungeon/scripts/prison_doors.rs2, data/src/scripts/ladders+stairs/scripts/stairs.rs2, data/src/scripts/quests/quest_scorpcatcher/scripts/quest_scorpcatcher.rs2, data/src/scripts/skill_fishing/configs/fishing.npc, data/src/scripts/skill_fishing/configs/fishing_movement.enum
Please don't anger the OCD. :) Also, Burthorpe is not Burthrope, for future ref. :)
=> fix(content): Renamed Taverly to Taverley in codebase

data/src/scripts/quests/quest_itexam/scripts/area_digsite.rs2
remove usages of strongqueue: https://github.com/2004scape/Server/wiki/RuneScript-Feature-History#11
=> fix(content): remove strongqueue usages

view/client.ejs
Ctrl-Alt-H was bringing Lost City client users to the home page. Cern and I tested Ctrl-alt-i as a replacement. :]
i am so sorry if i screwed something up
=> fix(client): Changed the hotkey to show Controls footer.

.github/workflows/migrations.yml
=> feat: add ci for migrations

data/src/scripts/skill_prayer/scripts/prayer_interface.rs2
=> fix(content): skulling clearing bug

data/src/scripts/drop tables/scripts/ice_giant.rs2
to match https://web.archive.org/web/20060108205211/http://www.runehq.com/RHQMonsterView.php?id=53
=> fix(content): remove addy arrow drop entirely from ice giant drops

data/src/scripts/minigames/game_trawler/scripts/trawler_bailing_bucket.rs2, data/src/scripts/skill_magic/scripts/spells/alchemy.rs2, data/src/scripts/skill_magic/scripts/spells/convert_bones.rs2, data/src/scripts/skill_magic/scripts/spells/enchant.rs2, data/src/scripts/skill_magic/scripts/spells/superheat.rs2, data/src/scripts/skill_magic/scripts/spells/telegrab.rs2, data/src/scripts/skill_magic/scripts/spells/teleport.rs2
also adds inv space check for telegrabbing
=> fix(content): p_delay's were too long for some client input triggers

data/src/scripts/skill_combat/scripts/pvp/pvp_combat.rs2, data/src/scripts/skill_combat/scripts/pvp/pvp_magic.rs2, data/src/scripts/skill_combat/scripts/pvp/pvp_melee.rs2, data/src/scripts/skill_combat/scripts/pvp/pvp_ranged.rs2
Not sure if authentic or not, can revert later if we find out this is wrong.
=> fix(content): Make combat antilog work as in osrs for now

data/src/scripts/_test/scripts/cheats/cheat_pvp.rs2, data/src/scripts/levelup/scripts/levelup_unlocks_ranged.rs2, data/src/scripts/skill_combat/scripts/pvp/pk_skull.rs2, data/src/scripts/skill_combat/scripts/pvp/pvp_combat.rs2, data/src/scripts/skill_combat/scripts/pvp/pvp_magic.rs2, data/src/scripts/skill_combat/scripts/pvp/pvp_melee.rs2, data/src/scripts/skill_combat/scripts/pvp/pvp_ranged.rs2, data/src/scripts/skill_prayer/scripts/prayer_interface.rs2, src/engine/entity/Player.ts, src/engine/entity/tracking/InputTracking.ts, src/network/rs225/client/handler/EventTrackingHandler.ts, view/client.ejs
Plus Website changes!
* #1303
* #1310
* #1319
* #1312
=> feat: February 18th Beta Updates

data/src/scripts/areas/area_white_wolf_mountain/scripts/white_wolf_mountain.rs2, data/src/scripts/skill_mining/scripts/mining.rs2
now correctly matches this video: https://youtu.be/ix4_VVi9Xm4
=> fix(content): mining anims and sounds

src/engine/World.ts, src/engine/entity/Entity.ts, src/engine/entity/Loc.ts, src/engine/entity/Npc.ts, src/engine/entity/Obj.ts, src/engine/entity/PathingEntity.ts, src/engine/entity/Player.ts, src/engine/script/ScriptIterators.ts, src/engine/script/handlers/ObjOps.ts, src/engine/zone/Zone.ts
Players now have slightly better logic for handling if they are in range to op and Obj. Further, unsetMapFlag() will no longer be called every tick
This PR stacks on https://github.com/2004Scape/Server/pull/1302 to avoid merge conflicts
=> fix(engine): Player unsetmapflag called less often and player inOperableDistance() improved

data/src/scripts/_unpack/all.npc
https://youtu.be/_yejdWUagek?t=293
This also matches black knights
=> fix(content): ice warrior huntrange to 5 to match 2006 vid

data/src/pack/loc.pack, data/src/pack/npc.pack, data/src/scripts/_unpack/all.loc, data/src/scripts/_unpack/all.npc, data/src/scripts/areas/area_ardougne_east/scripts/necromancer_tower.rs2, data/src/scripts/areas/area_combat_training/configs/combat_training_camp.loc, data/src/scripts/areas/area_combat_training/scripts/combat_training_camp.rs2, data/src/scripts/areas/area_taverly/scripts/crystal_chest.rs2, data/src/scripts/areas/area_yanille/configs/ogre.npc, data/src/scripts/areas/area_yanille/scripts/ogre_merchant.rs2, data/src/scripts/areas/area_yanille/scripts/ogre_trader.rs2, data/src/scripts/drop tables/scripts/chaos_dwarf.rs2, data/src/scripts/quests/quest_itwatchtower/scripts/quest_itwatchtower.rs2
Mostly I just wanted to test the vscode extension rename symbol implementation
=> chore(content): Naming some unnamed npcs, locs

data/src/scripts/areas/area_falador/scripts/makeover_mage.rs2, src/engine/World.ts, src/engine/entity/Loc.ts, src/engine/entity/NetworkPlayer.ts, src/engine/entity/Player.ts, src/engine/entity/tracking/InputTracking.ts, src/engine/script/handlers/LocOps.ts, src/engine/script/handlers/PlayerOps.ts, src/engine/zone/Zone.ts, src/network/rs225/client/handler/ClientCheatHandler.ts, src/network/server/OutgoingMessage.ts
* #1345
* Less overhead for pending messages
* Reverting zone changes from last update - did not solve what it wanted to, helped us get a reproduction case
=> fix: Bug fixes, some engine cleanup

src/engine/entity/NetworkPlayer.ts
This is not what OSRS does today but it seems like this is the only way for us... This will force the client to unload the zones already in view, but are outside of the loading lines, before rebuild_normal, which unlinks all the temp locs, and then we perform normal zone events....
=> fix(engine): client hard unload zones outside of the loading lines

src/engine/entity/Player.ts, src/network/client/model/MessagePrivate.ts, src/network/client/model/MessagePublic.ts, src/network/rs225/client/codec/MessagePrivateDecoder.ts, src/network/rs225/client/codec/MessagePublicDecoder.ts, src/network/rs225/client/handler/FriendListAddHandler.ts, src/network/rs225/client/handler/FriendListDelHandler.ts, src/network/rs225/client/handler/IgnoreListAddHandler.ts, src/network/rs225/client/handler/IgnoreListDelHandler.ts, src/network/rs225/client/handler/MessagePrivateHandler.ts, src/network/rs225/client/handler/MessagePublicHandler.ts, src/network/rs225/client/handler/ReportAbuseHandler.ts
https://youtu.be/s9R_K6cGGMA?t=81
=> feat(engine): additional packet protection for social input

src/engine/World.ts, src/engine/entity/NetworkPlayer.ts, src/engine/entity/Player.ts
- Resync rebuild normal after the scene state protection additions on reconnect.
- Resync stats on reconnect.
- Resync friends and ignores list on reconnect.
=> fix(engine): more client reconnection resyncing

data/src/scripts/areas/area_entrana/scripts/monk_entrana.rs2
wasn't updated, hadn't realized it was copy pasted from monastery monk
from 5 to 4 ticks
=> fix(content): monk of entrana heal_self interval correction

data/src/scripts/areas/area_edgeville/scripts/oracle.rs2
=> fix(content): typo in oracles dialogue

data/src/scripts/_test/scripts/cheats/cheat_quest.rs2, data/src/scripts/general/configs/quest.enum
Added option to complete all quests at once and reset all quests at once
=> feat(content): Update cheat_quest.rs2

data/src/scripts/_test/scripts/cheats/cheat_bank.rs2
New cheat to spawn f2p combat items into bank as a preset
=> feat(content): Update cheat_bank.rs2

src/engine/entity/BuildArea.ts
- Check for lifecycle just in case.
- Move the `has` check to the front as this is the most common case.
=> fix(engine): explicity check for lifecycle in build area

data/src/scripts/login_logout/login.rs2, data/src/scripts/player/scripts/stat.rs2
=> feat(content): boost reset on f2p login

data/src/scripts/quests/quest_grail/configs/fisher_realm.npc, data/src/scripts/quests/quest_grail/scripts/black_knight_titan.rs2
add blockwalk property and remove additional delays
=> fix(content): extra changes to black knight titan

data/src/scripts/quests/quest_itgronigen/scripts/observatory_professor.rs2
Fix an issue that was allowing you to repeat observatory quest if you have a coordinate clue after the quest is complete
=> fix(content): observatory quest bug

data/src/scripts/skill_combat/scripts/player/player_melee.rs2
Missed this. Meant to get it in https://github.com/2004Scape/Server/pull/1385
=> refactor(content): remove unnecessary sir_mordred and black knight titan check in player_melee.rs2

src/db/types.ts, src/engine/World.ts, src/engine/entity/Player.ts, src/engine/script/handlers/PlayerOps.ts, src/server/login/LoginClient.ts, src/server/login/LoginServer.ts, src/server/login/index.d.ts, src/util/Messages.ts
=> feat(engine): Display the user's unread messages on the welcome screen

data/src/scripts/skill_combat/scripts/player/player_melee.rs2
Could've sworn I did this in https://github.com/2004Scape/Server/pull/1402. Bug caught by b5 👀
=> fix(content): missing damage cap and heropoints for player_melee.rs2

data/src/scripts/skill_combat/scripts/player/player_attackstyles.rs2
missed this in https://github.com/2004Scape/Server/pull/1397
=> fix(content): ~player_combat_stat in ~set_attackstyle

data/src/scripts/areas/area_camelot/scripts/sir_lancelot.rs2
The one case was fixed but the same line in the other case wasn't.
=> fix(content): Another.. extra space in Lancelot dialogue

data/src/scripts/player/scripts/death.rs2
=> fix(content): change death to p_teleport instead of p_telejump

data/src/scripts/areas/area_draynor/scripts/ned.rs2
Add wig option to Ned's dialogue when returning from crandor, but before defeating Elvarg
=> fix(content): add prince ali option to post crandor ned chain

data/src/scripts/areas/area_lumbridge/scripts/duke_horacio.rs2
I base this change on video I found from 2008: https://youtu.be/rCC0CJQoXAE?t=16
=> fix(content): Duke Horacio typo

data/src/scripts/skill_prayer/scripts/prayers/clarity.rs2, data/src/scripts/skill_prayer/scripts/prayers/improvedreflexes.rs2, data/src/scripts/skill_prayer/scripts/prayers/incrediblereflexes.rs2, data/src/scripts/skill_prayer/scripts/prayers/protectfrommagic.rs2, data/src/scripts/skill_prayer/scripts/prayers/protectfrommelee.rs2, data/src/scripts/skill_prayer/scripts/prayers/protectfrommissiles.rs2, data/src/scripts/skill_prayer/scripts/prayers/protectitems.rs2, data/src/scripts/skill_prayer/scripts/prayers/rapidheal.rs2, data/src/scripts/skill_prayer/scripts/prayers/rapidrestore.rs2, data/src/scripts/skill_prayer/scripts/prayers/rockskin.rs2, data/src/scripts/skill_prayer/scripts/prayers/steelskin.rs2, data/src/scripts/skill_prayer/scripts/prayers/strengthburst.rs2, data/src/scripts/skill_prayer/scripts/prayers/superhumanstrength.rs2, data/src/scripts/skill_prayer/scripts/prayers/thickskin.rs2, data/src/scripts/skill_prayer/scripts/prayers/ultimatestrength.rs2
from videos: 
- https://youtu.be/j-Z-43CzpZQ?t=120
- https://youtu.be/NT74s7nJwAo?t=21
- https://youtu.be/fcRgR_4ZbdA
=> fix(content): clear interactions on prayer click

src/engine/script/handlers/PlayerOps.ts
was missed in https://github.com/2004Scape/Server/pull/1429
=> fix(engine): missing arg passed through setInteraction in p_opnpct handler

data/src/scripts/areas/area_port_sarim/scripts/klarense.rs2
wouldnt -> wouldn't
https://classic.runescape.wiki/w/Transcript:Klarense#After_asking_Oziach_details_on_the_Dragon
=> fix(content): klarense typo

data/src/scripts/skill_combat/scripts/player/player_attackstyles.rs2
missed in https://github.com/2004Scape/Server/pull/1458
=> fix(content): clear interaction on attackstyle change

data/src/scripts/quests/quest_arena/configs/quest_arena.constant, data/src/scripts/quests/quest_arena/configs/quest_arena.npc, data/src/scripts/quests/quest_arena/scripts/bouncer.rs2, data/src/scripts/quests/quest_arena/scripts/general_khazard.rs2, data/src/scripts/quests/quest_arena/scripts/hengrad.rs2, data/src/scripts/quests/quest_arena/scripts/khazard_ogre.rs2, data/src/scripts/quests/quest_arena/scripts/khazard_scorpion.rs2, data/src/scripts/quests/quest_mcannon/scripts/cannon.rs2
- Fixes to the Hengrad cutscene in fight arena
- Add maxrange property to general khazard
- change some of the area checks in the arena npc death queues
- Add death script to general khazard, previously it would not increment the quest varp
=> fix(content): fight arena changes

data/src/scripts/areas/area_ardougne_east/scripts/wizard_cromperty.rs2
**Haven't completed Rune Mysteries:**
**Completed Rune Mysteries:**
=> feat(content): Add Rune Essence teleport to Wizard Cromperty

data/src/scripts/quests/quest_itgronigen/scripts/observatory_professor.rs2, data/src/scripts/quests/quest_zombiequeen/scripts/nazastarool.rs2, data/src/scripts/quests/quest_zombiequeen/scripts/quest_zombiequeen.rs2
- change zone check behaviour for nazasatrool to match OSRS
- disable usage of zqcrystal after zombiequeen completion
- fix issue with observatory prof dialogue
=> fix(content): changes to nazasatarool, fix for prof dialogue

data/src/scripts/minigames/game_duelarena/scripts/duel_arena.rs2, data/src/scripts/minigames/game_duelarena/scripts/duel_arena_settings.rs2, data/src/scripts/minigames/game_duelarena/scripts/duel_arena_start.rs2, data/src/scripts/skill_magic/scripts/spells/teleport.rs2
Replaced some of Tanner's message guest with RS3 messages
=> feat(content): More Duel Arena messages

data/src/scripts/minigames/game_trawler/configs/trawler.constant, data/src/scripts/minigames/game_trawler/scripts/trawler_gangplank.rs2, data/src/scripts/minigames/game_trawler/scripts/trawler_sink.rs2, data/src/scripts/minigames/game_trawler/scripts/trawler_start.rs2
- need to figure out if theres an npc_gettimer command. But for now it just use a varn to keep track of the timer for murphy
- rewrites some shark logic to not npc_delay them
=> fix(content): trawler not starting games properly

README.md
This pull request includes updates to the `README.md` file to improve clarity and correct formatting issues. The most important changes are listed below:
Improvements to documentation:
* Corrected punctuation and improved clarity in the setup instructions.
* Added missing periods to the end of list items in the setup instructions.
* Added a new section for the project's license, specifying that it is licensed under the MIT License and providing a link to the license details.
=> chore: Small proofread of README

data/src/scripts/doors/scripts/doubledoors.rs2, data/src/scripts/doors/scripts/open_and_close_double_doors.rs2, data/src/scripts/engine.rs2, data/src/scripts/quests/quest_upass/configs/upass.npc
rework open-and-close double doors to get the open loc types from loc_param before the delay to prevent script errors (created separate procs for this so other double doors don't have to be changed), also add huntrange to blessed spiders
=> fix(content): double doors proc changes

data/src/scripts/_test/scripts/cheats/cheat_zone.rs2, src/engine/script/handlers/LocOps.ts
Oops! Loc type wasn't being checked in this handler and this led to a server crash
It's now being checked properly + there's a debugproc to test
=> fix(engine): Loc type is now properly being checked in loc_change

src/engine/GameMap.ts, src/engine/entity/PathingEntity.ts, src/engine/entity/Player.ts
https://youtu.be/NN5O08mNxTg?t=1170
https://youtu.be/_a-y7BHtdV8?t=120
=> feat(engine): prevent teleporting to invalid areas of the map

src/engine/entity/Player.ts, src/engine/entity/PlayerLoading.ts, src/engine/script/handlers/PlayerOps.ts
=> feat(engine): days since last login message on the welcome screen

package.json, pnpm-lock.yaml
https://github.com/2004Scape/rsbuf/pull/1
=> chore(engine): update rsbuf dependency version

data/src/scripts/player/scripts/equip.rs2
=> fix(content): equip.rs2

view/client.ejs
=> fix(mobile): add keyboard choice selection in client.ejs

data/src/scripts/macro events/scripts/macro_events.rs2, data/src/scripts/skill_cooking/scripts/cooking_inv/scripts/dough/dough.rs2
p_choice comes from:
- https://youtu.be/n79WMvBkFTc
- https://youtu.be/Tix1wbx3YCc
pitta mes comes from 2025 osrs: 
Members mes is guessed
=> feat(content): ability to make pitta dough

data/src/scripts/player/scripts/consumption/consume.rs2
todo: figure out if stuff like cakes should use this?
=> fix(content): pizza halves should appear in first slot after eating a full pizza

data/src/scripts/areas/area_desert/scripts/bedabin_nomad.rs2, data/src/scripts/areas/area_taverly/scripts/kaqemeex.rs2, data/src/scripts/doors/scripts/door_procs.rs2, data/src/scripts/doors/scripts/open_and_close_doors.rs2, data/src/scripts/general/scripts/quests.rs2, data/src/scripts/quests/quest_chompybird/scripts/rantz.rs2, data/src/scripts/quests/quest_cog/scripts/locs/quest_cog_gates_and_levers.rs2, data/src/scripts/quests/quest_itwatchtower/scripts/enclave_guard.rs2, data/src/scripts/quests/quest_upass/scripts/upass_bridge.rs2, data/src/scripts/skill_combat/scripts/npc/npc_combat.rs2, data/src/scripts/skill_thieving/configs/doors/locked_door.dbrow, data/src/scripts/skill_thieving/scripts/doors/locked_door.rs2
- add missing @multi to kaqemeex dialogue
- fix looping in bedabin nomad dialogue
- lower rantz timer for hunting chompies
- changes to mirrored locked doors, fix ardougne sewer gates to use correct opened locs
- fix some watchtower related checks post quest
=> fix(content): Various content fixes

data/src/scripts/quests/quest_arthur/scripts/quest_arthur.rs2, data/src/scripts/skill_smithing/scripts/smelting/cannonballs.rs2
also map_members check for cannonballs
=> feat(content): bucket crate

data/src/scripts/quests/quest_totem/scripts/quest_totem.rs2, data/src/scripts/quests/quest_zombiequeen/scripts/quest_zombiequeen.rs2, data/src/scripts/skill_agility/scripts/agility.rs2, data/src/scripts/skill_agility/scripts/wilderness_course.rs2
- fix bug with wilderness rocks obstacle, also add another appearance updating proc for convenience
- fix crate message in handelmorts mansion showing the incorrect address
=> fix(content): wilderness rocks, tribal totem message

data/src/scripts/skill_prayer/scripts/prayers/steelskin.rs2
oops!
Video of bug:
https://github.com/user-attachments/assets/6160419a-bca4-4207-9563-cb0057248b77
=> fix(content): steelskin prayer drain could exponentially stack

data/src/scripts/macro events/configs/antimacro.npc, data/src/scripts/macro events/scripts/woodcutting/macro_event_ent.rs2
Relies on https://github.com/2004Scape/Server/pull/1587
=> fix(content): ents were making trees walk throughable

data/src/pack/loc.pack, data/src/scripts/_unpack/all.loc, data/src/scripts/drop tables/scripts/chaos_druid.rs2, data/src/scripts/quests/quest_itgronigen/configs/grave_of_scorpius.loc, data/src/scripts/quests/quest_itgronigen/scripts/grave_of_scorpius.rs2
* Added Observatory Quest completion check for Chaos Druids dropping unholy symbol
* Added missing mesbox for reading the Grave of Scorpius (mesbox is Identical in RS3 and OSRS)
=> fix(content): Chaos Druid drop table and Grave of Scorpius mesbox

data/src/scripts/quests/quest_upass/scripts/quest_upass.rs2, data/src/scripts/quests/quest_upass/scripts/upass_obstacles.rs2
- add coord check to the ledge in the 2nd area, so you cant climb it from the pit
- allow using the doll of iban on any stage before killing iban, so you can enter + make the doll before throwing it in
=> fix(content): few upass bug fixes

data/src/scripts/skill_smithing/scripts/smithing/smithing.rs2
Reported by septim150 on Discord
https://discord.com/channels/953326730632904844/1358520956351414493
(If this is not the proper way to fix this issue, please advise)
=> fix(content): Dart tips not hilighting after tourist trap

data/src/scripts/quests/quest_legends/scripts/nezikchened.rs2, data/src/scripts/quests/quest_legends/scripts/quest_legends.rs2, data/src/scripts/skill_combat/scripts/player/player_ranged.rs2
- fix an issue where decanting pure water from golden bowl -> vial would change charges incorrectly
- add defence reduction to holy water usage
- add decanting from golden bowl -> enchanted vial to create holy water
=> fix(content): golden bowl decanting

data/src/scripts/general_use/configs/water_sources.loc, data/src/scripts/general_use/scripts/water_sources.rs2
also use the correct synth for filling from wells, use a separate category and remove string comp
=> fix(content): fix well script

data/src/scripts/skill_combat/scripts/player/player_attackstyles.rs2, data/src/scripts/skill_magic/scripts/spells/convert_bones.rs2
=> fix(content): only allow bones to bananas for regular bones

data/src/scripts/ladders+stairs/scripts/stairs.rs2
Did a search through the map files to compare with the stair script and these should be the only 2 sets of stairs we are still missing (that are reachable)
=> fix(content): Missing stairs

data/src/scripts/quests/quest_legends/configs/legends_gem_data.dbrow, data/src/scripts/quests/quest_legends/configs/quest_legends.constant, data/src/scripts/quests/quest_legends/scripts/quest_legends.rs2, data/src/scripts/skill_magic/scripts/spells/telegrab.rs2
- changes to some messages during gem puzzle to match rs3, also fix capitalization
- add full interaction to buried skeleton in the room
=> fix(content): legends gem puzzle changes

data/src/scripts/quests/quest_desertrescue/scripts/quest_desertrescue.rs2
the oplocu interaction was checking the wrong side when entering
=> fix(content): desertcamp door check

data/src/scripts/quests/quest_legends/scripts/ungadulu.rs2
Fixes chat-head for dagger return dialogue with Ungadulu
=> fix(content): Legends Quest "Given Dagger" Chat-head Fix

data/src/scripts/drop tables/scripts/necromancer.rs2
probably a typo: https://oldschool.runescape.wiki/w/Necromancer
=> fix(content): bad drop rates for necromancer

data/src/scripts/drop tables/scripts/imp.rs2
-Removed comments,
-Replaced magic number "200" drop duration with "^lootdrop_duration"
-Rename variable "$dropint" to "$random"
=> chore: Normalize imp.rs2 for consistency with other drop_table/*.rs2 files

data/src/scripts/quests/quest_arthur/scripts/quest_arthur.rs2, data/src/scripts/quests/quest_elena/scripts/sewerpipe.rs2, data/src/scripts/skill_agility/scripts/barbarian_course.rs2, data/src/scripts/skill_agility/scripts/shortcuts.rs2, data/src/scripts/skill_agility/scripts/wilderness_course.rs2
https://youtu.be/HwboEn6-MTk?si=OjvXH87hF04VGAg-&t=38 (also OSRS)
=> fix(content): add arrive delay to wilderness course rocks

data/src/scripts/areas/area_lumbridge/configs/lumbridge.npc, data/src/scripts/areas/area_lumbridge/scripts/hans.rs2
adds Hans patrol path/mode, and changes dialogue to match early OSRS
On patrol path here: 
(RS2 Beta)
=> fix(content): Hans patrol, dialogue changes

data/src/scripts/areas/area_camelot/scripts/king_arthur.rs2, data/src/scripts/areas/area_camelot/scripts/sir_kay.rs2, data/src/scripts/quests/quest_desertrescue/scripts/camp_guard.rs2, data/src/scripts/quests/quest_fluffs/configs/quest_fluffs.vars, data/src/scripts/quests/quest_fluffs/scripts/quest_fluffs.rs2, data/src/scripts/quests/quest_itgronigen/scripts/quest_itgronigen.rs2
=> fix(content): some dialogue fixes, lumberyard fence var

data/src/scripts/areas/area_varrock/scripts/straven.rs2
In case you've joined both gangs
=> fix(content): Straven will always talk to players in the phoenix gang

data/src/scripts/quests/quest_itexam/scripts/digsite_workman.rs2
https://github.com/user-attachments/assets/f20b4b99-fc4b-4d22-9240-d8ec3b3ab6e8
=> fix(content): missing code for digsite workman pickpocketing
