- README.md
NodeJS 19 is already at end-of-life and has been for the last 2 months
NodeJS 18 is supported for another 2 years
We should not recommend odd-numbered users to anyone, ever. Only people specifically looking to be part of NodeJS beta channels.
> docs: remove recommendation for NodeJS 19

- README.md
- package-lock.json
- package.json
Now we can just do `npm run dev` rather than fiddling with multiple terminals
This makes it easier to run as dev but also will make Dockerisation (see #17) easier
> build: use `concurrently` for one-command dev startup

- src/lostcity/entity/Player.ts
> fix: ::jtele command now uses level properly.

- data/src/scripts/quests/quest_cook/scripts/quest_cook.rs2
Got messed up during implementation of ~send_quest_complete proc due to lazy c&p.
> fix: Quest complete interface text correct for Cook's Assistant quest.

- .vscode/launch.json
- README.md
I had two issues with this:
- I can't use `integratedTerminal` (which I'd like to) but I think this might be some issue with my local setup (Unix-like shell in Windows environment)
- I can't reliably get console output from the tests
However besides that this seems to work well and uses the default VS Code inspector for stepping through the breakpoints.
Please test this branch on your machines and see if it all works for you too.
> build: add VS Code launch tasks for Jest debugging

- data/src/scripts/_test/scripts/debug_telejump.rs2
- data/src/scripts/_unpack/all.loc
- data/src/scripts/_unpack/all.npc
- data/src/scripts/areas/area_alkharid/configs/border_gate.loc
- data/src/scripts/areas/area_alkharid/configs/border_guard.npc
- data/src/scripts/areas/area_alkharid/scripts/border_gate.rs2
- data/src/scripts/areas/area_lumbridge/scripts/shortcuts.rs2
- data/src/scripts/areas/area_taverly/dungeon/scripts/prison_doors.rs2
- data/src/scripts/engine.rs2
- data/src/scripts/general_use/scripts/pickables.rs2
- data/src/scripts/skill_thieving/scripts/doors/locked_door.rs2
- docs/scripts.md
- src/lostcity/engine/script/ScriptOpcode.ts
- src/lostcity/engine/script/handlers/NpcOps.ts
- src/lostcity/engine/script/handlers/PlayerOps.ts
- src/lostcity/engine/script/handlers/ServerOps.ts
- src/lostcity/entity/Npc.ts
- src/lostcity/entity/PathingEntity.ts
- src/lostcity/entity/Player.ts
- Border gate guards now scout the area and no longer move around.
- Border gates now properly open and block clipping.
- Players can now pay 10 coins to pass through the border gates.
- `p_walk` is now used for walking with pathfinding support.
- `p_tele` renamed to `p_teleport`.
- Update scripts that used `p_walk` to now use `p_teleport`
- Update other npc wander ranges and moverestricts.
- Fixed `lineofwalk` to use correct dest sizes and remove alternative check.
- `PathingEntity` orientations now update properly when teleporting/jumping, to the player client. (When they are new to your view)
- `Npc` orientations now update properly when turning, to the player client. (When they are new to your view)
> 💂Implement the Lumbridge/Al Kharid border toll gates and guards.

- data/pack/seq.pack
- data/src/scripts/_unpack/all.seq
Angry and Beckon had the incorrect IDs associated with them. I was able to just swap the two and it resolved the issue with doing emotes from the emotes tab as well.
> Swapped Angry and Beckon to be the correct ids

- src/lostcity/engine/World.ts
if you try to p_teleport with a > 2 change in only x or z, you will try to walk it and desync client/server player pos, this fixes it by checking for both dx and dz < 2 before converting to walk/run
> fix walking tele

- data/src/scripts/_unpack/all.npc
- data/src/scripts/areas/area_rimmington/configs/rimmington.npc
- data/src/scripts/areas/area_yanille/configs/yanille.npc
- src/lostcity/engine/World.ts
- src/lostcity/engine/collision/CollisionManager.ts
- src/lostcity/engine/collision/NpcCollider.ts
- src/lostcity/entity/PathingEntity.ts
- src/lostcity/entity/Player.ts
- Also fixes `Player#inOperableDistance` for npcs size > 1
- Also fixes `NpcCollider` by now changing collision for their entire size and not just their SW tile.
> Add fixes to npc wanderrange and attackrange properties.

- data/src/scripts/areas/area_varrock/scripts/captain_rovin.rs2
- data/src/scripts/ladders+stairs/scripts/stairs.rs2
- data/src/scripts/quests/quest_demon/scripts/demon_slayer.rs2
Fixes:
- Stairs now work in the Varrock Castle and Wizard Tower.
- Once "killed" Delrith resets to his non-weakened form.  This is temporary until we can actually defeat him in combat.
- The sewer drain now correctly checks for only a bucket of water rather than letting you use any item.
- - This matches the functionality of RSC, as well as being able to have multiple keys spawned in the sewer at once
- Captain Rovin is now willing to talk about having a key after speaking with Sir Prysin.
> Demon Slayer fixes

- .github/workflows/pr-conventional-commits.yml
Checks that PR titles are in the [conventional commits format](https://www.conventionalcommits.org/)
This will allow @Pazaz  to one-click merge without changing commit message
> ci: lint PR titles for conventional commits

- data/src/scripts/areas/area_alkharid/scripts/border_gate.rs2
- data/src/scripts/areas/area_barbarian_outpost/scripts/outpost_gate.rs2
- data/src/scripts/areas/monastery/scripts/prayer_guild.rs2
- data/src/scripts/engine.rs2
- data/src/scripts/general/scripts/misc/coord_procs.rs2
- data/src/scripts/levelup/scripts/levelup.rs2
- data/src/scripts/quests/quest_fishingcompo/scripts/hemenster_fishing.rs2
- data/src/scripts/quests/quest_fishingcompo/scripts/quest_fishingcompo.rs2
- data/src/scripts/skill_combat/scripts/requirements/dragon_requirements.rs2
- data/src/scripts/skill_combat/scripts/requirements/equip_requirements.rs2
- data/src/scripts/skill_thieving/scripts/stalls/stealing.rs2
- data/src/scripts/skill_thieving/scripts/thieving.rs2
- src/lostcity/cache/NpcType.ts
- src/lostcity/engine/hunt/HuntMode.ts
- src/lostcity/engine/script/handlers/LocOps.ts
- src/lostcity/engine/script/handlers/NpcOps.ts
- src/lostcity/engine/script/handlers/ObjOps.ts
- src/lostcity/entity/Interaction.ts
- src/lostcity/entity/Npc.ts
- src/lostcity/entity/PathingEntity.ts
- src/lostcity/entity/Player.ts
- src/lostcity/tools/packconfig/NpcConfig.ts
> fix: Secondary Pointers. HuntMode Packing. 

- data/src/scripts/general_use/scripts/pickables.rs2
- data/src/scripts/player/scripts/drop.rs2
- data/src/scripts/player/scripts/inventory.rs2
- data/src/scripts/player/scripts/pickup.rs2
feat: Flax picking added, 1 time-use, 20t respawn (Adjusts based on worldpop).
feat: Made `pickup_loc_floor` take boolean value for input to determine if respawn rate should be adjusted based on worldpop.
feat: Added sounds to dropping and picking up items.
fix: Removed excess checks in `drop.rs2` & `inventory.rs2`.
> feat: Misc. changes

- data/src/scripts/player/scripts/damage.rs2
- src/lostcity/cache/NpcType.ts
- src/lostcity/entity/Npc.ts
- Fixes npcs running ai scripts under specific conditions when they shouldnt be.
- Defaults `maxrange=10` because at 5 just looks wrong when at range > 5 and npcs do nothing.
> fix: npc ai_mode improperly running

- data/src/scripts/general/scripts/misc/wine_of_zamorak.rs2
- data/src/scripts/player/scripts/pickup.rs2
Code for stealing Wine of Zamorak
Features:
* Reduces Attack, Strength, Defence, Ranged, Magic by 5%
* Damages player by their HP level / 20 + 1
* All monks in both zones attack player
* When all monks are dead the player can take the wine, but still receives damage (confirmed this happens on RS)
* Player can telegrab the wine
> feat: Stealing Wine of Zamorak

- data/src/scripts/quests/quest_blackknight/scripts/quest_blackknight.rs2
Black Knights inside their fortress now aggro when going into the dining hall or exiting onto the balcony before the grill.
> fix: Black Knights Aggro when going through doors in their fortress.

- data/src/scripts/player/scripts/equip.rs2
Fixes: ***When you try to equip arrows with a different type of arrows equipped and a full inventory it tells you that your inventory is full rather than swapping the arrows.***
> fix: equipping/unequipping of stackable objs properly

- src/lostcity/engine/GameMap.ts
Static OBJ spawns now take into account the member property when spawning, no more blood rune spawns in free-to-play worlds.
> fix: Member OBJs only spawn in member worlds.

- data/src/scripts/areas/area_wizard_tower/scripts/wizard_grayzag.rs2
- data/src/scripts/macro events/scripts/mining/macro_event_rock_golem.rs2
- data/src/scripts/npc/scripts/dragon.rs2
- data/src/scripts/player/scripts/consumption/effects/scripts/anti_fire.rs2
- data/src/scripts/player/scripts/consumption/effects/scripts/anti_poison.rs2
- data/src/scripts/player/scripts/global.rs2
- data/src/scripts/player/scripts/logout.rs2
- data/src/scripts/quests/quest_dragon/scripts/elvarg.rs2
- data/src/scripts/quests/quest_dragon/scripts/melzar_the_mad.rs2
- data/src/scripts/skill_combat/scripts/npc/npc_combat.rs2
- Antipoison and antifire persists after logging back in. Not sure if stat buffs or potion buffs like antifire & antipoison should be removed on logout.
- Elvarg attack switching chances
- Dragon fire for colored dragons (same chances as elvarg for now)
- Not every npc's retaliations were updated for singles/multi logic. Added a npc_default_retaliate_ap proc, I think most monsters that have an ap attack always auto retaliate with ap first.
> feat: dragon fire for dragons and other small fixes

- data/src/scripts/areas/area_mage_arena/scripts/chamber.rs2
- data/src/scripts/player/scripts/damage.rs2
fix: losing god cape on death didnt check if the slot had an item, before checking the item category
fix: typo 'veigns' -> 'veins'
> fix: death

- data/src/scripts/player/scripts/global.rs2
- data/src/scripts/tutorial/configs/tutorial.npc
- data/src/scripts/tutorial/scripts/guides/brother_brace.rs2
- data/src/scripts/tutorial/scripts/guides/combat_instructor.rs2
- data/src/scripts/tutorial/scripts/guides/financial_advisor.rs2
- data/src/scripts/tutorial/scripts/guides/magic_instructor.rs2
- data/src/scripts/tutorial/scripts/guides/master_chef.rs2
- data/src/scripts/tutorial/scripts/guides/mining_instructor.rs2
- data/src/scripts/tutorial/scripts/guides/quest_guide.rs2
- data/src/scripts/tutorial/scripts/guides/survival_guide.rs2
- data/src/scripts/tutorial/scripts/npcs/tut_giant_rat.rs2
- data/src/scripts/tutorial/scripts/skills/tut_smelting.rs2
- data/src/scripts/tutorial/scripts/skills/tut_smithing.rs2
- data/src/scripts/tutorial/scripts/tut_chatbox_steps.rs2
- data/src/scripts/tutorial/scripts/tut_doors_and_gates.rs2
- data/src/scripts/tutorial/scripts/tutorial.rs2
Thanks to everyone who chipped in testing and finding all of these issues and never ending typos. I'm sure there will be more time come.
Fixes:
- Removal of inventory full messages. Items now drop to the ground
- Loads of typos for NPC and tutorial step dialogues
- Smelting now requires both copper and tin ores
- Updated bonuses and weight when player controls and equipment screens are shown
- Rats can no longer be ranged after you've completed that step
- Corrected mind rune total when completing the tutorial
- Fixed incorrect timing of display for attack styles tab
> fix: Tutorial Island warranty fixes

- data/src/scripts/skill_combat/configs/ranged/bolts.obj
- data/src/scripts/skill_combat/scripts/player/player_ranged.rs2
this is a controversial one because there's no concrete data on any of this. Guesses were made based off of lunagang.nl's guesses.
pearl bolts are now usable, too, since the crossbow is no longer "too low level" for them.
> fix: change bolt rangebonus and pearl bolt's required level

- data/src/scripts/interface_bank/scripts/bank.rs2
- check for oc_stackable instead of oc_cert
- new message if inv_freespace(inv) = 0 (same as osrs)
- inv_itemspace instead of inv_itemspace2
- move "This item can not be withdrawn as a note." message
> fix: ~bank_withdraw_request fix

- data/src/scripts/levelup/scripts/levelup_unlocks_smithing.rs2
- Steel Med Helms are defined for Smithing level 33 reward.
> fix: levelup reward message for smithing level 48 steel platebodies

- data/src/scripts/_test/scripts/cheats/cheat_tele.rs2
- data/src/scripts/areas/area_wilderness/scripts/king_black_dragon.rs2
- data/src/scripts/npc/scripts/dragon.rs2
- data/src/scripts/player/scripts/damage.rs2
- data/src/scripts/quests/quest_dragon/scripts/elvarg.rs2
- data/src/scripts/skill_combat/scripts/npc/npc_combat.rs2
- data/src/scripts/skill_combat/scripts/poison.rs2
- data/src/scripts/tutorial/scripts/locs/tut_organ.rs2
- fix: change ~npc_default_retaliate_ap proc so the npc will only setmode to opplayer2 if its not currently ap'ing
- feat: 50% chance for dragons to headbutt you during op
- feat: video of elvarg ap found
- fix: random(1)'s replaced with random(2)'s
> fix: dragon headbutt, elvarg ap, and ap retal fix

- package-lock.json
- package.json
- src/lostcity/entity/PathingEntity.ts
- src/lostcity/entity/Position.ts
- Update rsmod dependency which no longer exposes `intersects` function.
- Simplify `inOperableDistance` and `inApproachDistance`.
> chore: update rsmod dependency

- .env.example
- src/lostcity/tools/packconfig/PackShared.ts
- src/lostcity/util/Environment.ts
- Use new environment property `SKIP_CRC` to skip packing crc checks or not.
- `true` enables the skip. 
- It is `false` by default.
> feat: new environment property SKIP_CRC for skipping crc packing checks

- package.json
Currently it tries to run the tests twice (`src/` and `out/`)
> ci: target `/src` with `test` script

- data/src/scripts/levelup/scripts/levelup_unlocks_cooking.rs2
- Removed the `brews` since that was part of Farming update.
> fix: some cooking levelup reward messages

- src/lostcity/entity/PathingEntity.ts
- Change the condition so it iterates less.
- Safe guard by manually counting the waypoint index instead of relying on the input.
> feat: queue waypoints improvement

- data/src/scripts/areas/area_mage_arena/configs/mage_arena.npc
- data/src/scripts/areas/area_mage_arena/scripts/battle_mage.rs2
- data/src/scripts/areas/area_mage_arena/scripts/gundai.rs2
- data/src/scripts/areas/area_mage_arena/scripts/lundail.rs2
- data/src/scripts/player/configs/multiway.dbrow
- data/src/scripts/skill_combat/scripts/npc/npc_combat_magic.rs2
- data/src/scripts/skill_combat/scripts/player/player_combat.rs2
- data/src/scripts/skill_combat/scripts/player/spells/scripts/flames_of_zamorak.rs2
- makes the arena bank multi
- adds dialogue to gundai and lundail
- fixes issue with flames of zamorak spell
- fixes npc magic, not checking if spotanim is null before using
- moves mage arena + battle mage check from `[opnpc2,_]` to `[opnpc2,_battle_mage]`
> fix(content): various mage arena fixes

- data/src/scripts/skill_combat/scripts/player/player_melee.rs2
`oc_param` fails when `$weapon` is `null`
> fix(content): poison check when not wearing a weapon for player melee combat

- data/src/scripts/quests/quest_legends/configs/quest_legends.obj
- data/src/scripts/skill_combat/scripts/player/player_ranged.rs2
- adds spotanim's to holy water
- throwing holy water drops glass
- arrows show up sooner on the ground
> fix(content): holy water missing proj_launch and proj_travel params

- data/src/scripts/_test/scripts/engine/debug_addobj.rs2
- src/lostcity/entity/NetworkPlayer.ts
- src/lostcity/entity/Player.ts
- op/ap interactions now automatically path to the target same as the packet decoding versions.
- no longer continue walking if the target is no longer in the world
> fix(engine): auto path to op/ap interactions

- data/src/scripts/_unpack/all.varp
https://runescape.wiki/w/Update:Game_Improvements
`We've also rejigged the combat selection so now you'll stick to the same fighting style after you log out. This means that when you log in again, you'll automatically use your preferred style - no more defending yourself by hitting someone over the head with a staff when you have plenty of runes!`
> fix(content): no longer remember attackstyles after logout

- data/src/scripts/quests/quest_ball/scripts/witches_experiement.rs2
- src/lostcity/engine/World.ts
Basically npc update uses `nid` which gets reused if an npc is deleted then a new npc is added on the same tick which results in that npc using the same `nid` as the one which was deleted which causes issues.
> fix(engine): cheapfix deleting and adding dynamic npcs on the same tick

- src/lostcity/engine/World.ts
- If no ids are available then an `Error` is thrown from EntityList.
- Npcs automatically handled since it's wrapped by script handling.
- Players need this logic for the full world response.
> fix(engine): next available pid not accounting for error for full world response

- data/src/scripts/macro events/scripts/general/macro_event_drunken_dwarf.rs2
- data/src/scripts/macro events/scripts/general/macro_event_genie.rs2
- data/src/scripts/macro events/scripts/general/macro_event_mysterious_old_man.rs2
- data/src/scripts/macro events/scripts/general/macro_event_triffid.rs2
- data/src/scripts/macro events/scripts/macro_events.rs2
In osrs, after receiving a reward from a random event and your inventory is full, it is dropped on the ground for 3h. This was supposedly added in osrs in ~2018.
> revert(content): macro_event reward lasting 3 hours on ground

- data/src/scripts/minigames/game_partyroom/scripts/partyroom_chest.rs2
https://youtu.be/Ve5UF8B3BMw?t=194
> fix(content): wrong message when partyroomoffer is full

- data/src/scripts/areas/area_alkharid/scripts/border_gate.rs2
- data/src/scripts/skill_agility/scripts/agility.rs2
- src/lostcity/engine/script/ScriptIterators.ts
- src/lostcity/engine/script/ScriptState.ts
- src/lostcity/engine/script/handlers/NpcOps.ts
- src/lostcity/engine/script/handlers/ObjOps.ts
- src/lostcity/engine/script/handlers/PlayerOps.ts
- src/lostcity/engine/script/handlers/ServerOps.ts
- src/lostcity/entity/Npc.ts
- src/lostcity/entity/PathingEntity.ts
- src/lostcity/entity/Player.ts
- src/lostcity/network/225/incoming/handler/MoveClickHandler.ts
- src/lostcity/network/225/incoming/handler/OpLocHandler.ts
- src/lostcity/network/225/incoming/handler/OpLocTHandler.ts
- src/lostcity/network/225/incoming/handler/OpLocUHandler.ts
- src/lostcity/network/225/incoming/handler/OpNpcHandler.ts
- src/lostcity/network/225/incoming/handler/OpNpcTHandler.ts
- src/lostcity/network/225/incoming/handler/OpNpcUHandler.ts
- src/lostcity/network/225/incoming/handler/OpObjHandler.ts
- src/lostcity/network/225/incoming/handler/OpObjTHandler.ts
- src/lostcity/network/225/incoming/handler/OpObjUHandler.ts
- src/lostcity/network/225/incoming/handler/OpPlayerHandler.ts
- src/lostcity/network/225/incoming/handler/OpPlayerTHandler.ts
- src/lostcity/network/225/incoming/handler/OpPlayerUHandler.ts
- src/lostcity/tools/packconfig/HuntConfig.ts
- All of the `op` packets all do the same thing now.
- Npc `aimode` now operates similarly to the player version where it attempts to interact more than once.
- Consolidated similar parts of interacting code into `PathingEntity`.
- Npcs can now target and also hunt different types of targets.
- No more `FaceEntity` and `FaceCoord` every tick.
- `HuntConfig` now packs all of the possible `NpcModes`
> fix(engine): npc interacting attempts & refactor interaction code

- data/src/scripts/engine.rs2
- data/src/scripts/general_use/configs/tables.loc
- data/src/scripts/general_use/scripts/tables.rs2
- src/lostcity/engine/script/ScriptOpcode.ts
- src/lostcity/engine/script/handlers/LocConfigOps.ts
sometimes items would drop on the wrong square
- adds lc_width and lc_length commands
- removes ability to put items on picnic tables
> fix(content): fixed placing items on tables being broken

- src/lostcity/cache/DbRowType.ts
- src/lostcity/cache/DbTableType.ts
- src/lostcity/cache/FontType.ts
- src/lostcity/cache/MesanimType.ts
- src/lostcity/cache/StructType.ts
- src/lostcity/cache/VarNpcType.ts
- src/lostcity/cache/VarPlayerType.ts
- src/lostcity/cache/VarSharedType.ts
- src/lostcity/engine/script/ScriptValidators.ts
- src/lostcity/engine/script/handlers/CoreOps.ts
- src/lostcity/engine/script/handlers/DbOps.ts
- src/lostcity/engine/script/handlers/EnumOps.ts
- src/lostcity/engine/script/handlers/InvOps.ts
- src/lostcity/engine/script/handlers/LocConfigOps.ts
- src/lostcity/engine/script/handlers/LocOps.ts
- src/lostcity/engine/script/handlers/NpcConfigOps.ts
- src/lostcity/engine/script/handlers/NpcOps.ts
- src/lostcity/engine/script/handlers/ObjConfigOps.ts
- src/lostcity/engine/script/handlers/ObjOps.ts
- src/lostcity/engine/script/handlers/PlayerOps.ts
- src/lostcity/engine/script/handlers/ServerOps.ts
- src/lostcity/entity/Position.ts
- Adds a new type `export type Position = {level: number, x: number, z: number};` 
- The ScriptValidators now return the specific types they are checking
- Removes a bunch of redundant code throughout the script handlers.
- Adds few additional checks like for vars or mesanims.
From:
```ts
[ScriptOpcode.LC_CATEGORY]: state => {
const locId = check(state.popInt(), LocTypeValid);
const locType = LocType.get(locId);
state.pushInt(locType.category);
},
```
To:
```ts
[ScriptOpcode.LC_CATEGORY]: state => {
state.pushInt(check(state.popInt(), LocTypeValid).category);
},
```
> refactor(engine): cleanup script validators and handlers

- src/lostcity/engine/GameMap.ts
- src/lostcity/engine/World.ts
- src/lostcity/engine/collision/CollisionManager.ts
- src/lostcity/engine/script/ScriptValidators.ts
- src/lostcity/engine/script/handlers/InvOps.ts
- src/lostcity/engine/script/handlers/LocOps.ts
- src/lostcity/engine/script/handlers/NpcOps.ts
- src/lostcity/engine/script/handlers/ObjOps.ts
- src/lostcity/engine/script/handlers/PlayerOps.ts
- src/lostcity/entity/Entity.ts
- src/lostcity/entity/EntityLifeCycle.ts
- src/lostcity/entity/HitType.ts
- src/lostcity/entity/Loc.ts
- src/lostcity/entity/Npc.ts
- src/lostcity/entity/NpcStat.ts
- src/lostcity/entity/Obj.ts
- src/lostcity/entity/PathingEntity.ts
- src/lostcity/entity/Player.ts
- src/lostcity/entity/PlayerLoading.ts
- src/lostcity/entity/PlayerStat.ts
- src/lostcity/network/225/incoming/handler/ClientCheatHandler.ts
- src/lostcity/tools/server/drops.ts
- Creates a `PlayerStat`, `NpcStat` and `HitType` enums for script validators. The stats are redundant.
- `EntityLifeCycle` default exports.
- Set the Player and Npc masks as readonly and add `static readonly BIG_UPDATE = 0x80;` for a player mask.
> refactor(engine): additional enum types for some script validators

- data/src/scripts/ladders+stairs/scripts/stairs.rs2
- Adds missing `p_arrivedelay`
- Adds an unhandled stairs found earlier.
> fix(content): varrock castle stairs

- src/lostcity/entity/Player.ts
- src/lostcity/maintenance.ts
- Varp like `-2147483748` is being written as a `varp_small`.
> fix(engine): writing large varps as small

- data/src/scripts/quests/quest_demon/scripts/delrith.rs2
Check by distance instead, allows you to kill it outside of the stonehenge circle. Not sure if this is correct but since there are no instances it would otherwise be unattackable outside of it. Alternatively it may have given a message but I don't know. That would be weird though as you'd have to wait for him to randomly walk back to the center before being able to fight again (changing wanderrange to 1 still causes it to walk too far both sides)
> fix(content): delrith being unattackable outside of 2 zones

- src/lostcity/web.ts
This was removed with fastify in https://github.com/2004Scape/Server/commit/0ca570e0da87793753c21f6b1e4db220fa4128ae
> fix(engine): allow cors again for separate localhost webclients

- data/src/scripts/_unpack/all.npc
- data/src/scripts/areas/area_gnome/configs/gnome.npc
- data/src/scripts/areas/area_varrock/configs/varrock.npc
- data/src/scripts/macro events/configs/antimacro.npc
The npc listed below no longer appear on the f2p server.
gertrude, gertrude's cat
philop, shilop, cinnamon, Wilough
Crate (kitten crate)
--
and Soldier's defend animation fixed. my own mistake when I had accidentally marked it //.
> small updates some members npc check + fixed 1 animation

- src/jagex2/io/Packet.ts
- src/lostcity/engine/World.ts
- src/lostcity/entity/BuildArea.ts
- src/lostcity/entity/NetworkPlayer.ts
- src/lostcity/entity/Player.ts
- src/lostcity/network/225/outgoing/codec/DataLandEncoder.ts
- src/lostcity/network/225/outgoing/codec/DataLocEncoder.ts
- src/lostcity/network/225/outgoing/codec/IfSetTextEncoder.ts
- src/lostcity/network/225/outgoing/codec/MessageGameEncoder.ts
- src/lostcity/network/225/outgoing/codec/MessagePrivateEncoder.ts
- src/lostcity/network/225/outgoing/codec/MidiJingleEncoder.ts
- src/lostcity/network/225/outgoing/codec/MidiSongEncoder.ts
- src/lostcity/network/225/outgoing/codec/NpcInfoEncoder.ts
- src/lostcity/network/225/outgoing/codec/PlayerInfoEncoder.ts
- src/lostcity/network/225/outgoing/codec/RebuildNormalEncoder.ts
- src/lostcity/network/225/outgoing/codec/UpdateIgnoreListEncoder.ts
- src/lostcity/network/225/outgoing/codec/UpdateInvFullEncoder.ts
- src/lostcity/network/225/outgoing/codec/UpdateInvPartialEncoder.ts
- src/lostcity/network/225/outgoing/codec/UpdateZonePartialEnclosedEncoder.ts
- src/lostcity/network/outgoing/codec/MessageEncoder.ts
- src/lostcity/network/outgoing/model/NpcInfo.ts
- src/lostcity/network/outgoing/model/PlayerInfo.ts
- src/lostcity/server/ClientSocket.ts
- src/lostcity/server/NullClientSocket.ts
- Writing packets no longer does array slicing.
- `pdata` and `gdata` no longer does array slicing.
- Cache appearances to reduce overall data out.
- Variable sized packets are now calculated real-time (except for NpcInfo and PlayerInfo).
> refactor(engine): performance optimizations

- src/lostcity/engine/script/handlers/PlayerOps.ts
- src/lostcity/entity/Player.ts
- src/lostcity/network/225/outgoing/codec/PlayerInfoEncoder.ts
- Also allows `anim` command to accept `-1`.
- Updates anim priority to exactly like the client.
> fix(engine): appearances being masked but not sent

- data/src/scripts/quests/quest_demon/configs/demon.npc
- data/src/scripts/quests/quest_demon/scripts/delrith.rs2
The timer in npc config doesn't seem to trigger at all?
> fix(content): fix delrith timer attempt 2

- data/src/scripts/areas/area_lumbridge/scripts/duke_horacio.rs2
- data/src/scripts/areas/area_varrock/scripts/aubury.rs2
- data/src/scripts/areas/area_wizard_tower/scripts/sedridor.rs2
- data/src/scripts/general/configs/quest.constant
- data/src/scripts/quests/quest_runemysteries/configs/quest_runemysteries.constant
- fix quest stages during rune mysteries (6 instead of 5)
- fix some mistakes with and add some missing dialogue to the quest
> fix(content): fix staging and incorrect dialogue during runemysteries

- data/src/scripts/minigames/game_duelarena/scripts/duel_arena.rs2
- data/src/scripts/minigames/game_duelarena/scripts/rotten_tomato.rs2
- data/src/scripts/minigames/game_trawler/scripts/trawler_start.rs2
- data/src/scripts/skill_cooking/scripts/cooking_inv/scripts/gnome_cooking/cocktail_finish.rs2
- data/src/scripts/skill_cooking/scripts/cooking_inv/scripts/gnome_cooking/gnome_crunchies.rs2
- data/src/scripts/skill_herblore/scripts/herblore.rs2
- data/src/scripts/skill_herblore/scripts/identifying/identify.rs2
- fix: rotten tomato missing op trigger and spotanim
- fix: unnecessary protected access check for trawler_start queue
- fix: missing null checks for obj param during gnome cooking
- fix: removed druidic ritual check for identifying herbs (didnt exist early osrs)
> fix(content): misc changes

- Bundle.ts
- src/lostcity/cache/config/Component.ts
- src/lostcity/entity/PlayerLoading.ts
- src/lostcity/server/ClientSocket.ts
- src/lostcity/server/NullClientSocket.ts
- src/lostcity/server/TcpMaintenanceServer.ts
- src/lostcity/server/TcpServer.ts
- src/lostcity/server/WSMaintenanceServer.ts
- src/lostcity/server/WSServer.ts
- src/lostcity/server/WorkerServer.ts
Found better ways to deal with crypto problem, either add the missing global variables to Bundle.ts defines or just filter the single init_crypto() call. Not doing this makes the worker server just error like this one that I missed: https://github.com/2004Scape/Server/commit/9a16f0f30a735e3ba25064ecde2cb76ed168d00a caused the global.crypto error too as it's used in clientcheathandler which is used by both servers.
Set staffmodlevel even without save file so people without access to filesystem can still use mod commands on webworker server.
Fix some environment variables not being set to default by setting them to undefined.
Also swapped load and loadAsync in component as I intended to keep the sync versions at the top of file.
> fix(engine): simplify and fix crypto id + set staffmodlevel without save

- data/src/scripts/skill_combat/scripts/player/weapon_category.rs2
Video from 2005:
https://youtu.be/LSpyUVXa4LE?t=225
I believe early osrs worked this way. Osrs later made a change to remember attack styles per weapon.
> fix(content): remove resetting attack styles on weapon switch

- bundle.js
- src/lostcity/engine/Login.ts
- src/lostcity/engine/World.ts
- src/lostcity/server/CrcTable.ts
- src/lostcity/server/LoginThread.ts
The worker implementation is now just reduced to some async functions and typeof self checks that are needed 😄 
Note: sometimes it can send `loginThread.postMessage` before login thread has set onmessage in which case it will get stuck on login forever. It only seems to happen on bun bundles though, esbuild bundles load loginthread faster.
Not really a problem anyway as u can just await the gamemaps to load first which will fix the timing, but I might let the worker start on client load instead of login as well.
> fix: cleanup all dupe worker code

- data/src/scripts/_unpack/all.npc
- data/src/scripts/areas/area_ardougne_east/scripts/brother_omad.rs2
- data/src/scripts/areas/area_ardougne_west/configs/mourner.npc
- data/src/scripts/areas/area_gnome/scripts/gnomes.rs2
- data/src/scripts/general/scripts/quests.rs2
- data/src/scripts/music/scripts/move.rs2
- data/src/scripts/quests/quest_drunkmonk/scripts/quest_drunkmonk.rs2
- data/src/scripts/quests/quest_ikov/scripts/ikov_dungeon.rs2
- data/src/scripts/quests/quest_murder/scripts/sinclair_guard_dog.rs2
- data/src/scripts/skill_combat/scripts/npc/npc_combat.rs2
- data/src/scripts/skill_combat/scripts/player/player_melee.rs2
- src/lostcity/engine/script/handlers/PlayerOps.ts
change ikov move trigger to use a timer that starts/stops on mapzone enter/exit, not 1:1 (no p_teleport to prevent moving to middle of bridge at the start) so might need to be adjusted later
* more mourner stats
* prevent attacking combat camp ogres with melee
* change last_coord to use laststep values instead (since lastX/Z will update before timer runs)
* change drunkmonk ladder to operate on reg timer instead of softtimer
> fix(content): Change ikov move trigger to use mapzone, mourner and ogre fixes

- bundle.js
- src/jagex2/io/Packet.ts
- src/lostcity/engine/GameMap.ts
- src/lostcity/server/ClientSocket.ts
- src/lostcity/server/WorkerServer.ts
- src/lostcity/worker.ts
These changes are for webrtc which is all client sided, and it works by having webrtc send and receive worker messages.
1. move uniqueId generation for workerserver to client, which means randomUUID has to be in the constructor
2. allow starting server on client load by sending `connection` message from client on login
3. map for connections, close logged off clientsockets, simplify ClientSocket
4. change bundles output dir to /public instead of /src/public to be ignored by terser in client2
5. fixed server hanging on load if you try to login before it's ready.
6. copy wasm files while bundling to avoid adding them to client, also copy packs+pem automatically too
7. Fixed issue where connected peers never logout if they X out of tab, sends close message on client unload.
More info and …
> feat(engine): multiple webworker connections support

- data/src/scripts/levelup/scripts/levelup_unlocks_fishing.rs2
> fix: fishing unlocks at 79 and 81 for trawler fish

- src/lostcity/entity/Player.ts
> fix(engine): do not allow repathing if player has no target or cant access

- data/src/scripts/levelup/scripts/levelup_unlocks_cooking.rs2
- data/src/scripts/levelup/scripts/levelup_unlocks_crafting.rs2
- data/src/scripts/levelup/scripts/levelup_unlocks_magic.rs2
- data/src/scripts/levelup/scripts/levelup_unlocks_prayer.rs2
- (cooking): fix typo and remove churning message
- (crafting): change level 72 message to say members
- (magic): replace messages and some spell names, fix typo
- (prayer): replace messages to match old screenshots
> fix(content): authentic lvl up reward messages

- data/src/scripts/tutorial/scripts/skills/tut_bury_bone.rs2
- Minor fix to use proper queue inside tutorial for burying bones, previously was able to level prayer past 3 during tutorial.
> fix(content): use correct bury bone queue for tutorial

- src/lostcity/engine/World.ts
- src/lostcity/engine/zone/Zone.ts
- src/lostcity/entity/Obj.ts
- Objs always reveal 100 ticks after first being added to the zone.
- `change obj` will increase the despawn timer until the obj is revealed.
==>
Reveal = 100 ticks
Obj Duration = 200 ticks
--
Obj dropped on floor.
Change obj after 50 ticks.
Obj reveals 50 ticks later (at tick 100)
Obj despawns 250 ticks later.
--
Obj dropped on floor.
Change obj after 25 ticks.
Obj reveals 75 ticks later (at tick 100)
Obj despawns 225 ticks later.
--
> fix(engine): changeobj not updating the obj despawn life cycle

- data/src/scripts/skill_combat/scripts/npc/npc_death.rs2
- data/src/scripts/skill_combat/scripts/player/player_combat.rs2
- Npc death will still allow the player to instantly attack another npc, after the npc's death anim
> fix(content): player able to logout immediately after npc dies during combat

- data/src/scripts/_unpack/all.obj
As far as I can tell the blue skirt has never offered any bonuses.
The best evidence I've found so far is a runehq link from 2005 which specifically mentions: "No stat effects; this is just to match the rest of your clothing."
- https://web.archive.org/web/20051130235246/http://runehq.com/RHQItemView.php?id=1149
There are also no bonuses for the blue skirt in runescape classic, or even OSRS today. So I'm fairly confident that it's never had any.
> fix(content): Removed magic bonuses from blue skirt

- data/src/scripts/quests/quest_hunt/scripts/redbeard_frank.rs2
- data/src/scripts/skill_fishing/configs/fishing_movement.enum
- src/lostcity/network/225/incoming/handler/OpHeldUHandler.ts
- src/lostcity/network/225/incoming/handler/OpLocUHandler.ts
- src/lostcity/network/225/incoming/handler/OpNpcUHandler.ts
- src/lostcity/network/225/incoming/handler/OpObjUHandler.ts
- src/lostcity/network/225/incoming/handler/OpPlayerUHandler.ts
engine: 
- clearPendingAction & closeModal sooner when interacting with members entities in f2p
content:
- fishing spot in port sarim was inaccessible
- redbeard dialogue for giving the key used objbox, instead of objboxt
> fix(content): inaccessible fishing spot, mems entity interaction fix, and redbeard dialogue

- data/src/scripts/quests/quest_sheepherder/scripts/npcs/councillor_halgrive.rs2
- data/src/scripts/quests/quest_sheepherder/scripts/npcs/diseased_sheep.rs2
- data/src/scripts/skill_combat/scripts/npc/npc_combat.rs2
1. Fixed typos in Councillor Halgrive's dialogue
2. Removed the combat checks for dialogue so now it uses the default messaging.
3. Relocated the combat checks to Diseased Sheep so prodding is prevented under the correct circumstances
4. Fixed checking if the inventory had bones from sheep you've already prodded.
> fix(content): Sheep Herder quest fixes

- data/src/scripts/general/configs/quest.constant
- data/src/scripts/quests/quest_chompybird/configs/quest_chompybird.constant
- data/src/scripts/quests/quest_chompybird/scripts/bloated_toad.rs2
- data/src/scripts/quests/quest_chompybird/scripts/bugs.rs2
- data/src/scripts/quests/quest_chompybird/scripts/chompy_bird.rs2
- data/src/scripts/quests/quest_chompybird/scripts/fycie.rs2
- data/src/scripts/quests/quest_chompybird/scripts/quest_chompybird.rs2
- data/src/scripts/quests/quest_chompybird/scripts/rantz.rs2
- data/src/scripts/quests/quest_chompybird/scripts/raw_chompy.rs2
- data/src/scripts/quests/quest_fluffs/scripts/quest_fluffs.rs2
- data/src/scripts/skill_cooking/scripts/cooking_inv/scripts/gnome_cooking/cocktail_mixing.rs2
- data/src/scripts/skill_cooking/scripts/cooking_inv/scripts/gnome_cooking/gnome_battas.rs2
- data/src/scripts/skill_cooking/scripts/cooking_inv/scripts/pizza/pizza.rs2
- data/src/scripts/skill_cooking/scripts/cooking_inv/scripts/stew/stew.rs2
- refactoring the toad (spawn chompy)/(explode) system
- plucking chompy, showing Rantz
- getting flavours from Rantz and kids
- filling half-full bellows
- cooking chompy on spit roast
- handing seasoned chompy to Rantz
- quest completion
**all that's left now** is to have Rantz shoot the chompy  , and add combat logic for player vs chompy
> feat: quest_chompybird part 4

- src/lostcity/engine/script/handlers/NpcOps.ts
Not sure if this is authentic but it's required for chompybird and I don't see any other way to clear the hunt mode
> feat(engine): support `npc_sethuntmode(null)` to clear hunt mode

- data/src/scripts/skill_combat/scripts/player/player_ranged.rs2
This fixes an issue with incorrect attack speeds when switching between different attack styles of a ranged weapon.
> fix(content): Update combat varps before calculating action_delay with ranged weapons

- data/src/scripts/levelup/scripts/levelup_unlocks_cooking.rs2
I believe this will fix the text with `Tangled Toad Legs` not having a space before `create`
> fix(content): Text-space for lvl 40 Cooking unlock Tangled Toad Legs

- data/src/scripts/skill_combat/scripts/npc/npc_poison.rs2
> fix(content): Clear npc poison when damage drops below 1

- src/lostcity/entity/Npc.ts
This fixes an issue with `npc_changetype` setting an invalid `ai_timer` on the new NPC.
Example of the issue:
https://github.com/user-attachments/assets/bc301a86-4db1-4b62-ba8c-26eb29ca87f9
> fix(engine): Safer checks when applying NPC timer

- data/src/scripts/areas/area_ardougne_east/scripts/baker.rs2
- data/src/scripts/areas/area_ardougne_east/scripts/fur_trader.rs2
- data/src/scripts/areas/area_ardougne_east/scripts/gem_merchant.rs2
- data/src/scripts/areas/area_ardougne_east/scripts/silk_merchant.rs2
- data/src/scripts/areas/area_ardougne_east/scripts/silver_merchant.rs2
- data/src/scripts/areas/area_ardougne_east/scripts/spice_seller.rs2
- data/src/scripts/areas/area_ardougne_west/scripts/mourner.rs2
- data/src/scripts/areas/area_varrock/scripts/tea_seller.rs2
- data/src/scripts/quests/quest_fluffs/scripts/pet.rs2
- data/src/scripts/quests/quest_fluffs/scripts/quest_fluffs.rs2
- data/src/scripts/skill_thieving/configs/chests/trapped_chest.dbrow
- data/src/scripts/skill_thieving/configs/chests/trapped_chest.dbtable
- data/src/scripts/skill_thieving/scripts/chest/trapped_chest.rs2
- data/src/scripts/skill_thieving/scripts/thieving.rs2
- Blood-Rune chest now teleports you to Elena's house
- Shark chest now teleports you to Pillars of Zanash
- Steel Arrowtips chest now works as intended
- Fixed Mourner typo
- Removed option to Trade with merchants you've recently thieved from
TODO on chests: correct damage formula
> fix(content): thieving chest teleporting, implement locked chests, remove trading after recently theiving

- package.json
Allows for the implicit type guard in https://github.com/2004Scape/Server/blob/main/src/lostcity/server/FriendsServerRepository.ts#L101 to function correctly
@Pazaz I'm not sure how that PR (#817) passed CI / ran locally 🤔 I was able to get the error that @ultraviolet-jordan reported when I changed my IDE to use `5.4.5` explicitly. But I would have expected CI to fail and for the friends server not to run locally...
> chore(engine): typescript `5.5.4`

- src/lostcity/engine/GameMap.ts
- src/lostcity/engine/Login.ts
- src/lostcity/engine/World.ts
- src/lostcity/engine/script/ScriptIterators.ts
- src/lostcity/engine/script/handlers/LocOps.ts
- src/lostcity/engine/script/handlers/ObjOps.ts
- src/lostcity/engine/script/handlers/ServerOps.ts
- src/lostcity/engine/zone/Zone.ts
- src/lostcity/entity/BuildArea.ts
- src/lostcity/entity/NetworkPlayer.ts
- src/lostcity/entity/Npc.ts
- src/lostcity/entity/PathingEntity.ts
- The fix is the `bordersFreeToPlay` function to check if a members loc borders a free zone, then we do not want to unload it.
- Did refactor `GameMap` and `World` to put `ZoneMap` inside of `GameMap`.
> fix(engine): unable to interact with bordering members locs on free world

- data/src/scripts/skill_combat/scripts/npc/npc_death.rs2
- data/src/scripts/skill_combat/scripts/player/player_magic.rs2
- src/lostcity/engine/script/handlers/NpcOps.ts
reduces 2nd npc_delay in npc_death to match:
- https://youtu.be/Vsnkdq8OOMg?t=209
- https://youtu.be/mrqmLFGEsOE?t=69
- https://youtu.be/fZGgcIlfoeI?t=33
- https://youtu.be/TiJ7bmcXVK0?t=33
- https://youtu.be/OHx58MJ2itw?t=338
- https://youtu.be/aJDlEmyPpk8?t=140
- https://youtu.be/QCUMECkwUb0?t=103
Magic was also always speeding up death (due to auto retal queue being later in the script)
> fix(engine): npc_arrivedelay delaying 0-2 ticks 

- data/src/scripts/quests/quest_itgronigen/scripts/quest_itgronigen.rs2
current randomization doesn't account for interface offset and includes 0 which is invalid
> fix(content): fix constellation randomization (observatory quest)

- data/src/scripts/quests/quest_arena/configs/quest_arena.npc
- data/src/scripts/quests/quest_upass/scripts/koftik.rs2
- Define maxranges for khazard minions so they will hunt the player through the whole arena
- Linebreaks for Koftik based off old images
> fix(content): khazard minions maxranges, koftik dialogue changes:

- data/src/scripts/areas/area_varrock/scripts/kanel.rs2
- data/src/scripts/areas/area_varrock/scripts/philop.rs2
- data/src/scripts/quests/quest_fluffs/scripts/pet.rs2
- data/src/scripts/tutorial/scripts/guides/combat_instructor.rs2
- data/src/scripts/tutorial/scripts/guides/financial_advisor.rs2
- data/src/scripts/tutorial/scripts/guides/master_chef.rs2
- data/src/scripts/tutorial/scripts/guides/mining_instructor.rs2
- data/src/scripts/tutorial/scripts/guides/survival_guide.rs2
- data/src/scripts/tutorial/scripts/tut_chatbox_steps.rs2
- data/src/scripts/tutorial/scripts/tut_doors_and_gates.rs2
Tutorial Island dialogue:
- fixed some typos and missing punctuations
- added missing recap trigger for mining instructor
- changed some instances of "Runescape" -> "RuneScape"
+slight tweaking to cat code, removed 2 wrong comments
> fix(content): tutorial island typos

- package.json
ts 5.6 introduced some new iterator subtypes which the EntityList code is not compatible with
https://devblogs.microsoft.com/typescript/announcing-typescript-5-6/#what%E2%80%99s-new-since-the-beta-and-rc
> chore(engine): pin typescript version to 5.5.4

- src/lostcity/util/Environment.ts
credit to @williamistGitHub for this one, I just pulled it out of #875 so it can be merged sooner
> fix(engine): no longer load login port as friends port

- src/lostcity/engine/script/handlers/NpcOps.ts
Note that hill giants had a shorter death delay back then. The arrivedelay should be the same though
https://github.com/user-attachments/assets/e18e0abe-bc87-40d5-b401-85b1a19d2a98
https://github.com/user-attachments/assets/b76b827e-6430-4cf1-a287-bc7738f42bea
https://github.com/user-attachments/assets/ca21537c-57ee-48c4-a315-3a2ab4e8b82c
https://github.com/user-attachments/assets/3aeaadb9-901a-4d28-99c2-a26811189a47
> fix(engine): revert npc_arrivedelay to old timings

- src/lostcity/engine/script/handlers/PlayerOps.ts
- src/lostcity/entity/Player.ts
Only updateMovement if first interaction failed, or aprange called to match:
https://github.com/user-attachments/assets/3a4b9182-7eb7-4330-bd22-590a12d7beba
https://github.com/user-attachments/assets/1b1f705a-09fd-4b88-8212-1366cf4523ca
> fix(engine): p_walk should move the player when movement is processed

- data/src/scripts/_test/scripts/cheats/cheat_interactions.rs2
- data/src/scripts/engine.rs2
- data/src/scripts/macro events/configs/antimacro.npc
- data/src/scripts/skill_firemaking/scripts/firemaking.rs2
- src/lostcity/entity/Npc.ts
- src/lostcity/entity/PathingEntity.ts
- src/lostcity/entity/Player.ts
- src/lostcity/network/225/incoming/handler/MoveClickHandler.ts
- src/lostcity/network/225/incoming/handler/OpHeldTHandler.ts
- src/lostcity/network/225/incoming/handler/OpHeldUHandler.ts
- src/lostcity/network/225/incoming/handler/OpLocHandler.ts
- src/lostcity/network/225/incoming/handler/OpLocTHandler.ts
- src/lostcity/network/225/incoming/handler/OpLocUHandler.ts
- src/lostcity/network/225/incoming/handler/OpNpcHandler.ts
- src/lostcity/network/225/incoming/handler/OpNpcTHandler.ts
- src/lostcity/network/225/incoming/handler/OpNpcUHandler.ts
- src/lostcity/network/225/incoming/handler/OpObjHandler.ts
- src/lostcity/network/225/incoming/handler/OpObjTHandler.ts
- src/lostcity/network/225/incoming/handler/OpObjUHandler.ts
- src/lostcity/network/225/incoming/handler/OpPlayerHandler.ts
- src/lostcity/network/225/incoming/handler/OpPlayerTHandler.ts
- src/lostcity/network/225/incoming/handler/OpPlayerUHandler.ts
Engine:
- extra check to decrement waypoint if player is standing on waypoint tile in . Currently our waypoints only decrement on a change of direction during the players path. P_teleports can cause this change of direction calculation to change, as p_teleport can change the player's x and z before movement is processed. So an additional check is necessary
- clearWaypoints *before* executing the script in `processInteractions()`, unless aprange is called. If a p_op command is called within the aptrigger, clearWaypoints after executing the script (Not entirely sure if this is how it should be implemented, but thats how the old code handled p_op commands in aptriggers)
- clearWaypoints *before* executing the script for npc's in `aiMode()`
- still queueWaypoint to current tile if current …
> fix(engine): engine tweaks to match osrs firemaking edgecases

- src/lostcity/engine/World.ts
- src/lostcity/engine/script/handlers/PlayerOps.ts
- src/lostcity/entity/Player.ts
https://github.com/user-attachments/assets/c35ce9fa-0847-4be5-8c2b-cfa385c2934c
https://github.com/user-attachments/assets/67000329-f10c-4079-a166-f860d93ca131
https://github.com/user-attachments/assets/7a42d51c-6142-46a9-b0c7-d9c00d69d1f7
> fix(engine): match osrs redx and yellowx mechanics

- src/lostcity/engine/World.ts
- src/lostcity/engine/zone/Zone.ts
- Set receiverid for all objs where applicable to prevent showing to other players
- Untradeable objs ground duration (with a receiver) will now match tradeable objs (3 minutes instead of 2)
> fix(engine): reveal on untradeable objs

- src/lostcity/engine/script/handlers/ServerOps.ts
fixes an issue where random events would often spawn on-top of the player
> fix(engine): prevent map_findsquare from prioritizing corners

- src/lostcity/entity/Npc.ts
https://github.com/user-attachments/assets/3a927def-0904-4363-ba73-22db88b1cc6a
https://github.com/user-attachments/assets/9e6e63c9-81e0-4e5e-b84b-e6267bf885f6
This used to clearWaypoints, which inadvertently stopped their movement entirely
https://github.com/user-attachments/assets/e3b86169-03bd-4a27-baf0-7fd6af83425f
Previous 'fix' was to clearWaypoints, which again inadvertently stopped their movement entirely
https://github.com/user-attachments/assets/67e9013f-f663-4055-8fdf-039a662cc927
> fix(engine): prevent npc pathing to target if target is outside maxrange

- data/src/pack/varp.pack
- data/src/scripts/_unpack/all.varp
- data/src/scripts/player/scripts/drop.rs2
- data/src/scripts/quests/quest_mcannon/scripts/cannon.rs2
- data/src/scripts/skill_combat/scripts/player/auto_retaliate.rs2
- data/src/scripts/skill_combat/scripts/pvp/pvp_magic.rs2
- src/lostcity/engine/script/handlers/PlayerOps.ts
- fix: stop animations when dropping items to match early osrs.  https://youtu.be/QvDYolBZNjY?t=164, https://youtu.be/DVHCP2JhQE0?t=142
- fix: load cannonballs mes to never singularize 
- fix: remove npc attackable check from player retaliation, and check if the op exists in the p_op commands. If the npc does have an op2, when it runs there will already an npc attackable check in there. %action_delay is still set in this clip, causing me to firemake in 2 ticks:
https://github.com/user-attachments/assets/0d92f2d0-d46b-470b-a2a8-ab8b983eaac9
- fix: 10 tile check for pvp freezes to match: https://youtu.be/SC4KF1JWVl8&t=76. This is how it works in osrs currently, theres no indication in any blog posts that this was added post rs2 release
- fix: inv space check for the cannon is placed earlier …
> fix(content): misc fixes

- src/lostcity/entity/Player.ts
- src/lostcity/network/225/incoming/handler/MoveClickHandler.ts
- fix: prevent running on ctrl-click if op click, to match this [blog post](https://oldschool.runescape.wiki/w/Update:Wilderness_Feedback_Update) from 2014 osrs `Holding CTRL to run now functions correctly when clicking on an object or NPC.` (This is actually still the case for opu clicks in osrs!)
- fix: turn off run when below 100 run energy, only if ctrl-clicked, in move click handler
- fix: turn off run when below 100 run energy, if ctrl-clicked in movement process
I run for 2 ticks. Old implementation I'd run for 1 tick
Osrs:
https://github.com/user-attachments/assets/4715a666-0b24-40bd-9e82-78e814eb11a2
2004 with fixes:
https://github.com/user-attachments/assets/58faf95b-7d77-466c-a4a7-5d2a215476e2
I run for 1 tick, never reaching 0 run energy.
Osrs: …
> fix(engine): ctrl-click to run inaccuracies 

- data/src/scripts/areas/area_wilderness/configs/wilderness_levels.constant
- data/src/scripts/areas/area_wilderness/scripts/wilderness_warning.rs2
- src/lostcity/engine/script/handlers/PlayerOps.ts
- src/lostcity/entity/PathingEntity.ts
- src/lostcity/entity/Player.ts
also refactors wildy warning code to only show wildy warning when you pass the "wilderness line"
> fix(engine): last_coord command to use last changed coord instead of last step

- src/lostcity/engine/World.ts
- src/lostcity/entity/PathingEntity.ts
https://github.com/user-attachments/assets/fd925b05-fa2b-4876-bdeb-a31199b90f1c
https://github.com/user-attachments/assets/d1b778f4-d516-40e3-86b9-8ebfb0d87340
https://github.com/user-attachments/assets/ef240abe-92c1-4971-bcd8-d81bbf92edf3
https://github.com/user-attachments/assets/877227a6-9228-44a1-aad0-04af8b76bf24
> fix(engine): following took an extra tick if right next to target

- src/lostcity/cache/config/LocType.ts
- src/lostcity/cache/config/NpcType.ts
Interactions are checking and ignoring == null... so we need them to be valid on the server
> fix(engine): Keep 'hidden' ops loaded in memory

- data/src/scripts/quests/quest_mcannon/scripts/cannon.rs2
Updates the cannonball projectile length and step to match osrs.
Current args:
https://github.com/user-attachments/assets/8d6c6775-9671-4b8d-ae8d-2ccc00d84f5a
Modified args:
https://github.com/user-attachments/assets/9a671880-5686-4077-9bf6-d4b05e411f77
I do not have a rsprox log to back it up but i have some old notes from back 2017 where i logged a bunch of osrs projectiles:
```
{gfxId=53, sourceX=6976, sourceY=7360, targetX=6848, targetY=7488, startHeight=144, endHeight=140, delay=0, duration=30, slope=2, centerOffset=11}
{gfxId=53, sourceX=5952, sourceY=6080, targetX=5696, targetY=5952, startHeight=144, endHeight=140, delay=0, duration=35, slope=2, centerOffset=11}
{gfxId=53, sourceX=5952, sourceY=6080, targetX=5568, targetY=5952, startHeight=144, endHeight=140, delay=0, duration=40, …
```
> fix(content): tweak mcannon projectile parameters

- data/src/scripts/skill_combat/configs/ranged/bolts.obj
Per discussion in discord sources channel (username is teagan) revised non-standard crossbow bolts to give a +18/+9 each tier /half-tier, as there is some indirect evidence that this schema pre-dates the crossbow rework in 2006. Consolidated comments to one longer comment, which explains the change.
> fix: Revised non-standard crossbow bolt ranged strength bonus

- data/src/scripts/areas/area_wilderness/scripts/king_black_dragon.rs2
Kbd can be safespotted, but can also attack from a distance. The theory goes that he attacks once from a distance and then tries to move towards you.
> fix(content): allow kbd safespotting

- data/src/scripts/skill_thieving/configs/doors/locked_door.dbrow
- data/src/scripts/skill_thieving/configs/doors/locked_door.dbtable
- data/src/scripts/skill_thieving/scripts/doors/locked_door.rs2
A few doors have the locked side as the inverse of the entering side:
door 1 - pirate hut wildy (pos 3045, 3956)
door 2 - yanille dungeon (pos 2601, 9481)
> fix(content): inverted locked doors

- data/src/scripts/skill_magic/scripts/spells/charge.rs2
https://youtu.be/CqzZ_Qsw7RE this video shows charge had no cooldown. This video shows him packeting, which is why the charges are 'queued' up
> fix(content): remove cooldown on charge spell

- .devcontainer/devcontainer.json
Because `/bin/sh/` is not really pleasant to work with.
> chore: set devcontainer default shell to /bin/bash

- src/lostcity/engine/World.ts
- src/lostcity/entity/BuildArea.ts
- src/lostcity/network/225/outgoing/codec/NpcInfoEncoder.ts
- src/lostcity/network/225/outgoing/codec/PlayerInfoEncoder.ts
The screenshots show `less dense vs more dense` before & after examples on my pc.
I did not do this for npcs because it seemed too slow for 5000 npcs, and it definitely won't scale well when there are more in the world in the future.
> feat(engine): create a player grid to improve player_info performance

- data/src/scripts/login_logout/logout.rs2
- data/src/scripts/minigames/game_duelarena/scripts/duel_arena.rs2
- data/src/scripts/minigames/game_duelarena/scripts/duel_arena_finish.rs2
- data/src/scripts/minigames/game_duelarena/scripts/duel_arena_start.rs2
- duel time limit from this [blog](https://runescape.wiki/w/Update:Assist_System). `The time-out in the Duel Arena has been reduced to 30 minutes from the previous 60 minutes.`
- duel time out from opponent disconnecting from this [video](https://youtu.be/LZzhIWbSKpY?t=126).
- In the video above, the opponent logs out after not being attacked for 17 ticks. This means the duel arena check is only in the logout if_button. Same goes with gnomeball, current osrs you can afk log within gnomeball
- also applies the ~inv_remove_leading_empty_slots proc from trading to duel stakes
> fix(content): duel time limit, duel time out, and logout trigger changes 

- src/lostcity/engine/World.ts
- src/lostcity/entity/EntityList.ts
`scaleByPlayerCount` was created which calls into `getTotalPlayers` to get the current number of players in the `World`. The way `getTotalPlayers` is implemented is by manually counting the slots every time:
```ts
get count(): number {
let count: number = 0;
for (const _ of this[Symbol.iterator]()) {
count++;
}
return count;
}
```
which the `[Symbol.iterator]` is a loop itself:
```ts
*[Symbol.iterator](): ArrayIterator<T> {
for (const index of this.ids) {
if (index === -1) {
continue;
}
const entity: T | undefined = this[index];
if (typeof entity === 'undefined') {
continue;
}
yield entity;
}
}
```
Since `scaleByPlayerCount` fn in `World` is used by `removeNpc` and `removeObj`, it is performing a double loop every time an npc or obj is removed from the world.
Refactor the `count` fn as …
> feat(engine): entitylist count performance for scalebyplayercount fn

- data/src/scripts/skill_magic/scripts/spells/superheat.rs2
- data/src/scripts/skill_smithing/configs/smelting/smelting.struct
- Ensure both primary and secondary ore are present, fixing bug where bronze bars could be superheated with only tin ore
- Add OSRS failure message if both copper and tin not present ![image](https://github.com/user-attachments/assets/f6d95a79-0042-45b8-9f10-6caa3e23210c)
> fix(content): bronze bar superheating

- src/lostcity/entity/PathingEntity.ts
Fixes https://github.com/2004Scape/Server/issues/982
Thanks to https://github.com/2004Scape/Server/issues/982#issuecomment-2455896662
However a new issue arises:
https://github.com/user-attachments/assets/9ce12f1c-50e3-40b9-84bf-1f9d4ed4baef
In order to fix this I added the same work around to pathToMoveClick():
https://github.com/tannerdino/Server/blob/72cbca79c438eb37097d9cf6fe0037247a90604e/src/lostcity/entity/PathingEntity.ts#L403-L408
> fix(engine): players now naive path if target is ontop of them

- src/lostcity/engine/World.ts
Moving it to the appropriate spot since it was written before I wrote the `npc.nid = -1;` & `npc.uid = -1;`.
> fix(engine): npc renderer to remove permanent nids properly

- data/src/scripts/quests/quest_crest/configs/quest_crest.npc
- data/src/scripts/quests/quest_crest/scripts/crest_chronozon.rs2
- Add 2.5% combat xp scaling for Chronozon
- Changed death/regen behaviour:
- If you've cast all the spells (or have done the quest before) Chronozon will die, and if you did the most damage and are on the right quest stage it'll drop the crest piece
- If you've cast all the spells but didn't do the most damage, it'll die with no drop for anyone
- If you haven't cast all the spells, it regens with a message
- If it can't find the player attacking it, it regens silently
> fix(content): fix Chronozon death/regen behaviour if no hero found

- data/src/scripts/npc/configs/ai_spawn.varn
- data/src/scripts/npc/scripts/ai_spawn.rs2
- data/src/scripts/quests/quest_chompybird/scripts/chompy_bird.rs2
- data/src/scripts/skill_combat/scripts/player/player_magic.rs2
- data/src/scripts/skill_combat/scripts/player/player_melee.rs2
- data/src/scripts/skill_combat/scripts/player/player_ranged.rs2
- src/lostcity/engine/World.ts
- src/lostcity/engine/script/ServerTriggerType.ts
- src/lostcity/entity/Npc.ts
0 xp spawnhitting:
- [Video](https://youtu.be/yYRSpv2AGq4) by keyboardOSRS (patched)
- Ours with proposed fixes:
https://github.com/user-attachments/assets/2d02e84e-6037-4643-8da1-3399ae20d12c
- ash tweet:
Respawn is moved to processNpcs() because:
- Npc's with hunt rates of 1, will always hunt 1 tick after *visibly* respawning (which is a total of 2 ticks after being added to the world). If respawns were processed before hunts, npc's with hunt rates of 1 would hunt the same tick it *visibly* respawns
https://github.com/user-attachments/assets/3f365058-4640-4d29-91e1-7322dcb7b4ea
https://github.com/user-attachments/assets/7ab173c3-da5e-47d2-8a84-4f0c0714ab77
- ai_spawn scripts take a tick to process in early osrs. This is the mechanism, along with pvm bonus xp handled with a varn, that …
> feat(engine): ai_spawn triggers, 0 xp spawnhitting bug, and process order of npc hunt's

- src/lostcity/entity/Npc.ts
Osrs is 500 ticks + some change; it's not usually exactly 500 ticks. I think they probably only teleport on the 1/8 chance to wander. Last wander also resets on defaultMode, so you can keep an npc stuck by splashing and logging on an alt every few minutes. For these reasons we cannot reuse `lastMovement`.
Added `startLevel` just incase an npc gets teleported and trapped on a level different than their respawn.
https://github.com/user-attachments/assets/9acc0b19-e6b0-4ce8-bdc6-10061f0f9d80
> feat(engine): wandering npcs now teleport if stuck for 5 min

- src/lostcity/entity/PathingEntity.ts
fixes #997 
- 1x1 npc pathing (unchanged):
https://github.com/user-attachments/assets/cb41abcd-674b-4d80-8838-9c33558d1278
- big npc pathing:
https://github.com/user-attachments/assets/4da2c574-946b-453a-a095-2c20ae143574
- big npc pathing in zigzag pattern:
https://github.com/user-attachments/assets/e59adb91-0d3a-44ad-bfb5-532d5faefe38
- corner safespotting still exists
https://github.com/user-attachments/assets/765aa425-ce69-4ae5-bac4-8d6bfbb31aea
- npcs still dance whilst under target
https://github.com/user-attachments/assets/9aacafeb-8493-4fa2-a815-6fcdc7f36cd4
> feat(engine): pre-2006 big npc pathing

- data/src/scripts/quests/quest_chompybird/configs/quest_chompybird.npc
- data/src/scripts/quests/quest_chompybird/scripts/bugs.rs2
- data/src/scripts/quests/quest_chompybird/scripts/chompy_bird.rs2
- data/src/scripts/quests/quest_chompybird/scripts/fycie.rs2
- data/src/scripts/quests/quest_chompybird/scripts/rantz.rs2
- data/src/scripts/quests/quest_chompybird/scripts/raw_chompy.rs2
- data/src/scripts/skill_cooking/scripts/cooking_inv/scripts/gnome_cooking/cocktail_mixing.rs2
- data/src/scripts/skill_cooking/scripts/cooking_inv/scripts/gnome_cooking/gnome_battas.rs2
- data/src/scripts/skill_cooking/scripts/cooking_inv/scripts/pizza/pizza.rs2
- data/src/scripts/skill_cooking/scripts/cooking_inv/scripts/stew/stew.rs2
- Add missing dialogue for `chompybird_kids_play_with_toad` and `chompybird_removed_rock_from_chest` stages
- Restore chompy hunt range
- Fix issue where players had to spam click the chompy for arrows to fire
- Add spit animation, sounds, delay, and burn chance
- Add 30 cooking requirement for cooking chompy
- Add delay for Rantz hunting the chompy
- Fix ogre arrow spotanim height for humans
- Fix "Nothing interesting happens" when using raw chompy on secondary ingredients
- Fix inverted check if the player made the ogre arrows themselves
- Handle no inv space scenario when buying feathers/tools from Rantz's kids
> fix(content): Big Chompy Bird Hunting fixes

- src/lostcity/engine/Login.ts
- src/lostcity/engine/World.ts
- src/lostcity/server/LoginClient.ts
- src/lostcity/server/LoginThread.ts
- The current implementation is non-blocking so when `Login.logout` is called, it doesn't actually remove the player from the world. This happens sometime later from the worker thread.
- `Environment.NODE_DEBUG_PROFILE` was reporting the next game tick instead of this current game tick.
- Renamed `processMovementDirections` to `processInfo` to more accurately describe what that function does now.
> fix(engine): actually remove the player when they logout

- src/lostcity/engine/World.ts
- src/lostcity/prometheus.ts
Swap prometheus player/npc count metrics from histograms to gauges. These metrics do not track any sort of duration so they're not well suited to histograms as their values are somewhat constant. A gauge is a better metric because show a 'point in time' of the player/npc count.
> refactor(engine): swap npc/player count metrics to gauges

- data/src/scripts/areas/area_mage_arena/scripts/kolodion.rs2
- data/src/scripts/areas/area_mage_arena/scripts/lundail.rs2
- data/src/scripts/engine.rs2
https://youtu.be/mQmeH32PdNk?t=19
This dialogue confirms they are not using "Gielinor" in their dialogue, changed other usages of the word to "RuneScape" off an assumption it is the same.
Also NPC say texts were incorrect compared to the video
> fix(content): mage arena dialogues

- .env.example
- data/src/scripts/player/playerwalk.rs2
- data/src/scripts/quests/quest_mcannon/scripts/cannon.rs2
- src/lostcity/engine/World.ts
- src/lostcity/engine/script/handlers/PlayerOps.ts
- src/lostcity/entity/NetworkPlayer.ts
- src/lostcity/entity/Player.ts
- src/lostcity/network/225/incoming/handler/MoveClickHandler.ts
- src/lostcity/network/225/incoming/handler/OpHeldHandler.ts
- src/lostcity/network/225/incoming/handler/OpHeldTHandler.ts
- src/lostcity/network/225/incoming/handler/OpHeldUHandler.ts
- src/lostcity/network/225/incoming/handler/OpLocHandler.ts
- src/lostcity/network/225/incoming/handler/OpLocTHandler.ts
- src/lostcity/network/225/incoming/handler/OpLocUHandler.ts
- src/lostcity/network/225/incoming/handler/OpNpcHandler.ts
- src/lostcity/network/225/incoming/handler/OpNpcTHandler.ts
- src/lostcity/network/225/incoming/handler/OpNpcUHandler.ts
- src/lostcity/network/225/incoming/handler/OpObjHandler.ts
- src/lostcity/network/225/incoming/handler/OpObjTHandler.ts
- src/lostcity/network/225/incoming/handler/OpObjUHandler.ts
- src/lostcity/network/225/incoming/handler/OpPlayerHandler.ts
- src/lostcity/network/225/incoming/handler/OpPlayerTHandler.ts
- src/lostcity/network/225/incoming/handler/OpPlayerUHandler.ts
- src/lostcity/util/Environment.ts
- src/lostcity/util/WalkTriggerSetting.ts
- adds ~playerwalk3 proc
- adds NODE_... setting for where walktrigger is ran in the world cycle. 0 = processed in packet handler. 1 = processed in player setup (client input). 2 = processed in player movement. For setting 0, path is set in the packet handler. For settings 1 & 2, path is set in player setup.
- defaults both path to be set and walktrigger to be processed immediately in the packet handler. In the span of OSRS's lifetime, the location of where walktrigger was processed for yellowx was changed from: packet handler -> client input -> player movement. Videos: [May 4, 2013 OSRS](https://youtu.be/dKfFkEyqD8E?t=9) (before server pathing update), [Oct 17, 2016 OSRS](https://youtu.be/TnBJZD9AcJE) (after server pathing update)
- p_op and p_walk should not set moveClickRequest, and …
> fix(engine): walktrigger env settings and moveClickRequest changes

- src/lostcity/entity/Npc.ts
- reset spawn coords of the npc every tick it follows. No way to confirm this in osrs, but if a following npc switches to attack you, it could get stuck if you're far away from its spawn point. Example of this for us would be the dwarf random event
- also only teleports to player after movement is processed, the old code the following npc could tele and move same tick, which didnt match osrs tests
> fix(engine): reset spawn point for following npcs

- src/lostcity/engine/World.ts
- src/lostcity/engine/script/handlers/NpcOps.ts
- src/lostcity/engine/script/handlers/PlayerOps.ts
- src/lostcity/entity/HeroPoints.ts
- src/lostcity/entity/Npc.ts
- src/lostcity/entity/PathingEntity.ts
- src/lostcity/entity/Player.ts
- src/lostcity/entity/PlayerLoading.ts
- src/lostcity/network/225/incoming/handler/ChatSetModeHandler.ts
- Remove heropoints duplicate code by creating a class for it.
- Improve player chatmodes code.
- Some imports organizing.
> refactor(engine): create heropoints class & improve chatmodes

- data/src/scripts/areas/area_gnome/scripts/gnome_restaurant.rs2
- data/src/scripts/areas/area_white_wolf_mountain/scripts/mountain_dwarf.rs2
- data/src/scripts/levelup/configs/levelup_unlocks.enum
- data/src/scripts/levelup/scripts/levelup_unlocks_attack.rs2
- data/src/scripts/levelup/scripts/levelup_unlocks_fletching.rs2
- data/src/scripts/levelup/scripts/levelup_unlocks_herblore.rs2
- data/src/scripts/levelup/scripts/levelup_unlocks_magic.rs2
- data/src/scripts/levelup/scripts/levelup_unlocks_mining.rs2
- data/src/scripts/levelup/scripts/levelup_unlocks_smithing.rs2
- Fixed typos in mountain dwarf & gnome chef dialogue
- Added mining guild level up message
- Removed black punctuation from some level up messages
- Attack & Fletching had black punctuation entirely removed
- Other skills had blue punctuation added to specific messages with screenshots attached
> fix(content): typos, level up messages

- data/src/scripts/levelup/configs/levelup_unlocks.enum
- data/src/scripts/levelup/scripts/levelup_unlocks_cooking.rs2
- Removed message for cheese churning which wasn't added until October 24th, 2005
- Corrected level 65 unlock message, removing reference to wine of Zamorak fermenting which wasn't added until May 20th, 2013
- Removed a few unused levels from the .enum
Used this video as a reference for the new 65 unlock message: https://youtu.be/YayjtGk5JBg?t=112
> fix(content): Remove erroneous cooking unlock messages

- data/src/scripts/areas/area_edgeville/scripts/oziach.rs2
- data/src/scripts/quests/quest_dragon/configs/quest_dragon.constant
References:
- https://forum.tip.it/topic/75433-melzars-maze-not-an-option/ 
- https://forum.tip.it/topic/42769-melzars-maze-key/
While RSC Dragon Slayer had you trade other players or buy a new key from Legends Guild, with RS2, Maze key can not be traded - locking f2p out if key is lost.
This also seems to line up with known varp values for Dragon Slayer in OSRS (even though the quest was reworked in 2007): https://chisel.weirdgloop.org/varbs/display?varplayer=176
I ran a test on local server by setting dragon_progress varp to 1 and talking to Oziach, trying to do the drop trick. I found nothing obvious that had broken as result of this, but a review is appreciated in any case.
> fix(content): Oziach should give spare key to maze during quest if lost

- src/engine/entity/Player.ts
When you perform an `exactmove`, the server is updated properly to know what your new position is on the world, but the client is never actually updated. The only thing the client receives is that you performed an `exactmove` but not that you actually moved positions or anything (walk, run, teleport).
https://github.com/user-attachments/assets/06c9eee6-6a73-4282-9f42-9b37050d288c
I believe there is some sort of client logic difference between the "local player" and the "array of players" when it's updating player positions and etc on the client side. Local player bits uses this property:
While update blocks use this array of players:
From what I gather, the reason of the desync in general is because the offset from you to the other player is based on your position and the client thinks …
> fix(engine): exactmove not updating local player position on the client

- data/src/scripts/_unpack/all.loc
- data/src/scripts/general_use/configs/tables.loc
Before: "Nothing interesting happens." when attempting to place item on it.
How it looks with items on the counters:
On OSRS, the counters at giants also allow to place items on them.
> fix(content): Mark counters at giants as a usable table

- src/engine/World.ts
- src/engine/entity/Npc.ts
- src/engine/entity/PathingEntity.ts
- src/engine/entity/Player.ts
- src/engine/script/handlers/NpcOps.ts
- src/engine/script/handlers/PlayerOps.ts
- src/network/rs225/client/handler/InvButtonDHandler.ts
- src/network/rs225/client/handler/InvButtonHandler.ts
- src/network/rs225/client/handler/MoveClickHandler.ts
- src/network/rs225/client/handler/OpHeldHandler.ts
- src/network/rs225/client/handler/OpHeldTHandler.ts
- src/network/rs225/client/handler/OpHeldUHandler.ts
- src/network/rs225/client/handler/OpLocHandler.ts
- src/network/rs225/client/handler/OpLocTHandler.ts
- src/network/rs225/client/handler/OpLocUHandler.ts
- src/network/rs225/client/handler/OpNpcHandler.ts
- src/network/rs225/client/handler/OpNpcTHandler.ts
- src/network/rs225/client/handler/OpNpcUHandler.ts
- src/network/rs225/client/handler/OpObjHandler.ts
- src/network/rs225/client/handler/OpObjTHandler.ts
- src/network/rs225/client/handler/OpObjUHandler.ts
- src/network/rs225/client/handler/OpPlayerHandler.ts
- src/network/rs225/client/handler/OpPlayerTHandler.ts
- src/network/rs225/client/handler/OpPlayerUHandler.ts
Changes:
- Move delay logic back to the beginning of player processing, like in osrs. There are no sources showing different behaviour from osrs.
- Make delay duration the same no matter at what point in the tick it was started. This is motivated by p_arrivedelay, which delays a full tick both from packet processing (spade digging) and interaction.
In practice this means that you can no longer start a new action on the last tick of a delay. For example, previously you could smelt and cook 1t faster than expected due to this.
Delay durations are not changed by this, except in edge cases. For example, p_delay/npc_delay started from world processing are probably 1t longer now. I could only find one such case in rashiliyia.rs2.
> fix(engine): Change delay behaviour to match osrs

- src/engine/entity/Player.ts
Jagex reworked the queue fairly recently (2021?), this is one of the things they changed. Revert to the old behaviour.
> fix(engine): Change strong queue behaviour to match early osrs

- data/src/scripts/levelup/scripts/levelup_unlocks_smithing.rs2
Smithing level up messages are saying you can make spears, when you can't:
<br></br>
Spear creation requirements are **Barbarian training** just for example, which was released in 3 July 2007:
https://oldschool.runescape.wiki/w/Spear
I couldn't find any sources of what the message actually was.. For now, I've removed the spear portion from all Smithing level up messages, and also replaced the icon with arrow heads:
As there is no smithing constructs for creating spears either, I believe this change will do for now(?)
> fix(content): Remove spear text, replace icon with arrowheads

- data/src/scripts/skill_prayer/scripts/prayers/clarity.rs2
All other prayers have this already. Meant you could stack clarity prayer interfaces by just spam clicking.
> fix(content): Add missing protected access check to clarity prayer

- src/engine/entity/Player.ts
- src/engine/script/handlers/PlayerOps.ts
in osrs, only the last level of a stat level up is shown per skill.
https://github.com/user-attachments/assets/a852d881-b5cb-4c82-8893-e0bafe80286b
> fix(engine): clear multiple stat_advance engine queues of one skill type

- src/engine/entity/NetworkPlayer.ts
For example, the current logic, makes you not able to spam click to pickup items on the floor, because your "queue" essentially gets filled with handles to objs that no longer exist.
Now it will only count towards the limiter when they are successfully handled.
> fix(engine): in packets failed accounting towards queue limit

- data/src/scripts/areas/area_camelot/scripts/sir_gawain.rs2
- data/src/scripts/areas/area_lumbridge/scripts/father_aereck.rs2
- data/src/scripts/areas/area_varrock/scripts/aubury.rs2
- data/src/scripts/areas/area_wizard_tower/scripts/sedridor.rs2
- data/src/scripts/quests/quest_ikov/scripts/quest_ikov.rs2
- Typos in merlins crystal, restless ghost, ikov
- fix opnpcu interactions during rune mysteries (TODO: figure out if these existed before OSRS rework)
> fix(content): quest fixes

- src/engine/entity/PathingEntity.ts
- src/network/rs225/client/handler/MoveClickHandler.ts
- src/network/rs225/client/handler/OpHeldHandler.ts
- src/network/rs225/client/handler/OpHeldTHandler.ts
- src/network/rs225/client/handler/OpHeldUHandler.ts
https://github.com/user-attachments/assets/ede0e0df-ba4c-4936-9f30-05e8c8cc1509
https://github.com/user-attachments/assets/2222471b-b470-4390-84b8-2aa2ca2d22e9
https://github.com/user-attachments/assets/0e44ea87-cd08-49e4-903e-aeb605f24a93
> fix(engine): fix spam click obj bug

- data/src/scripts/areas/area_falador/scripts/sir_amik_varze.rs2
- data/src/scripts/quests/quest_blackknight/scripts/quest_blackknight.rs2
Sorry for the double PR, I had to quickly relearn `git remote` and branch from the correct place.
This closes #1058 with the added bonus that I _think_ I have fixed black knight overhead text/aggression correctly (tested both areas several times and saw no issues with removing the `$has_spoken` stuff).
> fix(content): fix typo, improve quest stage setting, also fix quest-related black knight aggression

- data/src/scripts/drop tables/scripts/goblin.rs2
https://oldschool.runescape.wiki/w/Goblin
> 18 February 2016
> (update | poll)
> Hammers are now dropped by goblins. 
https://oldschool.runescape.wiki/w/Poll:Quality_of_Life_-_Top_10_PvM_Suggestions
> Should a hammer drop be added to the drop table of goblins? This would make it easier to get into the Bandos Godwars room if > you have forgotten a hammer.
> fix(content): Remove hammer drop from goblins

- data/src/scripts/areas/area_ardougne_east/scripts/siegfried_erkle.rs2
- Connect Legends' Guild Shop of Useful Items
- Implement Siegdried Erkle
Later sources show right-click trade but our cache does not have it so it was added later.
- https://runescape.wiki/w/Siegfried_Erkle
- https://oldschool.runescape.wiki/w/Siegfried_Erkle
- https://classic.runescape.wiki/w/Siegfried_Erkle
> Strangely, whenever you talk to him, he appears to be sad instead of happy. This is likely a glitch.
RSC has Siegdried Erkle tell you off if you have not completed legend's guild but others do not. For now I have not implemented that restriction
> feat(content): Implement Siegfried Erkle 

- data/src/scripts/drop tables/scripts/tribesman.rs2
- Added drop table for tribesman
- https://oldschool.runescape.wiki/w/Tribesman
- https://runescape.wiki/w/Wandering_warrior
- https://classic.runescape.wiki/w/Tribesman
OSRS has trading sticks and cleaning cloths. They happen to align, weight and value wise with some RSC drops so 138 as the base rate was used (from OSRS and RS3) but later drops replaced with their RSC drops.
<!-- #Outside of scope ->
> feat(content): Add drops to tribesman

- data/src/scripts/drop tables/oomlie_bird.rs2
- Implement Oomlie bird raw meat drop as always
- https://runescape.wiki/w/Oomlie_bird
- https://oldschool.runescape.wiki/w/Oomlie_bird
- https://classic.runescape.wiki/w/Oomlie_Bird
Also tried cooking it. RS3/OSRS talk about burning it if you try and cook without a leaf but in 2004 it appears that you just could not cook it. What we are doing right now is authentic. You can use a palm leaf and wrap the meat then cook it.
[historic source](https://runescape.wiki/w/Raw_oomlie?direction=next&oldid=1417322)
<!-- #Outside of scope ->
> feat(content): implement oomlie bird drop

- src/engine/World.ts
- src/engine/zone/Zone.ts
- src/network/server/codec/ZoneMessageEncoder.ts
When a player logs in, they do not have any loaded zones yet when enclosed shared zone buffers are computed. Because 2004scape builds a list of zones, based on players loaded zones, for this computation, if there are 0 players nearby, this work is not done. This is only a problem when players login for the 1 tick this happens, logging into these zones, versus running back into them, etc. Because the server wants to send these updates from the zones as shared enclosed updates.
I adjusted the durations to match my login speed accordingly for quickly testing.
I wasn't able to reproduce this with Locs, but there may be some edge case I'm not thinking of. But either way Locs seem unaffected.
This is basically the fix I did.
I made `computeShared` slightly better by using a statically allocated …
> fix(engine): stop relying on player zones to compute shared enclosed zone buffers

- data/src/scripts/quests/quest_desertrescue/configs/desertrescue.constant
- data/src/scripts/quests/quest_desertrescue/scripts/ana.rs2
- data/src/scripts/quests/quest_desertrescue/scripts/captain_siad.rs2
- data/src/scripts/quests/quest_desertrescue/scripts/irena.rs2
- data/src/scripts/quests/quest_desertrescue/scripts/quest_desertrescue.rs2
- fix wrong obj deletion when dropping ana
- fix siad not sending guards on a dialogue branch
- prevent guards from being sent after completing quest
- change camp cave entrance blocking after quest to match OSRS
- fix duplicate constant value being used for ana's rescue
> fix(content): desertrescue fixes

- data/src/pack/npc.pack
- data/src/scripts/_unpack/all.npc
- data/src/scripts/drop tables/scripts/ice_warrior.rs2
I verified this against RSC/OSRS wikis and also checked in-game in OSRS, these warriors should be on the drop table too!
> fix(content): add queen's guard to ice_warrior droptable

- data/src/scripts/drop tables/scripts/goblin.rs2
- Fix incorrect drop for goblins in goblin village when playing on F2P Server
- https://oldschool.runescape.wiki/w/Goblin
- https://runescape.wiki/w/Goblin
The whole goblin drop table rates may need to be audited.
<!-- #Outside of scope ->
> fix(content): Correct f2p drop from goblin

- data/src/scripts/levelup/scripts/levelup_unlocks_firemaking.rs2
- data/src/scripts/levelup/scripts/levelup_unlocks_woodcutting.rs2
- Firemaking unlocks share the same object size and positioning as woodcutting unlocks, as shown by these old screenshots:
- Removed black punctuation from firemaking unlocks
- "You can now cut down Magic Trees" fixed to "Members can now cut down Magic Trees"
- "You can now burn Magic Logs" fixed to "Members can now burn Magic Logs"
> fix(content): fire making and woodcutting unlock messages

- data/src/pack/varp.pack
- data/src/scripts/_test/scripts/cheats/cheat_quest.rs2
- data/src/scripts/quests/quest_desertrescue/scripts/quest_desertrescue.rs2
- data/src/scripts/quests/quest_ikov/configs/quest_ikov.constant
- data/src/scripts/quests/quest_ikov/configs/quest_ikov.varp
- data/src/scripts/quests/quest_ikov/scripts/ikov_dungeon.rs2
- data/src/scripts/quests/quest_ikov/scripts/quest_ikov.rs2
Change the ikov bridge to use a varp to determine which side the player is on (this won't be needed for later versions since the middle tiles are blocked off, but we don't know if original behavior was just broken or not), queue when walking from west -> east (matching OSRS behavior)
> fix(content): change ikov bridge logic

- src/engine/zone/Zone.ts
- src/engine/zone/ZoneEntityList.ts
Zones have a hard limit to the number of locs and objs that can be within one. The current implementation is manually counting the number of them in the zone every time an obj or loc is added or removed.
```ts
private get total(): number {
let total: number = 0;
for (let index: number = 0; index < this.length; index++) {
const items: T[] | undefined = this[index];
if (typeof items === 'undefined') {
continue;
}
total += items.length;
}
return total;
}
```
Instead of doing this, we just keep track of the amount using `count` and boom 500ms faster.
> feat(engine): improve the speed of zone entity list capacity checking

- data/src/scripts/areas/area_desert/scripts/desert_heat.rs2
- data/src/scripts/quests/quest_desertrescue/scripts/quest_desertrescue.rs2
- data/src/scripts/quests/quest_itgronigen/scripts/quest_itgronigen.rs2
- slave robes no longer give desert protection, shirt reduced to 10t save (2023 OSRS change)
- `Desert effect is now over.` mes when leaving the desert
- desertrescue/observatory dialogue changes based off old images
> fix(content): authenticity changes for desertrescue, desert heat, observatory

- data/src/scripts/areas/area_desert/scripts/desert_heat.rs2
- data/src/scripts/quests/quest_desertrescue/scripts/quest_desertrescue.rs2
- data/src/scripts/quests/quest_itgronigen/scripts/quest_itgronigen.rs2
- src/engine/entity/Npc.ts
After the last update - `npc_death` called `npc_del`, which then would clear NPC heropoints immediately. I'm not sure how it didn't prevent all npc_findhero drops, but it was found because random events were suspiciously dropping nothing
> fix: NPC drops were a little too rare!

- data/src/scripts/areas/area_wilderness/configs/wilderness.varp
- data/src/scripts/areas/area_wilderness/scripts/wilderness_warning.rs2
- data/src/scripts/music/scripts/move.rs2
...also makes it so if you login in the wildy, and go to border you get the warning. No idea if this was authentic. But the reasoning being, I'd have to add an exception for the underground wilderness warning zone - you can enter that from the side, instead of from the south. I could make it so it checks if you're in the wilderness on login, but I'd like to confirm it with a video first
> fix(content): delay wilderness warning by 1t and make it once per login

- data/src/scripts/quests/quest_hunt/scripts/luthas.rs2
Source: https://www.youtube.com/watch?v=SInMQzx1K1I&t=181s
Pretty sure something is wrong with the engine to require using if_close here, but we already do it in lots of other places.
> fix(content): Add missing if_close in luthas dialogue

- src/engine/entity/Player.ts
- src/network/rs225/client/handler/CloseModalHandler.ts
Fixes:
- Handle close modal request at start of player processing
- Make last login info modal purely client sided
> fix(engine): Close modal improvements

- src/engine/entity/PathingEntity.ts
```ts
this.orientationX = CoordGrid.moveX(this.x, dir) * 2 + 1;
this.orientationZ = CoordGrid.moveZ(this.z, dir) * 2 + 1;
```
This is not calculating correctly for npc with size > 1.
----
```ts
// direction when the player is first observed (updates on movement)
this.orientationX = faceX;
this.orientationZ = faceZ;
// direction update (only updates from facesquare or interactions)
this.faceX = faceX;
this.faceZ = faceZ;
```
Move this up so it is always set again when doing an interaction. Does not necessarily require the `FaceCoord` mask to be set during this.
This was under the `Loc/Obj` condition, which was fine. However, when an interaction is set on a Player or Npc, and their target is a Player or Npc, it only does a `FaceEntity` mask, which was fine. But when you relog, or run away …
> fix(engine): facecoord not being updated upon interaction with other pathing entities properly

- data/src/scripts/areas/area_varrock/scripts/aubury.rs2
This changes the script to correctly display Aubury's name and chat-head giving the Notes, instead of the player's.
> fix(content): Rune Mysteries Lost Notes Dialogue

- data/src/pack/seq.pack
- data/src/scripts/_unpack/all.seq
- data/src/scripts/quests/quest_chompybird/configs/quest_chompybird.constant
- data/src/scripts/quests/quest_chompybird/configs/quest_chompybird.hunt
- data/src/scripts/quests/quest_chompybird/configs/quest_chompybird.npc
- data/src/scripts/quests/quest_chompybird/scripts/chompy_bird.rs2
- data/src/scripts/quests/quest_chompybird/scripts/ogre_bow.rs2
- data/src/scripts/quests/quest_chompybird/scripts/rantz.rs2
- data/src/scripts/quests/quest_chompybird/scripts/raw_chompy.rs2
- Add chompy kill tracking, fixes #799 
- Fix chompy behaviour:
- Toad hunt was only triggering if chompy spawned on same tile as toad
- Add landing animation
- Remove player retaliation and add retreating
- Ensure burning the chompy during the quest doesn't allow you to progress
- Check player still has the chompy during Rantz's hand-in dialogue
> fix(content): fixes for chompy bird hunting, add kill tracking

- data/src/scripts/skill_combat/scripts/player/weapon_category.rs2
from [video](https://youtu.be/Mo6AcO4rg4A?t=69)
> fix(content): autocast "You need to choose a spell first." mes

- data/src/scripts/areas/area_brimhaven/scripts/pineapple_plants.rs2
Looks like this was used during testing to ensure the plant was being "depleted" whilst picking, but wasn't removed after
> fix(content): remove pineapple_plants debug message

- src/engine/zone/Zone.ts
If the obj has an owner and gets deleted, this does a `follows` event, the problem however, is the event was being sent for `-1` receivers, which is allowing the follow events to be sent out for everyone. The problem is only found when this is done using the same type of obj on the same tile.
```ts
writePartialFollows(player: Player): void {
if (this.events.size === 0) {
return;
}
player.write(new UpdateZonePartialFollows(this.x, this.z, player.originX, player.originZ));
for (const event of this.follows()) {
if (event.receiver64 !== Obj.NO_RECEIVER && event.receiver64 !== player.hash64) {
continue;
}
player.write(event.message);
}
}
```
> fix(engine): deleting objs of the same type being sent out to clients incorrectly

- data/src/scripts/areas/area_port_sarim/scripts/thurgo.rs2
- data/src/scripts/quests/quest_squire/scripts/quest_squire.rs2
From RSC Wiki, after the quest:
https://classic.runescape.wiki/w/Transcript:Thurgo#After_The_knight's_sword_quest
_Player: Thanks for your help in getting the sword for me
Thurgo: No worries mate_
From RS3 Wiki, after the quest:
https://runescape.wiki/w/Transcript:Thurgo#After_the_Knight's_Sword
Choice 3: Something else.
_Player: About that sword...
Player: Thanks for all your help getting it for me!
Thurgo: No worries mate._
OSRS Wiki, just for reference:
https://oldschool.runescape.wiki/w/Transcript:The_Knight%27s_Sword
There is no mention of "_No worries mate._" which was used in Classic -> RS3 which suggests the OSRS dialogue was re-written at some point.
I've therefore gone with the RSC Wiki version because there are no other Choices like in RS3, and can presume it would just be: …
> fix(content): thurgo post-quest dialogue

- data/src/scripts/player/scripts/stat.rs2
Commented example of drinking a beer given a boosted str lvl of 3 and base str lvl of 1:
```js
[proc,stat_addclamp](stat $stat, int $constant, int $percent) //strength,1,2
def_int $base_level = stat_base($stat); // 1
def_int $level = stat($stat); // 3
// calculate the maximum level based on the base level
def_int $max_level = calc($base_level + ($constant + scale($base_level, 100, $percent)));
// => 1 + (1 + (1*2)/100) => 2
// calculate the boost and lower it to max - level if it goes over
def_int $boost = calc($constant + scale($level, 100, $percent));
// => 1 + (3*2)/100 => 1
if (calc($level + $boost) > $max_level) { // => true
$boost = calc($max_level - $level);
// => 2 - 3 => -1
}
// add the boost, with no percent
stat_add($stat, $boost, 0); // $boost is -1 => exception
```
> fix(content): was possible to attempt stat_add with negative value

- src/engine/zone/Zone.ts
I want to ensure that objs and locs deletions happen before respawn additions, by putting each step into their own dedicated loops until there is no more work to be completed. This happens for deletions first, and additions afterward. In an attempt to nail down the weird bug with them going invisible.
> fix(engine): ensure locs are always deleted before added

- src/engine/entity/BuildArea.ts
- src/network/rs225/server/codec/NpcInfoEncoder.ts
- src/network/rs225/server/codec/PlayerInfoEncoder.ts
- src/util/Numbers.ts
Today we loop 25 zones around the player to search for nearby npcs.
An optimization can be made where, standing on the edge of your zone, will loop 20 zones around you, and standing in the corner of a zone, will loop 16 zones around you.
I also removed the redundant checks, it should not be possible to view players or npcs outside of your build area. The maximum view distance is 15 tiles.
> feat(engine): improve searching speed for nearby npcs

- data/src/scripts/areas/area_wilderness/configs/wilderness_zones.dbrow
Dark Warrior's Fortress goes up to level 3. For example, checking each coord at the south east ladder:
0,47,56,28,42
1,47,56,28,42
2,47,56,28,42
3,47,56,28,42
Rogues' Castle also goes up to level 3:
0,51,61,17,32
1,51,61,17,32
2,51,61,17,32
3,51,61,17,32
Used the same method as resolving the Tutorial Island height check:
https://github.com/2004Scape/Server/commit/494d404227787a8c02f331215d213f83531ddc93
Tested working at each level
> fix(content): wilderness height check

- data/src/scripts/skill_mining/scripts/prospect.rs2
Prospecting a gas rock currently returns "Nothing interesting happens."
This fix will return the normal prospect message. It may have been different in 2004 but I haven't yet been able to find a source
> fix(content): gas rock prospect message

- src/network/rs225/client/handler/OpHeldHandler.ts
- src/network/rs225/client/handler/OpHeldTHandler.ts
- src/network/rs225/client/handler/OpHeldUHandler.ts
- src/network/rs225/client/handler/OpLocHandler.ts
- src/network/rs225/client/handler/OpLocTHandler.ts
- src/network/rs225/client/handler/OpLocUHandler.ts
- src/network/rs225/client/handler/OpNpcHandler.ts
- src/network/rs225/client/handler/OpNpcTHandler.ts
- src/network/rs225/client/handler/OpNpcUHandler.ts
- src/network/rs225/client/handler/OpObjHandler.ts
- src/network/rs225/client/handler/OpObjTHandler.ts
- src/network/rs225/client/handler/OpObjUHandler.ts
- src/network/rs225/client/handler/OpPlayerHandler.ts
- src/network/rs225/client/handler/OpPlayerTHandler.ts
- src/network/rs225/client/handler/OpPlayerUHandler.ts
All of these packets call into `player.clearPendingAction();` anyways, but we need to do it on hard failed handled packets, like menu options, visibility, inventory listeners, etc, things that should be impossible for the client to see or do. I did not add these to any of the `delayed` checks.
> fix(engine): clear pending action upon failed packet validations

- data/src/pack/varp.pack
- data/src/scripts/_unpack/all.varp
- data/src/scripts/areas/area_varrock/scripts/curator.rs2
- data/src/scripts/quests/quest_itexam/configs/quest_itexam.constant
- data/src/scripts/quests/quest_itexam/configs/quest_itexam.varp
- data/src/scripts/quests/quest_itexam/scripts/area_digsite.rs2
- data/src/scripts/quests/quest_itexam/scripts/digsite_workman.rs2
- data/src/scripts/quests/quest_itexam/scripts/examiner.rs2
- data/src/scripts/quests/quest_itexam/scripts/panning_guide.rs2
- data/src/scripts/quests/quest_itexam/scripts/private_dig_worker.rs2
- data/src/scripts/quests/quest_itexam/scripts/quest_itexam.rs2
- data/src/scripts/quests/quest_itexam/scripts/student1.rs2
- data/src/scripts/quests/quest_itexam/scripts/student2.rs2
- data/src/scripts/quests/quest_itexam/scripts/student3.rs2
- move bits used for itexam out of the progress varp and into varp 132/133, move thieving timer to 138
- add interactions for level 1/2/3 cert to the varrock curator
- don't send the clean message if you find nothing from level-3 digging
- alter flow for getting the key from the digsite workman to match RSC/pre-rework
- adjusted some dialogue/mesanims based off old images/OSRS
> fix(content): digsite quest fixes

- data/src/scripts/_test/scripts/engine/debug_walktrigger.rs2
- data/src/scripts/skill_combat/scripts/pvp/pvp_magic.rs2
Sound doesnt play for a tick (I yellow click at 389 ticks and sound begins at 391 ticks)
https://github.com/user-attachments/assets/bc0ff4e6-9ba6-42b8-9ab9-7f142696cd9e
PVP freezes are definitely queued, lasts 8 ticks after the p_delay is over:
https://github.com/user-attachments/assets/d7ea41d5-aaa1-4a03-88ae-34e3514f97f3
Us with fixes:
https://github.com/user-attachments/assets/33db18c5-39e9-4bdf-9ab0-f9a98f43633e
Also lets us remove the +1's in the pvp stun length :D.
> fix(content): p_stopaction on pvp stuns

- data/src/scripts/skill_combat/scripts/npc/npc_combat_melee.rs2
in osrs melee npcs cant deal damage when they're at 0 hp. Still sets the attack vars though
> fix(content): npc on 0 hp when meleeing behavior

- data/src/scripts/interface_trade/scripts/trade.rs2
Doing `sub(.inv_size(inv), $slot)` does not work if the obj is stackable, for `inv_itemspace`.
> fix(content): trading not accounting for stackable objs correctly

- src/engine/entity/Player.ts
players previously would not gain run energy while following another player who is walking if they had run enabled. 
https://youtu.be/ZRzDMzTRMT8?t=376 shows a player with run energy enabled restoring run energy while pathing to another player who is walking. This behavior was inconsistent with both attacking and following other players on 2004Scape. Checking stepsTaken < 2 instead of MoveSpeed.RUN recovers energy at the same rate, while allowing for proper restoration while pathing towards others
> fix(engine): fix run energy to recover while walking with run enabled

- data/src/scripts/skill_woodcutting/scripts/woodcut.rs2
Previously, the message was "You do not have an axe which you have the woodcutting level to use.".
This doesn't seem authentic according to images I have seen, including those commented in the code. It does not mention 'woodcutting' in the message authentically.
> fix(content): Fix message received when woodcutting without axe

- src/engine/World.ts
- src/engine/entity/Player.ts
`BuildArea#clear` clears the following properties on the `Player`.
```ts
clear(): void {
this.players.clear();
this.npcs.clear();
this.loadedZones.clear();
this.activeZones.clear();
this.appearances.clear();
}
```
Since you're going for rebuilding during reconnecting, might as well just clear the zones.
The client also clears out the appearance cache:
https://github.com/2004Scape/Client/blob/lastmain/client/src/main/java/client.java#L7695
Also refresh all of the player inv listeners by doing `listener.firstSeen = true` on all of them. This will also refresh `weight`.
> fix(engine): resync invs and appearances on reconnect

- src/engine/entity/Player.ts
The logic block for handling when a player interacts with an entity is refactored and reorganized. It should now also match documented behavior better.
The first Nothing interesting happens message is given the cycle after player moves
https://github.com/user-attachments/assets/4f8fa8ee-2b1f-49eb-afd9-88f5795579ed
The first Nothing interesting happens message is given the same cycle as player's movement
https://github.com/user-attachments/assets/00647ce3-0062-4a0c-9b28-bde331adf264
The first Nothing interesting happens message is given the cycle after player moves
https://github.com/user-attachments/assets/387754af-67c9-4bcf-8218-31e17ec5f7e3
3 interacts due to how p_aprange() is handled
https://github.com/user-attachments/assets/65f63e31-c8dd-4bd7-b250-61da479e4970
Only 2 interacts due …
> fix(engine): Refactor and organize player interactions, match interaction behavior closer to documented rs2 mechanics

- data/src/scripts/macro events/scripts/macro_events.rs2
No good way to confirm this is how it works but it seems like something they'd do. Notably it only checks LOW with the sw tile, I could add LOW check for all 4 tiles but we have like no source for this. This is probably fine?
> fix(content): check if rock golem sw tile has LOW with player

- src/engine/World.ts
This happens on low fps (use cpu performance throttling in browser preferably chrome, but not needed for it to happen):
1. isclientconnected is true (correct), but bytesRead will be 0 + out packet pos in client is 0 until buildScene is ran
2. tryLogout or loggedOut gets set as lastResponse is -1 due to not being set in decodeIn (tryLogout sets loggedOut later as well)
3. however long it takes for buildScene to run later: bytesRead is now non 0, lastResponse finally gets set
4. flushPlayer gets called and logoutRequests is set (either before or after step 3 doesn't matter you log off)
This change stops players from instantly disconnecting when creating new account which solves the issue, but I don't understand why I can't reproduce the disconnect on existing accounts???
> fix(engine): set player.lastResponse on login to avoid new account dc

- src/engine/World.ts
- src/engine/entity/BuildArea.ts
- src/engine/entity/Player.ts
- We need to keep the active zones atleast. I'm basically reverting the last PR on the zones bit.
- Create a `onReconnect` fn to clean it up a little.
> fix(engine): dont clear zones on reconnect instead

- src/engine/World.ts
- src/engine/entity/PlayerLoading.ts
The problem was just the playerloading.load returning before lastResponse is set if no save, this works now until it reaches 30 sec as intended.
This fix is not needed anymore so removed it again: https://github.com/2004Scape/Server/pull/1215
> fix(engine): real fix for new acc dc

- data/src/scripts/_unpack/all.inv
- data/src/scripts/interface_bank/scripts/bank.rs2
- data/src/scripts/minigames/game_partyroom/configs/partyroom.inv
- data/src/scripts/minigames/game_partyroom/scripts/partyroom_chest.rs2
- data/src/scripts/minigames/game_trawler/scripts/trawler_win.rs2
Bank reorganise being queued was confirmed by leaving an empty slot before closing bank, then banking an item with imp-in-a-box without letting queue run. This put the banked item in the empty slot. Doing the same test but letting queue run first resulted in the banked item being placed at the end.
> fix(content): if_close trigger fixes

- data/src/scripts/areas/area_varrock/scripts/captain_rovin.rs2
- data/src/scripts/quests/quest_demon/scripts/delrith.rs2
- data/src/scripts/quests/quest_demon/scripts/demon_slayer.rs2
Source for name: https://youtu.be/-QCLVYNZfYo?si=ECm_o7WIuJ8M2-tE&t=213
I don't have a source for the water bucket. It can be rolled back if it was authentic the old way. Now the bucket is replaced when the player gets a message that they have poured the water down.
> fix(content): Fix issues with demon slayer authenticity

- src/engine/World.ts
- src/engine/entity/Player.ts
This ensures that, if there is a pending server shutdown ("system update") when a client reconnects, that the number of ticks remaining will be sent. Otherwise, on reconnection, the client loses the timer.
> fix(engine): send reboot timer on reconnect

- data/src/scripts/skill_cooking/scripts/cooking.rs2
From a [speed training guide](https://web.archive.org/web/20041013102610/http://runehq.com/viewspecialreports.php?id=00248) `5.Keep an eye out for the text messages instead of the animation. The animation takes longer than the action itself, and can save you quite some time, if you follow the messages instead.`
Currently our cooking is 4 ticks. At a range its not really noticeable that the 'animation takes longer than the action itself' at this 4t speed. Its only noticeable at 3 ticks.
I think also during the rs2 beta, cooking was slower than rsc (3 ticks). They made a [blog post](https://oldschool.runescape.wiki/w/Update:RS2_progress_report) that mentions cooking speeds: `We have also been working hard to tweak RS2 on the basis of your feedback. For instance we've been working to make …
> fix(content): make cooking 1t faster

- src/engine/entity/BuildArea.ts
- src/network/rs225/server/codec/NpcInfoEncoder.ts
- src/network/rs225/server/codec/PlayerInfoEncoder.ts
Searching for nearby players is done in a spiraling pattern around the player today. This search is particularly only useful when your view distance of players gets smaller and smaller, as player density increases to 250+. 
I add an additional way to search for players by zone lookup, when your view distance is currently unchanged. I've found this to be less work then doing a full spiral loop every tick, when the area is not dense.
And this is what I get for an extremely packed area.
I also made it so when you teleport into a dense area of players, this will automatically decrease your view distance and switch to search by nearby.
> feat(engine): search for nearby players using different algorithms

- src/engine/World.ts
- src/engine/entity/PathingEntity.ts
- src/engine/entity/Player.ts
- src/network/rs225/client/handler/MoveClickHandler.ts
Following a player before 2007 was pid dependent. With this PR, behavior should now match pre-2007 behavior.
Further, there were some bugs with how walktriggers are handled. They should now more accurately match expected behavior
When following a player, it should be pid-dependent whether or not you follow two tiles or three tiles back
[In this video from 2006](https://youtu.be/CszyqcDFnp8?si=vuA33EFLT0XCbeKS&t=101), we see that the players clearly get separated into two distinct groups based on pid
https://github.com/user-attachments/assets/393d3e3f-465b-42e2-9aa6-09bf4156d80b
With this PR, 2004scape now correctly sorts following players into two groups depending on pid. This should be the expected behavior.
Before 2023 in OSRS and pre-OSRS, if a player teleported away while you were …
> fix(engine): Follow pathing and walk triggers behave closer to pre-2007 behavior

- src/engine/World.ts
- src/engine/entity/PathingEntity.ts
- src/engine/entity/Player.ts
- src/network/rs225/client/handler/MoveClickHandler.ts
Stacks on previous pull request: https://github.com/2004Scape/Server/pull/1238
This is mostly a significant code re-organization with very minor behavioral differences. The logic in the movement-interaction block of code is significantly de-duplicated and is now structured as simple as possible. This is likely my final commit to this portion of the code
These are some small behavioral differences that this PR accomplishes
1. Run energy logic is now handled _after_ the interaction attempt that happens after player movement. This means that if the interaction trigger p_delays the player, run energy will not increment or decrement. This is authentic to rs2 behavior
2. Previously, the logic would check if the player is in a different location than they started to determine that they 'moved'. …
> fix(engine): Reorganize interactions, movement, and run energy

- src/engine/script/handlers/ServerOps.ts
To fix being able to get out into members areas.
To be clear, the members areas are unloaded and you cannot actually do anything while on a F2P world.
> fix(engine): lineofsight and lineofwalk commands returning true for members zones in F2P

- data/src/scripts/areas/area_wizard_tower/scripts/sedridor.rs2
Fix typo in sedridor typo
2008 source: https://www.youtube.com/watch?v=rCC0CJQoXAE
Transcript source: https://runescape.wiki/w/Transcript:Rune_Mysteries_(historical)
I don't see any evidence that this typo is authentic
> fix(content): correct Sedridor typo

- data/src/pack/varp.pack
- data/src/scripts/_test/scripts/cheats/cheat_reset.rs2
- data/src/scripts/_unpack/all.varp
- data/src/scripts/areas/area_varrock/scripts/thessalia.rs2
- data/src/scripts/player/scripts/untradeable_holiday_items.rs2
- data/src/scripts/skill_magic/scripts/spells/telegrab.rs2
New file, as there doesn't seem to be anywhere else appropriate. Any suggestions welcome. It's in `data\src\scripts\player\scripts` which also contains `pickup.rs2`, `cracker.rs2`, which are semi-related and is personal to the player. Is there a better place for this? I considered renaming `cracker.rs2` to `holiday_items.rs2`, and merge together to reduce clutter and cover any future items (`rubber_chicken` hype??).
The intention is, which is tested as working:
- `scythe`:
- - If you try pick up a `scythe`, and you don't already have one, pick it up and set `%scythe_unlocked = 1`
- - If you try pick up a `scythe`, and you do already have one, don't allow it
- `bunny_ears`:
- - If you try pick up `bunny_ears`, and you don't already them, pick it up and set `%bunny_ears_unlocked = 1`
- - If …
> fix(content): thessalia dialogue, bunny_ears, scythe

- data/src/scripts/quests/quest_chompybird/configs/quest_chompybird.constant
- data/src/scripts/quests/quest_chompybird/scripts/chompy_bird.rs2
- data/src/scripts/quests/quest_chompybird/scripts/ogre_bow.rs2
- data/src/scripts/quests/quest_chompybird/scripts/quest_chompybird.rs2
- data/src/scripts/skill_fletching/scripts/ogre_arrows.rs2
fixes https://github.com/2004Scape/Server/issues/801
* Add ranged xp reward to chompy bird hunting (once you hit 4000), can't confirm it existed for sure before https://oldschool.runescape.wiki/w/Update:Quest_Journals_and_Chompy_Hats, but since tracking did exist (and the reward isn't mentioned as an update anywhere), it seems likely
* reset `chompybird_kills` after quest completion, and cap at 100k (https://x.com/jamesmonger/status/1819334219308343466)
> fix(content): changes to chompy bird tracking, ranged xp reward

- src/engine/World.ts
- src/engine/entity/Player.ts
I can't reach that! was firing prematurely if player p_access was blocked. It is now moved into the portion of the code that requires p_access
Further, a few unused codes were removed
> fix(engine): I can't reach that! bug fix + remove unused code

- data/src/scripts/levelup/scripts/levelup.rs2
from [video](https://youtu.be/UFgMqvI4to8?t=83): 
https://github.com/user-attachments/assets/b667d6d9-36b8-4cee-877c-7af7a830269e
Ours:
https://github.com/user-attachments/assets/bb195a61-8265-4771-842a-e1fbe70fd1de
- https://youtu.be/LdnO1_wTmls?t=15
- https://youtu.be/gUB1rS53IFc?t=10292 (p_arrivedelay at start of the script)
- https://youtu.be/zXMXcij4748?t=156
> fix(content): remove queue for level ups, make them run straight from eq

- data/src/scripts/skill_fishing/scripts/fishing_spots/cage_harpoon_fishing.rs2
- data/src/scripts/skill_fishing/scripts/fishing_spots/lure_bait_fishing.rs2
- data/src/scripts/skill_fishing/scripts/fishing_spots/net_bait_fishing.rs2
- data/src/scripts/skill_fishing/scripts/fishing_spots/net_harpoon_fishing.rs2
Fishing synths should only play once when you start the action. This saw more changes after https://oldschool.runescape.wiki/w/Update:Area_Sounds
> fix: Changed fishing synths to be only on start of the action

- prisma/multiworld/migrations/20250210235403_input_tracking/migration.sql
- prisma/multiworld/schema.prisma
- prisma/singleworld/migrations/20250210135320_input_track/migration.sql
- prisma/singleworld/schema.prisma
- src/db/types.ts
- src/engine/World.ts
- src/engine/entity/tracking/InputEvent.ts
- src/engine/entity/tracking/InputTracking.ts
- src/network/rs225/client/handler/EventTrackingHandler.ts
- src/server/logger/LoggerClient.ts
- src/server/logger/LoggerServer.ts
- src/server/logger/LoggerThread.ts
- All events now report user as active (wasn't sure on intention here - can revert if needed)
- Adds input_report and input_report_event table, populated by logger server on input_track message
> feat(engine): submit input reports to logger server

- tools/server/setup.ts
Very similar to "configure single" but in dev mode but I thought this probably deserves its own top-level menu item
> feat: add `configure-dev-stack` setup step to run supporting servers for dev

- prisma/singleworld/migrations/20250210135320_input_track/migration.sql
#1266 had some mysql dialect in the sqlite migrations. I will make a CI pipeline to detect this
> fix: use sqlite dialect for `20250210135320_input_track`

- data/src/scripts/drop tables/scripts/grip.rs2
- data/src/scripts/quests/quest_hero/scripts/locs/brimhaven_scarface_mansion.rs2
- data/src/scripts/quests/quest_hero/scripts/npcs/grip.rs2
Grip was getting distracted before getting into the room to be shot at. This fixes that.
Player delay added to the situation like in OSRS, delay of 7 ticks measured with RSProx.
> fix(content): heros quest grip walking bug

- src/engine/entity/Player.ts
- src/engine/renderer/PlayerRenderer.ts
- src/engine/script/handlers/PlayerOps.ts
`buildappearance` is generating the byte array every time it is called. this can be optimized by just setting the inv and mask and build the byte array once instead.
> feat(engine): only build appearance once if requested multiple times

- src/engine/script/handlers/InvOps.ts
Since the change in `obj_count` now can return 0, this command is only used for `inv_itemspace` which was doing a bounds check of 1-2147483647. So we make a change for `inv_itemspace` and `inv_itemspace2` to return false if the inputted count is 0.
> fix(engine): hard check for 0 count for inv_itemspace commands

- src/engine/World.ts
- src/engine/entity/NetworkPlayer.ts
- src/network/rs225/client/handler/OpLocUHandler.ts
- src/network/rs225/client/handler/OpNpcTHandler.ts
- src/network/rs225/client/handler/OpNpcUHandler.ts
- src/network/rs225/client/handler/OpObjTHandler.ts
- src/network/rs225/client/handler/OpObjUHandler.ts
- src/network/rs225/client/handler/OpPlayerTHandler.ts
- src/network/rs225/client/handler/OpPlayerUHandler.ts
They changed use item (and report option) in osrs at some point, allowing them to be used for interface walking. Was not the case originally.
> fix(engine): Revert opu special case

- src/network/rs225/client/handler/EventTrackingHandler.ts
Java client sends `event_type(1)` / `event_type(3)` for R mouse click up/down respectively, and `event_type(2)` / `event_type(4)` for L mouse clicks and all others (ie middle).
This doesn't need to go in with any urgency, but it's worth fixing long-term.
> fix(engine): L/R mouse click events were switched

- src/engine/entity/Player.ts
reverts part of this https://github.com/2004Scape/Server/pull/1054
In OSRS, big xp drops such as quest completions or wines will only show the last level up. This is because `advancestat()` is only being called once. But theres certain scenarios where `advancestat()` can be called again before the levelup engine queue runs. Since levelup interface & mes are handled in runescript, itll only show the most recent levelup hence why dupe messages can exist.
Osrs during leagues for example:
The only example I could think of for 2004scape is smithing 10 bronze items at level 1 (50+ smith xp), since smithing is p_delay'd in this version. I believe this is authentic behavior, since the interfaces ran straight from the engine queue early osrs and pre 2007 - there are no weakqueue'd interfaces to …
> revert(engine): remove unlinkQueuedScript from levelup engine queue

- data/src/scripts/levelup/scripts/levelup_unlocks_ranged.rs2
When leveling up to 40 Ranged, the unlocks have a small text coloration issue where "Robin" is highlighted properly in blue, while "Hood hat" are moved to the next line and are no longer highlighted in blue. 
This fixes that issue:
> fix(content): Fixing the level up message highlighting for level 40 Ranged.

- src/engine/entity/tracking/InputTracking.ts
If a user does not submit an input tracking report, but they are unable to be logged out (ie: combat), we must not spam the session log. Instead, clear the fact that we have a report pending.
> fix(engine): prevent session log spam

- src/engine/World.ts
- src/engine/entity/Entity.ts
- src/engine/entity/Loc.ts
- src/engine/entity/Npc.ts
- src/engine/entity/Obj.ts
- src/engine/entity/PathingEntity.ts
- src/engine/entity/Player.ts
- src/engine/script/ScriptIterators.ts
- src/engine/script/handlers/ObjOps.ts
- src/engine/zone/Zone.ts
This PR aims to build a robust system for how references to entities are validated to be active entities in the game world. This applies to Locs, Players, Objs, and Npcs
`Entity` now has a new boolean `isActive`. `isActive` will be what we use to keep track of if the `Entity` currently should be available in the `World`
- `isActive` is set to `true` inside of `Zone.addObj()`, `Zone.addStaticObj()`, `Zone.addLoc()`, and `Zone.addStaticLoc()` for non-pathing entities
- `isActive` is also set to `true` inside of `World.addNpc()` and `World.addPlayer()` for pathing entities
- `isActive` is set to `false` inside of `Zone.removeObj()`, and `Zone.removeLoc()` non-pathing entities
- `isActive` is also set to `false` inside of `World.removeNpc()` and `World.removePlayer()` for pathing entities …
> fix(engine): More robust tracking for Entity validation

- src/engine/World.ts
- src/engine/entity/Entity.ts
- src/engine/entity/Loc.ts
- src/engine/entity/Npc.ts
- src/engine/entity/Obj.ts
- src/engine/entity/PathingEntity.ts
- src/engine/entity/Player.ts
- src/engine/script/ScriptIterators.ts
- src/engine/script/handlers/ObjOps.ts
- src/engine/zone/Zone.ts
This PR stacks on top of https://github.com/2004Scape/Server/pull/1301
This PR accomplishes the following:
- `Player.isActive` logic is added to `Player.onLogin()` and `Player.cleanup()`
- All `Entity` lookup methods on `Zone` now use the new `.isValid()` method rather than checking the `Entity`'s LIFECYCLE
- Removes some redundant logic from other places that is now handled inside of `isValid()`
> fix(engine): Use new Entity validation everywhere

- src/cache/PackAll.ts
- src/engine/Inventory.ts
- src/engine/World.ts
- src/engine/entity/Player.ts
- src/engine/script/ServerTriggerType.ts
- src/engine/script/handlers/PlayerOps.ts
- src/network/rs225/client/handler/ClientCheatHandler.ts
- src/network/rs225/client/handler/MoveClickHandler.ts
- src/server/friend/FriendThread.ts
- src/server/login/LoginClient.ts
- src/server/login/LoginThread.ts
- src/server/login/index.d.ts
- src/server/tcp/TcpServer.ts
- src/server/ws/WSServer.ts
- src/util/Environment.ts
- src/util/RuneScriptCompiler.ts
- src/web.ts
- tools/cache/jagUnpack.ts
- tools/server/headless.ts
- tools/server/setup.ts
- Stronger types for LoginThread and FriendThread
- Error logging for failure to update compiler / check for update
- Enhanced error logging for failure to compile runescript files (maybe?)
- Many more minor things that should not affect actual runtime code
> chore(eslint): many eslint fixes

- data/src/scripts/quests/quest_arena/scripts/local.rs2
- data/src/scripts/quests/quest_biohazard/configs/quest_biohazard.obj
- data/src/scripts/quests/quest_upass/configs/upass.obj
- data/src/scripts/skill_magic/scripts/spells/alchemy.rs2
- Prevent alching kittens/cats (witches cat is an exception)
- allow alching on biohazard/upass objs (this was an osrs change)
- fix incorrect dialogue for the local (fight arena)
> fix(content): prevent alching cats, allow alch for biohazard/upass objs, fix typo

- data/src/scripts/quests/quest_itwatchtower/scripts/city_guard.rs2
- data/src/scripts/quests/quest_itwatchtower/scripts/quest_itwatchtower.rs2
`chatplayer` instead of `chatnpc` for city guard dialogue, wrong script type on rock cake eat op
> fix(content): watch tower fixes

- data/src/scripts/macro events/scripts/woodcutting/macro_event_ent.rs2
- data/src/scripts/skill_woodcutting/scripts/woodcut.rs2
- removes the raw herring easter egg:
- matches standard wcing anims and sounds with ent macro events
> fix(content): macro event ents and raw herring easter egg

- src/server/login/LoginServer.ts
Several changes which should increase robustness of the login/logout processing.
- Prevent passing an _invalid_ savefile from the LoginServer to World on login
- Prevent passing an _invalid_ savefile from the LoginServer to World on reconnect
- Prevent passing an _empty_ savefile from the LoginServer to World if the user has previously logged in (and therefore should have a `.sav`.)
- Prevent overwriting an existing savefile with one that has less time played than the existing one `(existingSave.playtime > newSave.playtime)`; this should prevent such cases that have somehow been resetted from being permanently saved on disk.
> fix(engine): add safety checks to savefile loading/storing

- prisma/multiworld/migrations/20250220184917_input_report_event_raw/migration.sql
- prisma/multiworld/schema.prisma
- prisma/singleworld/migrations/20250220184559_input_report_event_raw/migration.sql
- prisma/singleworld/schema.prisma
- src/db/types.ts
- src/engine/entity/tracking/InputEvent.ts
- src/engine/entity/tracking/InputTracking.ts
- src/engine/entity/tracking/ReportEvent.ts
- src/network/rs225/client/handler/EventTrackingHandler.ts
- src/server/logger/LoggerServer.ts
- src/server/login/LoginThread.ts
- src/util/Environment.ts
- Store raw data from client instead of new row per input event (there could be tens of thousands per tracking event!)
- Introduce rate limit for how much data we're willing to store per tracking session (it's 500 bytes limit per flush, and anecdotal testing suggests we won't get more than a few thousand bytes per tracking session, but if someone is malicious, we cap to 50kb per few minutes).
- Fix bug where we were losing part of the logs due to race between ending the tracking session and pushing data to the DB.
In time when we don't need data stored in the previous table we can easily remove it.
Tested:
- Player is still AFK kicked due to no activity
- Players which are tracked vs untracked do not know the difference (we don't end early or anything)
- We don't parse data if the user …
> fix(engine): improve input tracking

- src/engine/World.ts
- src/engine/entity/Loc.ts
- src/engine/entity/NetworkPlayer.ts
- src/engine/script/handlers/LocOps.ts
- src/engine/zone/Zone.ts
Our implementation is slightly incorrect. We perform way too many `loc_del` packets than what Jagex does.
1. `loc_change` will only send the `loc_add` packet. We currently send a `loc_del` -> `loc_add`.
2. Our current implementation actually sends 2 `loc_del` packets in some cases with temporary locs (like doors).
3. If a temporary loc is currently replacing a permanent loc, then we should only send the `loc_add` packet. We currently send a `loc_del` -> `loc_add`.
4. The only time a `loc_del` is actually used, is when there are no temporary locs in place of a permanent one.
5. Loc events are sent before the obj events.
6. I was not able to send a `partial enclosed` packet with a `full follows` one on osrs. `full follows` and `partial follows` are only written with new zones in view. …
> fix(engine): corrections to zones implementation

- data/src/scripts/quests/quest_hero/scripts/locs/brimhaven_scarface_mansion.rs2
https://youtu.be/O-GstkQpa7M?t=90
video shows mesbox is closed, and confirms that the player is delayed while summonign grip (clicked to walk, but didn't move)
> fix(content): heroes - close mesbox when summoning grip

- data/src/scripts/quests/quest_desertrescue/scripts/captain_siad.rs2
- data/src/scripts/quests/quest_desertrescue/scripts/mercenary.rs2
- data/src/scripts/quests/quest_desertrescue/scripts/quest_desertrescue.rs2
- add missing dialogue to retrieve bet from mercenaries after defeating the captain during desertrescue, also fix a couple mistakes in the mercenary dialogue
- don't show op for sailing if you haven't searched the bookcase when talking to siad
> fix(content): desertrescue retrieving bet, siad dialogue fix

- src/engine/entity/Player.ts
- src/network/rs225/client/handler/InvButtonDHandler.ts
In osrs it used to be possible to drag an item after equipping or dropping it.
> fix(engine): Allow dragging empty inventory slot

- data/src/scripts/drop tables/scripts/hobgoblin.rs2
https://oldschool.runescape.wiki/w/Hobgoblin#Armed_hobgoblin_drops
> fix(content): level 42 hobgoblin drop table

- Dockerfile
-Docker does not bind the volume at build-time, only at runtime, resulting in /app directory being empty
-Replaced VOLUME with COPY to build the Dockerfile
-The volume is still mounted at runtime by docker-compose
Split effort by myself and iPsych0
> fix: Updated Dockerfile - would not find json - /app empty

- data/src/scripts/skill_combat/scripts/pvp/pk_skull.rs2
https://oldschool.runescape.wiki/w/Update:Grand_Exchange_Tax_%26_Item_Sink I misunderstood this blogpost at the time. The skull would only not reset if the target wasnt new (u being within the last 2 players they attacked, and them being within the last 3 players you attacked)
> fix(content): reset current skull on attack if target is new

- src/engine/entity/tracking/InputTracking.ts
- Small typo that's causing a linting error.
> fix(engine): Fixing typo in input tracking file

- data/src/scripts/skill_mining/scripts/mining.rs2
The p_delay(0) was added to most rocks in june 2004. Apart of this update: https://oldschool.runescape.wiki/w/Update:Special_Attacks
`The new RuneScape launch inadventantly made it harder to gain resources from these in competative situations (where two or more people are trying to get the resource at once), since only one person could ever get the resource at a time. We have now fixed it back to the old behaviour where if both people are successful at the exact same instant, they will both get the resource.`
> fix(content): remove p_delay on success for most rocks

- data/src/scripts/skill_firemaking/scripts/firemaking.rs2
https://github.com/user-attachments/assets/bc3e663a-73a9-4f75-a397-bb4d503d8300
Removed the stall to match osrs behavior
> fix(content): Firemaking no longer delays the player if they are on an adjacent tile

- data/src/scripts/login_logout/login.rs2
- data/src/scripts/player/scripts/stat.rs2
- data/src/scripts/skill_prayer/scripts/prayers/rapidheal.rs2
- data/src/scripts/skill_prayer/scripts/prayers/rapidrestore.rs2
From this [blog post](https://oldschool.runescape.wiki/w/Update:Game_Engine_Update):
`Over time, if your stats have been reduced or raised, most of them restore slowly back towards their default levels. However, if you opened an interface such as one of the skill guides or a shop, your stats used to stop restoring until you closed it again. We've now fixed it so that your stats will restore normally even if you have an interface open.`
> fix(content): change regen softtimer to timer

- data/src/scripts/npc/scripts/shadow_spider.rs2
- data/src/scripts/quests/quest_arthur/scripts/sir_mordred.rs2
- data/src/scripts/quests/quest_demon/scripts/delrith.rs2
- data/src/scripts/quests/quest_grail/scripts/black_knight_titan.rs2
- data/src/scripts/quests/quest_mcannon/scripts/cannon.rs2
- data/src/scripts/quests/quest_vampire/scripts/count_draynor.rs2
- data/src/scripts/skill_combat/scripts/npc/npc_combat.rs2
- data/src/scripts/skill_combat/scripts/player/player_combat.rs2
- data/src/scripts/skill_combat/scripts/player/player_magic.rs2
- data/src/scripts/skill_combat/scripts/player/player_melee.rs2
- data/src/scripts/skill_combat/scripts/player/player_ranged.rs2
- data/src/scripts/skill_combat/scripts/pvp/pvp_combat.rs2
- data/src/scripts/skill_combat/scripts/pvp/pvp_magic.rs2
- data/src/scripts/skill_combat/scripts/pvp/pvp_ranged.rs2
- refactors some combat scripts
- remove custom opnpc2 and apnpc2 triggers for count draynor and delrith. Move these to ~npc_is_attackable to allow p_aprange calculations to run.
- removes 0 hp check for magic and cannoning (these dont exist in osrs!)
- adds cannon quest req to place cannons
- heal black knight titan and sir mordred from their death instead of being attacked at 0 hp
- shadow spiders drain prayer when they *retaliate*
- reset autocast when out of runes, if trying to attack with your autocast spell (matches osrs)
- move garlic behavior to count count draynor's attack script and *retaliate* script
> fix(content): handle special npc's better in combat, and other combat refactors

- src/engine/script/handlers/InvOps.ts
Instead of one log entry per individual item, condense all equal items into a single entry. This reduces server database load.
Applies to both `BOTH_MOVEINV` and `INV_DROPALL`.
> fix(engine): de-duplicate wealth log entries

- data/src/scripts/skill_combat/scripts/npc/npc_poison.rs2
- src/engine/World.ts
- src/engine/entity/Npc.ts
- src/network/rs225/server/codec/NpcInfoEncoder.ts
- tools/pack/config/HuntConfig.ts
This pull request changes a significant amount of Npc behavior and mechanics to more accurately model the rs2 engine
- Hunts for Npcs have been significantly reworked
- Hunt delay is processed during the Npc's turn, and is better handled in general
- findnewmode now runs the `ai_queue` script immediately rather than adding it to the Npc's queue
- If `findkeephunting` is no, then the Npc will disable its huntmode after consuming a hunt target
- `Npc.defaultMode()` does a better job of resetting the Npc's relevant hunt variables
- findnobodynear=no now checks if Npc is rendered by any player before allowing a hunt
- Npc pathing and interactions is a bit different
- Interaction order has corrected
- More robust logic for handling Npc walktrigger
- `Npc.defaultMode()` no longer tries to path …
> fix(engine): Npc timers, hunts, and interactions/movement have been significantly reworked to better match rs2 engine

- src/engine/World.ts
- src/engine/entity/PathingEntity.ts
Currently, the engine converts a 1/2 tile teleport op to a walk/run, this is incorrect as the client will already convert any <= 2 teleport into a walk anyways if it's not a jump (https://github.com/2004Scape/Client/blob/67f5eda79588149043170088a53465fe3b00aa1a/client/src/main/java/client.java#L10278
This matches OSRS 1, see the p_teleport used here: https://youtu.be/FPNmOhs8jdw?si=K-5L2oh6J3OLuIjs&t=602
Previous:
https://github.com/user-attachments/assets/c786ebb8-b496-488d-8c99-dcb25527ae50
After change:
https://github.com/user-attachments/assets/87dbbfc5-4b19-4103-a26e-1327b07bfdc3
> fix(engine): don't convert teleport op to walk/run

- data/src/scripts/quests/quest_sheepherder/scripts/npcs/diseased_sheep.rs2
Fixed typo when sheep are herded into enclosure.
https://youtu.be/SrPeQHoiI0o?si=x50Pp2ipgc84w67n&t=652 - RSC version (Granted it was not uploaded around RSC time, but still fairly old)
https://youtu.be/fzoxDrN3W4w?si=_CEY5FQorTJ_qi3w&t=247 - OSRS
I can't imagine it'd have changed from 'enclosure' to 'inclosure' for a short period of time, hence this PR.
> fix(content): Sheep Herder typo fixed

- src/engine/World.ts
- src/network/rs225/server/codec/NpcInfoEncoder.ts
Error in logic was causing some Npcs to try to hunt players even when no one is in the area. This should save a bit of processing power
> fix(engine): Prevent Npcs from searching for Players when no one is around

- data/src/scripts/areas/area_combat_training/scripts/combat_training_camp.rs2
- data/src/scripts/areas/area_varrock/scripts/attack_dummy.rs2
- data/src/scripts/quests/quest_chompybird/scripts/chompy_bird.rs2
- data/src/scripts/quests/quest_mcannon/scripts/cannon.rs2
- data/src/scripts/skill_combat/scripts/player/player_magic.rs2
- data/src/scripts/skill_combat/scripts/player/player_melee.rs2
- data/src/scripts/skill_combat/scripts/player/player_ranged.rs2
- data/src/scripts/skill_combat/scripts/pvp/pvp_magic.rs2
- data/src/scripts/skill_combat/scripts/pvp/pvp_melee.rs2
- data/src/scripts/skill_combat/scripts/pvp/pvp_ranged.rs2
- data/src/scripts/tutorial/scripts/skills/tut_player_magic.rs2
Fairly certain they only need to be calculated on stat change and equipment change. I think there were also some osrs bugs related to this at some point with new weaponry?
Should also help with server tick speed :)
> refactor(content): only call ~player_combat_stat on stat change and equipment change

- view/client.ejs
- Mobile device to reset canvas to default (1x) and show hidden controls on reload/refresh. Desktop remains as is, respecting all localStorage settings, including unhide controls & canvas size.
- When accessing live server or local client direct via mobile device and controls are hidden, there is no easy way to unhide controls without manually clearing localStorage. Canvas can be hard to change if raised > than 1x when embedded vs direct - a refresh allows reset to 1x - mobile only.
- Made 'ctrl+alt+i' ' / 'unhide controls' key-combo more universal for apple keyboards, as well as non-English keyboards. 
- Example: acute i was registering on a user debug and not sending to client.
- fix - look for e.code and not e.key, avoids clashing with non-US keyboards and also covers if caps lock is …
> fix(client): Mobile improvements for controls & canvas reset | unhide controls adjusted to support apple & non-US inputs 

- data/src/scripts/quests/quest_chompybird/scripts/chompy_bird.rs2
- data/src/scripts/quests/quest_mcannon/scripts/cannon.rs2
- data/src/scripts/skill_combat/scripts/npc/npc_combat.rs2
- data/src/scripts/skill_combat/scripts/player/player_magic.rs2
- data/src/scripts/skill_combat/scripts/player/player_melee.rs2
- data/src/scripts/skill_combat/scripts/player/player_ranged.rs2
- data/src/scripts/skill_combat/scripts/pvp/pvp_combat.rs2
- data/src/scripts/skill_combat/scripts/pvp/pvp_melee.rs2
- data/src/scripts/skill_combat/scripts/pvp/pvp_ranged.rs2
- Npc's can no longer tick heal incoming damage, with the exception of ring of recoil damage. However, xp gained and kill credit should still use the capped damage.
From [Video](https://gyazo.com/529a4cbcb261e758c9a4b9764c8a68dc):
- Kill credit will now only update on successful hit
- Also fixes #1403
> fix(content): prevent npcs from tick healing non-recoil damage

- data/src/scripts/skill_combat/scripts/player/player_magic.rs2
- data/src/scripts/skill_combat/scripts/pvp/pvp_magic.rs2
Sources in comments don't have the typo.
> fix(content): Typo in magic message

- data/src/scripts/areas/area_ardougne_east/scripts/captain_barnaby.rs2
- data/src/scripts/areas/area_falador/scripts/squire.rs2
- data/src/scripts/areas/area_port_sarim/scripts/sailors.rs2
- data/src/scripts/areas/area_port_sarim/scripts/thurgo.rs2
- data/src/scripts/areas/area_varrock/scripts/reldo.rs2
- data/src/scripts/areas/areas_heroes_guild/scripts/achietties.rs2
- data/src/scripts/minigames/game_ranging/scripts/ranging_guild_door.rs2
- data/src/scripts/minigames/game_trail/scripts/trail_clue_read.rs2
- data/src/scripts/quests/quest_haunted/scripts/quest_haunted.rs2
- data/src/scripts/quests/quest_squire/configs/quest_squire.constant
- data/src/scripts/quests/quest_squire/scripts/quest_squire.rs2
- lower clue scroll split_init
- add dialogue case for crandor to barnaby
- add some missing dialogue to achietties
- fix mesanims in knight's sword, correct + add some missing dialogue, change quest stages to use constants
- change some 2 tile forcemove doors to use p_teleport instead
> fix(content): knights sword dialogue, clue split_init, and some doors

- src/engine/entity/HeroPoints.ts
- src/engine/script/handlers/NpcOps.ts
- src/engine/script/handlers/PlayerOps.ts
- src/util/QuickSort.ts
Three big things accomplished in this PR:
- Kill credit now uses a quicksort that matches RuneScape's implementation. This is minor but the specific sort method affects tie breaker calculations
- Heropoints now uses a player's unique hash64, rather than a UID which is assigned on login. This allows heropoints to persist between login sessions
- Heropoint additions of 0 are denied from taking up a slot in the size-16 Array. In OSRS they introduced custom functionality to maintain a slot with 0 heropoints after Ironman mode came out, but we don't need to worry about that
> fix(engine): Npc kill credit is now determined more appropriately and will persist between login sessions

- data/src/scripts/_unpack/all.npc
- data/src/scripts/areas/area_draynor/scripts/witch.rs2
From [archived magazine](https://archive.org/details/PCPowerplay-101-2004-07/page/n13/mode/2up?q=runescape):
The witch has the same combat level as dark wizards and the screenshot shows she uses weaken, so I assume she's very similar to dark wizards. 
In rsc and from [runehq](https://web.archive.org/web/20040813232041/http://runehq.com/viewMonster.php?id=34) she drops nothing. 
One potential todo though is that runehq says she can spawn in the middle of the wilderness 👀
> feat(content): witch in draynor manor uses magic now to match old screenshot

- src/engine/entity/Player.ts
Timers now schedule against the mapclock rather than using a decrement. This gives more consistent behavior and better replicates rs2 behavior
> fix(engine): Player timers now schedule more accurately

- prisma/multiworld/migrations/20250304021857_add_reviewed_column_to_report/migration.sql
- prisma/multiworld/schema.prisma
- prisma/singleworld/migrations/20250304021849_add_reviewed_column_to_report/migration.sql
- prisma/singleworld/schema.prisma
- src/db/types.ts
Adds a new `reviewed` column to the `report` table to track whether a report has been reviewed.
- Added `reviewed BOOLEAN NOT NULL DEFAULT FALSE` to the `report` model in Prisma schema.
- Generated and included the necessary Prisma migrations.
> feat(engine): Report review migrations

- data/src/scripts/_unpack/all.loc
- data/src/scripts/skill_woodcutting/scripts/old_woodcut.rs2
We have no idea how this tree is supposed to work since it has no op3. It was removed in rev 270 (Nov 2004)
> fix(content): A particular dead tree would display "Nothing interesting happens."

- src/engine/entity/Player.ts
Will make the session log about reaching 250 total, even if you were to go from 249 to 251 total in one tick
> fix(logging): log milestone total levels even if gaining multiple lvls

- data/src/scripts/macro events/scripts/general/macro_event_genie.rs2
- data/src/scripts/macro events/scripts/general/macro_event_mysterious_old_man.rs2
Since mysterious old man has the same dialogue here as genie, its safe to assume that they have the same 'no target' dialogue.
- Talking to a mysterious old man that isnt yours, from [video](https://youtu.be/U_TRFGTfIY0?t=276):
- Talking to a genie that isnt yours *and* talking to a genie that cant find it's target, from [video](https://youtu.be/qNQYgiNMBes?t=134):
> fix(content): Genie and mysterious old man were missing special dialogue

- data/src/scripts/engine.rs2
Moves the format of the info tagging to the standardized way the vscode extension expects it to be, rather than hardcoding special case for `engine.rs2`
Want to keep unmerged until new plugin version 0.2.0+ is released for a while
Current version of plugin will work with this, with caveat of showing the "info:" tag
New version of the plugin will work with this, and backwards compatible with the current live version of `engine.rs2`, but that compatibility will be removed in the future, no special handling for any specific file.
> chore(content): add more engine command info

- data/src/scripts/skill_combat/scripts/player/player_magic.rs2
- data/src/scripts/skill_combat/scripts/pvp/pvp_combat.rs2
- data/src/scripts/skill_combat/scripts/pvp/pvp_magic.rs2
- data/src/scripts/tutorial/scripts/skills/tut_player_magic.rs2
- wrongfully writing to %damagestyle
- Also removes the arbitrary weapon staff check for defensive magic casting. In 2006-2007, they reworked the defensive cast entirely by integrating it into autocast. So by design, they *require* autocast for defensive cast to work. Our defensive casting is separate from autocast, hence why the weapon staff check makes no sense to me.
> fix(content): ranged combat fix

- data/src/scripts/areas/area_alkharid/scripts/gem_trader.rs2
- data/src/scripts/areas/area_falador/scripts/sir_amik_varze.rs2
- data/src/scripts/areas/area_port_sarim/scripts/monk_of_entrana.rs2
- data/src/scripts/areas/area_varrock/scripts/fancy_dress_shop_owner.rs2
- data/src/scripts/player/scripts/death.rs2
- data/src/scripts/quests/quest_crest/scripts/crest_boot.rs2
- data/src/scripts/quests/quest_crest/scripts/crest_caleb.rs2
- data/src/scripts/quests/quest_crest/scripts/crest_chronozon.rs2
- data/src/scripts/quests/quest_crest/scripts/crest_dimintheis.rs2
- data/src/scripts/quests/quest_crest/scripts/crest_johnathon.rs2
- data/src/scripts/quests/quest_crest/scripts/crest_man.rs2
- data/src/scripts/quests/quest_crest/scripts/quest_crest.rs2
- data/src/scripts/quests/quest_scorpcatcher/scripts/quest_scorpcatcher.rs2
- data/src/scripts/quests/quest_sheepherder/scripts/npcs/councillor_halgrive.rs2
- data/src/scripts/quests/quest_sheepherder/scripts/npcs/doctor_orbon.rs2
- data/src/scripts/skill_herblore/scripts/brewing/brew_potion.rs2
- data/src/scripts/skill_magic/scripts/spells/teleport.rs2
- Changes to family crest:
- Fix some mesanims/dialogue, add a couple missing interactions with using crest
- Change Chronozon crest shield drop to happen before death seq, remove heropoints req
- Change Johnathon script to only accept standard antipoison
- Reset var used for the quest after completion as the lever puzzle and chronozons state will reset
- Fix incorrect check order when teleporting with ana in a barrel
- change level req mesbox used for blamish oil during heros quest
- fix some incorrect mesanims in various quests
- add members restriction to dimintheis and the fancy clothes shop
> fix(content): family crest changes, more members restrictions, and anainabarrelfix

- data/src/scripts/skill_combat/scripts/combat.rs2
- data/src/scripts/skill_combat/scripts/npc/npc_combat.rs2
- data/src/scripts/skill_combat/scripts/npc/npc_combat_magic.rs2
- data/src/scripts/skill_combat/scripts/npc/npc_combat_melee.rs2
- data/src/scripts/skill_combat/scripts/npc/npc_combat_ranged.rs2
- data/src/scripts/skill_combat/scripts/player/player_combat_stat.rs2
Separation of 'style bonus' and +8 from ~combat_effective_stat, makes it easier to implement void in the future... Restructuring it in a way where style bonuses are applied at the end prevents us from having to -8 to $effective magic and $effective_defence, for effective magic defence.
Our previous effective magic defence would double floor since we used `scale()`. Now the question is, did jagex implement the 30/70 split like: 
`divide(add(multiply(7, $effective_magic), multiply(3, $effective_defence)), 10);` 
or 
`add(scale(3, 10, $effective_defence), scale(7, 10, $effective_magic));`
My guess is *without* `scale()`. this will only have very minor differences
> fix(content): Fix double flooring for magic defence formula

- src/server/login/LoginServer.ts
If a server is ran with `Environment.WEBSITE_REGISTRATION` **disabled**, meaning that users can login with any credentials and have an account created, there will be some SQL errors because the response from LoginServer.ts is missing the `account_id` property. Fix this by returning the primary key inserted for the new account.
> fix(engine): prevent sql errors on new user login

- data/src/scripts/quests/quest_itgronigen/scripts/quest_itgronigen.rs2
- data/src/scripts/tutorial/scripts/tut_doors_and_gates.rs2
- src/engine/zone/Zone.ts
This PR adds some safety at the engine level for iterating through Locs and Objs, so that our cursor doesn't get lost if we remove Locs and Objs while iterating. This matches our queue behavior
Also, in runescript some logic for a gate has been improved in response to a bug reported here: https://discord.com/channels/953326730632904844/1349358765878804561
> fix(content): Several doors and gates have been reworked to match a recent engine change

- src/engine/World.ts
- src/network/client/model/ReportAbuse.ts
- src/network/rs225/client/handler/ReportAbuseHandler.ts
Automatically and immediately start tracking a player's inputs if they are reported for either macroing or abusing a bug.
Also improves types for the ReportAbuse ClientProt.
> feat(engine): enable tracking on macro/bug-abuse reports

- data/src/pack/varp.pack
- data/src/scripts/_unpack/all.varp
- data/src/scripts/areas/area_yanille/scripts/agility_dungeon.rs2
- data/src/scripts/login_logout/login.rs2
- data/src/scripts/login_logout/logout.rs2
- data/src/scripts/macro events/scripts/thieving/macro_event_poisonous_gas.rs2
- data/src/scripts/player/scripts/consumption/effects/scripts/anti_poison.rs2
- data/src/scripts/player/scripts/consumption/effects/scripts/strange_fruit.rs2
- data/src/scripts/skill_combat/scripts/poison.rs2
Reworked poison to work more authentically. Instead of there being 2 variables, %poison and %antipoison, there is just one variable, %poison. This variable is negative if the player has poison immunity, and positive if the player is poisoned. In addition, added poison immunity to strange fruit to work as described by Ash https://archive.is/6SmRo.
> fix(poison): Reworked player poison implementation

- data/src/scripts/quests/quest_itwatchtower/scripts/enclave_guard.rs2
Change enclave guard behavior to match OSRS instead of RSC, which allows access to the ogre enclave after completion of watch tower (matches 2005/2006 posts)
> fix(content): allow access to the ogre enclave after quest completion

- data/src/scripts/_unpack/all.varp
- data/src/scripts/interface_controls/configs/player_controls.varp
- data/src/scripts/interface_controls/scripts/player_controls.rs2
- data/src/scripts/interface_options/scripts/game_options.rs2
- data/src/scripts/interface_options/scripts/game_options_ld.rs2
- data/src/scripts/skill_combat/scripts/player/player_attackstyles.rs2
- data/src/scripts/skill_combat/scripts/player/player_magic.rs2
- data/src/scripts/skill_prayer/scripts/prayer.rs2
- data/src/scripts/skill_prayer/scripts/prayers/clarity.rs2
- data/src/scripts/skill_prayer/scripts/prayers/improvedreflexes.rs2
- data/src/scripts/skill_prayer/scripts/prayers/incrediblereflexes.rs2
- data/src/scripts/skill_prayer/scripts/prayers/protectfrommagic.rs2
- data/src/scripts/skill_prayer/scripts/prayers/protectfrommelee.rs2
- data/src/scripts/skill_prayer/scripts/prayers/protectfrommissiles.rs2
- data/src/scripts/skill_prayer/scripts/prayers/protectitems.rs2
- data/src/scripts/skill_prayer/scripts/prayers/rapidheal.rs2
- data/src/scripts/skill_prayer/scripts/prayers/rapidrestore.rs2
- data/src/scripts/skill_prayer/scripts/prayers/rockskin.rs2
- data/src/scripts/skill_prayer/scripts/prayers/steelskin.rs2
- data/src/scripts/skill_prayer/scripts/prayers/strengthburst.rs2
- data/src/scripts/skill_prayer/scripts/prayers/superhumanstrength.rs2
- data/src/scripts/skill_prayer/scripts/prayers/thickskin.rs2
- data/src/scripts/skill_prayer/scripts/prayers/ultimatestrength.rs2
- data/src/scripts/tutorial/scripts/tut_chatbox_steps.rs2
- src/engine/script/ScriptOpcodePointers.ts
- src/engine/script/handlers/PlayerOps.ts
- settings will now close interfaces (and disrupt future weakqueues) to match: https://youtu.be/neAoU0yiGFY?t=98
- Prayers, attack styles, run/walk, and auto retaliate buttons no longer queue if delayed to match:
- Various buttons now clears interactions:
> fix(content): settings will now close interfaces and player controls no longer queue if the player is delayed

- src/engine/script/handlers/CoreOps.ts
- Fixes `pop_varn` was popping a number instead of a string for varn type string.
- Simplify the command impls and to no longer need the forced `!` in the code.
> fix(engine): pop_varn command & cleanup

- data/src/scripts/areas/area_ardougne_east/configs/ardougne_east.inv
- data/src/scripts/areas/area_taverly/configs/taverly.inv
The shop stacks of the shops changed here now match the early 2006.
but I don't know if the stacks were the same in 2004 or 2005.
because the shops stacks are significantly different compared to the runescape classic.
> fix(content): Shop changes

- prisma/multiworld/migrations/20250314194454_remove_input_report_event_table/migration.sql
- prisma/multiworld/schema.prisma
- prisma/singleworld/migrations/20250314194559_remove_input_report_event_table/migration.sql
- prisma/singleworld/schema.prisma
- src/db/types.ts
Switching to raw input_report_events has proven the better play, and the older data is no longer needed at this point.
> chore(db): remove unused database table, low priority

- data/src/scripts/_test/scripts/cheats/cheat_zone.rs2
- src/engine/World.ts
Very small fix that should have been addressed in the last PR
```
[debugproc,loc_del_change]
if (p_finduid(uid) = true) {
p_telejump(0_37_55_32_30);
p_delay(0);
loc_add(0_37_55_32_30, loc_1276, 0, centrepiece_straight, 10);
p_delay(0);
loc_del(100);
p_delay(0);
loc_change(loc_2732, 10);
}
```
Adding a static loc, deleting it, and then changing it would bring it back to life before this PR. This is an issue because a dynamic loc gets removed from the Zone when deleting (unlike a static Loc). Now, the `loc_change` just gets discarded via an early return 🤷
> fix(engine): Added extra logic to safeguard devs from resurrecting stale Locs 

- src/engine/script/handlers/NpcOps.ts
- src/engine/script/handlers/PlayerOps.ts
Implementation for stat drains seems to be incorrect.
Zammy flames drains one more point than expected
osrs: https://imgur.com/a/ci5dbP0
pre-fix: https://imgur.com/a/zFv737U
npc reduction: https://imgur.com/a/QbuS8x4
> fix(engine): Truncate statsub percentage calculations

- eslint.config.js
- src/db/query.ts
- src/engine/World.ts
- src/engine/entity/NonPathingEntity.ts
- src/engine/entity/Player.ts
- src/engine/script/handlers/LocOps.ts
- src/engine/zone/Zone.ts
- src/server/friend/FriendServer.ts
Hey, I saw some lint warnings on pull requests and noticed this TODO in the `eslint.config.js`.
In a handful of places, we have caught errors with the variable name `_`, but the config wasn't set to ignore those. It will ignore them now.
The most interesting change is in `src/db/query.ts`. `dialect` was getting defined but going unused. Meanwhile a separate, inline `dialect` was getting defined. Their definitions appeared identical, so I removed the duplication to satisfy eslint.
I set `no-case-declarations` and `@typescript-eslint/no-namespace` to `error` as well. No code changes were needed.
--
I have prettier configured to format files on save in my editor, but in that same `src/db/query.ts`, there's some formatting that prettier was modifying. I didn't check those changes in because …
> fix(config): set no-unused-vars to error

- src/engine/World.ts
- src/engine/entity/Player.ts
- src/engine/entity/tracking/InputEvent.ts
- src/engine/entity/tracking/InputTracking.ts
- src/network/rs225/client/handler/EventTrackingHandler.ts
- src/server/logger/LoggerClient.ts
- src/server/logger/LoggerServer.ts
- src/server/logger/LoggerThread.ts
Current code has a bug where it does not properly wait for the client data to be sent after tracking ends. It was supposed to wait a number of ticks for the client to send this. As a result, we are often discarding some input tracking data from the client.
```
if (this.waitingForLastReport) {
if (this.endTrackingAt + InputTracking.FINAL_REPORT_TIME_LEEWAY >
World.currentTick) {
// Finalize tracking
}
}
```
This will not wait the intended duration before finalizing the tracking session as the logic is wrong. `endTrackingAt+16` will always be greater than `World.currentTick`. So if a client took more than 1 tick to send its input tracking bundle it would be discarded.
Issue can be reproduced by delaying the FinishTracking ClientProt by a tick, or modifying client to wait an extra tick …
> fix(engine): input tracking bugfix

- tools/pack/map/Worldmap.ts
I don't have all of the context here, but I saw this csv processing going on and there's a bunch of duplicate code. I extracted the duplicate code into a function called `processCsv`.
I can improve these names if you think there's something better!
> refactor: extract processCsv to reduce duplicate code

- src/engine/zone/Zone.ts
- src/util/LinkList.ts
Two primary things here
```typescript
...
private readonly players: LinkList<Player> = new LinkList();
private readonly npcs: LinkList<Npc> = new LinkList(); 
private readonly locs: LinkList<Loc> = new LinkList();
private readonly objs: LinkList<Obj> = new LinkList();
...
```
All of our zone data structures now match! :) Using LinkedLists for Npcs and Players achieves a few things, but namely it's very quick to remove items from the collection and Npcs and Players need to be removed from the collection very often
Further, I tossed a generator iterator into our LinkList implementation
```typescript
*all(reverse = false): IterableIterator<T> {
if (reverse) {
for (let link = this.tail(); link !== null; link = this.prev()) {
const save = this.cursor;
yield link;
this.cursor = save;
}
} else { …
```
> fix(engine): Zones now track Npcs and Players with a more robust data structure

- data/src/scripts/areas/area_gnome/scripts/spirit_tree.rs2
- data/src/scripts/minigames/game_trail/scripts/hard/zamorak_wizard.rs2
- data/src/scripts/quests/quest_grandtree/scripts/grandtree_black_demon.rs2
- data/src/scripts/skill_woodcutting/configs/trees/burnt.loc
- break plague sample when travelling via spirit tree (RSC behavior)
- switch category on charcoal trees
- update clue/grandtree var before death seq (matches OSRS)
> fix(content): spirit tree plague sample, charcoal tree, update zamorak wizard/black demon vars earlier

- data/src/scripts/general/scripts/invs.rs2
- data/src/scripts/interface_bank/scripts/bank.rs2
- data/src/scripts/minigames/game_partyroom/scripts/partyroom.rs2
- data/src/scripts/minigames/game_partyroom/scripts/partyroom_chest.rs2
- change main inv space checks to match OSRS (check itemspace per obj being added rather than using inv_freespace)
- account for empty slots when getting a random slot (this way, items near the end of the chest won't get stuck there if there are empty slots)
- reorganize partyroom inv as items are removed (most of the time), matches https://youtu.be/Ve5UF8B3BMw?si=NKO9H7bd6rJGY_LF&t=251
> fix(content): more partyroom changes

- src/engine/World.ts
- src/engine/entity/BuildArea.ts
- src/engine/entity/Entity.ts
- src/engine/script/handlers/ServerOps.ts
- src/engine/zone/Zone.ts
- src/network/rs225/server/codec/NpcInfoEncoder.ts
- src/network/rs225/server/codec/PlayerInfoEncoder.ts
Basically I removed `Entity.checkLifecycle` because it's supposed to do exactly what the `isActive` variable does except it does it less directly
I need this to be done because I am going to completely rewrite how entity lifecycles work in a way that we can no longer use it to check stuff like this
@ultraviolet-jordan These changes need to be reflected in rsbuf at some point. Instead of passing in the lifecycle variable we should just pass in `isActive` and check against that, like we are doing in this PR
I went through and tested killing npcs, changing npcs, picking up static objs, dropping dynamic ones, spawning dynamic locs, and relogging while doing all of this. Behavior should be entirely unchanged, since `isActive` and `checkLifecycle` aim to measure the same thing about an Entity
> fix(engine): The engine now more directly checks if an entity is active, rather than inferring it indirectly

- data/src/scripts/quests/quest_biohazard/scripts/chancy.rs2
- data/src/scripts/quests/quest_biohazard/scripts/hops.rs2
- data/src/scripts/skill_magic/scripts/spells/telegrab.rs2
- clear bits instead of setting them when talking to chancy/hops in varrock with the wrong vials given
- remove telegrab restriction on the plague items
> fix(content): biohazard vials

- data/src/scripts/_test/scripts/cheats/cheat_trawler.rs2
- data/src/scripts/_unpack/all.varn
- data/src/scripts/login_logout/login.rs2
- data/src/scripts/minigames/game_trawler/configs/trawler.constant
- data/src/scripts/minigames/game_trawler/configs/trawler.dbrow
- data/src/scripts/minigames/game_trawler/configs/trawler.npc
- data/src/scripts/minigames/game_trawler/scripts/trawler.rs2
- data/src/scripts/minigames/game_trawler/scripts/trawler_control.rs2
- data/src/scripts/minigames/game_trawler/scripts/trawler_flood.rs2
- data/src/scripts/minigames/game_trawler/scripts/trawler_gangplank.rs2
- data/src/scripts/minigames/game_trawler/scripts/trawler_net.rs2
- data/src/scripts/minigames/game_trawler/scripts/trawler_sink.rs2
- data/src/scripts/minigames/game_trawler/scripts/trawler_start.rs2
- data/src/scripts/minigames/game_trawler/scripts/trawler_win.rs2
- data/src/scripts/player/scripts/appearance.rs2
Has old trawler commits cuz i forgor to make a new branch...
Turns out there were two main issues with trawler:
- map_playercount command doesnt support two coords with different levels, so I just changed the trawler dbrow
- Timers werent defined in the npc config for murphy... So if murphy went through defaultMode it'd remove the timer
some other fixes:
- Trawler locs were resetting immediately on trawler win/lose  - this doesnt match old videos
- Cam reset would be called every time you equipped an item
- Trawler was started too early, every vid ive seen has it start 17 ticks (10s) after the sailing interface.
- Only full trawler leaks were reset between trawler games, fixed leaks are only reset naturally (after 10 minutes)
- Old videos show that theres no opu trigger for fixed/non …
> fix(content): trawler rewrite

- data/src/scripts/_test/scripts/cheats/cheat_interactions.rs2
- data/src/scripts/_test/scripts/cheats/cheat_npc.rs2
- data/src/scripts/areas/area_draynor/scripts/prince_ali.rs2
- data/src/scripts/areas/area_mage_arena/scripts/kolodion_fight.rs2
- data/src/scripts/engine.rs2
- data/src/scripts/general/scripts/flavour_text/sheep.rs2
- data/src/scripts/general_use/scripts/shear_sheep.rs2
- data/src/scripts/macro events/scripts/fishing/macro_event_big_fish.rs2
- data/src/scripts/macro events/scripts/fishing/macro_event_whirlpool.rs2
- data/src/scripts/macro events/scripts/general/macro_event_triffid.rs2
- data/src/scripts/minigames/game_gnomeball/scripts/gnome_baller.rs2
- data/src/scripts/minigames/game_gnomeball/scripts/gnome_winger.rs2
- data/src/scripts/minigames/game_gnomeball/scripts/gnomeball.rs2
- data/src/scripts/quests/quest_arthur/scripts/beggar.rs2
- data/src/scripts/quests/quest_demon/scripts/delrith.rs2
- data/src/scripts/quests/quest_desertrescue/scripts/mining_slave.rs2
- data/src/scripts/quests/quest_fluffs/scripts/pet.rs2
- data/src/scripts/quests/quest_haunted/scripts/quest_haunted.rs2
- data/src/scripts/quests/quest_prince/scripts/quest_prince.rs2
- src/engine/World.ts
- src/engine/entity/Loc.ts
- src/engine/entity/Npc.ts
- src/engine/script/handlers/NpcOps.ts
- src/engine/zone/Zone.ts
Before we were having to manually revert Npcs after changing their type
Now, `npc_changetype(Npc type, int duration)` takes in a `duration` and the engine will handle reverting the Npc after the duration has elapsed
I've gone ahead and filled all the examples in runescript of the command with a placeholder `^max_32bit_int`, so the feature is dormant for the time being
> fix(engine): After changing type, Npcs will now revert themselves automatically

- prisma/multiworld/migrations/20250322112523_2fa/migration.sql
- prisma/multiworld/schema.prisma
- prisma/singleworld/migrations/20250322112532_2fa/migration.sql
- prisma/singleworld/schema.prisma
- src/db/types.ts
This only contains raw database schema changes to support account-based 2FA.
> feat(security): add 2fa schema changes

- view/client.ejs
If you toggled auto client sizing on, then clicked 2x or 3x sizing, the max width style would mean that the client width is much smaller than it should be.
Thanks to @Collin-M for bringing this to my attention. Their image below for reference.
Fix is just to clear the max width when the sizing changes.
No changes needed for fullscreen mode.
> fix(client): Auto sizing client conflicting with 2x and 3x sizes

- data/src/scripts/areas/area_ardougne_west/configs/doors.loc
- data/src/scripts/areas/area_ardougne_west/scripts/doors.rs2
- data/src/scripts/quests/quest_elena/scripts/alrena.rs2
- data/src/scripts/quests/quest_upass/configs/quest_upass.vars
- data/src/scripts/quests/quest_upass/scripts/upass_obstacles.rs2
- data/src/scripts/skill_agility/scripts/barbarian_course.rs2
- data/src/scripts/skill_agility/scripts/shortcuts.rs2
- data/src/scripts/skill_agility/scripts/wilderness_course.rs2
- Fixed Alrena missing dialogue on `^quest_elena_gasmask` stage
- changed mourner HQ to not call loc_param for doors through dialogue
- fixed check for rope swing in underground pass, also removed the additional 1t delay rope swings had before usage when starting standing next to them
- blocked usage of the grate pipe in underground pass when someone else is in it
> fix(content): fixes to plague series quests, rope swings

- data/src/scripts/quests/quest_itgronigen/scripts/quest_itgronigen.rs2
https://classic.runescape.wiki/w/Observatory_quest
https://oldschool.runescape.wiki/w/Observatory_Quest/Quick_guide
both wikis show an uncut sapphire as a reward for observatory quest
https://github.com/2004Scape/Server/issues/1527 issue posted here
> fix(content): observatory quest reward was missing sapphire

- data/src/scripts/areas/area_alkharid/configs/shantay_pass.loc
- data/src/scripts/areas/area_alkharid/scripts/shantay_pass.rs2
- data/src/scripts/areas/area_mage_arena/configs/mage_arena.obj
- data/src/scripts/doors/scripts/doors.rs2
- data/src/scripts/player/configs/death.param
- data/src/scripts/player/scripts/death.rs2
- data/src/scripts/quests/quest_blackknight/scripts/quest_blackknight.rs2
- data/src/scripts/quests/quest_desertrescue/configs/desertrescue.obj
- data/src/scripts/quests/quest_elena/scripts/doors.rs2
- data/src/scripts/skill_fishing/scripts/fishing_guild.rs2
- fix remaining possible script errors in locs using next_loc_stage
- create a param for objs that are never kept on death (currently only applied to god capes and ana in a barrel)
> chore(content): destroy_death param, fix script errors with remaining locs using next_loc_stage

- data/src/scripts/_unpack/all.npc
https://github.com/2004Scape/Server/issues/1509
addressing this issue here, it looks like they've provided proof on discord.
The issue seems to  be everything in the wilderness is treated as aggressive so somebody at the time must have written a carve out for them?
> fix: Adds aggression exemption for rogues

- src/engine/entity/Npc.ts
This code had been commented out of nomode() because it didn't belong there. Instead it now is called directly when clearinteraction() gets called
> fix(engine):  Npcs will now stop facing player when interaction is cleared

- data/src/scripts/interface_trade/configs/trade.constant
- data/src/scripts/interface_trade/scripts/trade.rs2
- data/src/scripts/minigames/game_duelarena/configs/duelarena.constant
- data/src/scripts/minigames/game_duelarena/scripts/duel_arena.rs2
- data/src/scripts/minigames/game_duelarena/scripts/duel_arena_finish.rs2
- data/src/scripts/minigames/game_duelarena/scripts/duel_arena_settings.rs2
- data/src/scripts/minigames/game_duelarena/scripts/duel_arena_start.rs2
Initially reported by White Turtle on discord:
```
Player A trades Player B
Player B logs out
Player B logs back in quickly
Player B trades Player A
Trade screen immediately appears without confirmation from player A
```
To confirm ours works like the above steps:
https://github.com/user-attachments/assets/9945d09c-9661-421b-8815-a4c0dc86305b
Osrs doesnt work like ours does:
https://github.com/user-attachments/assets/5a6da0d0-0077-4814-a012-19c0aaa13557
2004Scape with my fixes:
https://github.com/user-attachments/assets/6f2bab76-5ecf-487f-9975-d4245f778b84
> fix(content): only bring up trades menu if you've recieved a trade recently

- prisma/multiworld/migrations/20250324231534_add_mod_action_table/migration.sql
- prisma/multiworld/schema.prisma
- prisma/singleworld/migrations/20250324232003_add_mod_action_table/migration.sql
- prisma/singleworld/schema.prisma
- src/db/types.ts
Adds a new `mod_action` table for the purpose of auditing moderator actions.
- Added `mod_action` table in both Prisma schemas.
- Generated and included the necessary Prisma migrations.
> feat(engine): Add mod action table

- data/src/scripts/minigames/game_duelarena/scripts/duel_arena_finish.rs2
Plenty of vids and screenshots of people brining pets into duels
> fix(content): no longer delete pets when finishing a duel

- data/src/scripts/skill_firemaking/configs/bank_zones.dbrow
from [video](https://youtu.be/NjOBkLNp5p0?si=YpO-Cfmrgi4ktvJh&t=89):
> fix(content): adjust firemaking tiles in fishing guild bank

- data/src/scripts/skill_fishing/scripts/fishing_spots/lavafish_loc.rs2
There was no increment on the action delay while fishing for lava eels from the loc object, so it would perpetually try to fish but never catch anything in the spawns in the lava maze.
> fix(content): Fixing lava eel fishing for loc

- data/src/pack/varp.pack
- data/src/scripts/quests/quest_mcannon/configs/cannon.constant
- data/src/scripts/quests/quest_mcannon/configs/quest_mcannon.varp
- data/src/scripts/quests/quest_mcannon/scripts/cannon_fire.rs2
- data/src/scripts/quests/quest_mcannon/scripts/cannon_setup.rs2
- data/src/scripts/quests/quest_mcannon/scripts/npcs/nulodion.rs2
- Var2 is used for cannon stage 0-4: https://chisel.weirdgloop.org/varbs/display?varplayer=2
- You can claim partial cannon parts that are lost after placement:
- cannon rotate timer continues to tick until logout or out of ammo
Videos:
- https://youtu.be/Vsnkdq8OOMg?t=81
- https://youtu.be/TeQXQDaawO0?t=234
- https://www.youtube.com/watch?v=WWyNTsMXjTE&t=219s
The first video is particularly useful, you can see that he places a cannon (starts north), and picks it up when its facing east
Then he places another cannon later in the video, which starts south east (spinning until it reaches north and hits the ammo check)
> feat(content): %mcannon_stage varp and cannon timer arg

- data/src/scripts/skill_thieving/scripts/thieving.rs2
- src/engine/entity/Npc.ts
Fixes thieving and splashing outside of maxrange
> fix(engine): Npcs will now reset properly if they have not wandered in 500 ticks

- data/src/scripts/areas/area_wilderness/scripts/king_black_dragon.rs2
- data/src/scripts/macro events/scripts/general/macro_event_drunken_dwarf.rs2
- data/src/scripts/macro events/scripts/mining/macro_event_rock_golem.rs2
- data/src/scripts/npc/scripts/dragon.rs2
- data/src/scripts/player/scripts/combat_clearqueue.rs2
- data/src/scripts/player/scripts/damage.rs2
- data/src/scripts/quests/quest_dragon/scripts/elvarg.rs2
- data/src/scripts/quests/quest_dragon/scripts/melzar_the_mad.rs2
- data/src/scripts/skill_combat/scripts/npc/npc_combat.rs2
- data/src/scripts/skill_combat/scripts/npc/npc_combat_magic.rs2
- data/src/scripts/skill_combat/scripts/npc/npc_combat_melee.rs2
- data/src/scripts/skill_combat/scripts/npc/npc_combat_ranged.rs2
- data/src/scripts/tutorial/scripts/npcs/tut_giant_rat.rs2
most uses of the damage_player queue are non-combat related, but when the queue executes it will put the player in combat, preventing logout, this PR renames the old proc to be used specifically for combat, and updates all combat related usages.
> fix(content): update damage queue uses

- data/src/scripts/player/scripts/consumption/consume.rs2
- data/src/scripts/player/scripts/consumption/effects/scripts/consume_effects.rs2
- matches osrs's curry, stew, and some cocktails...
Old videos:
https://github.com/user-attachments/assets/368606b5-88dd-4c30-bf7f-bce877d90994
https://github.com/user-attachments/assets/b1966761-3335-495e-a82f-bf85d1ff8923
> fix(content): put pies and cakes into first inv slot after eating

- data/src/scripts/areas/area_seers/scripts/mcgrubors_wood.rs2
- data/src/scripts/levelrequire/scripts/levelrequire.rs2
- data/src/scripts/quests/quest_chompybird/scripts/chompy_bird.rs2
- data/src/scripts/quests/quest_murder/configs/quest_murder.loc
- data/src/scripts/quests/quest_murder/scripts/murder_guard.rs2
- correct freespace check on vine worms
- change sinclair fountain to work as a water source
- fix typo in murder guard dialogue
- aprange check for chompy bird hunting
- Fixed bug where Iban's staff would only check against either stat instead of both, also add the requirement messages, and change it to use `stat` instead of `stat_base`, as this was more likely to be the original cause of the bug (having a check < 49 doesn't make much sense)
> fix(content): Misc context fixes

- src/engine/World.ts
- src/engine/entity/Npc.ts
Npc events now decrement and compare to 0 rather than scheduling for a tick
This is extremely minor, but it causes slight behavioral difference when an Npc is `npc_delay()`'d, because this causes the counter to not decrement
> fix(engine): Npc events (respawn, despawn, changetype) are now scheduled better

- src/engine/World.ts
- src/engine/entity/EntityQueueRequest.ts
- src/engine/entity/EntityTimer.ts
- src/engine/entity/Npc.ts
- src/engine/entity/NpcQueueRequest.ts
- src/engine/entity/Player.ts
- src/engine/entity/PlayerQueueRequest.ts
- src/engine/script/ScriptRunner.ts
- src/engine/script/ScriptState.ts
- src/engine/script/handlers/NpcOps.ts
- src/engine/script/handlers/PlayerOps.ts
The script lookup was happening when we queue the script, but this means if the npc does a `npc_changetype` it would run the script from the old Npc type
Now, we look up the script when the queue executes, and so the current Npc type will be reflected
> fix(engine): Npc queues now consider if the Npc has changed type 

- data/src/scripts/minigames/game_trail/scripts/easy/trail_clue_easy_reward.rs2
- data/src/scripts/minigames/game_trail/scripts/hard/trail_clue_hard_reward.rs2
- data/src/scripts/minigames/game_trail/scripts/medium/trail_clue_medium_reward.rs2
- data/src/scripts/skill_agility/scripts/shortcuts.rs2
Since RuneScape didn't start tracking clue scroll completions for quite a while after 2004, and Adventure Log wasn't a thing for quite a while, I think this would be a good compromise.
Allowing clue completions onto the Adventure's log will allow 3rd party applications to keep track externally by checking the log periodically (right now HTML scraping, but an API would be nice for this)
> feat(content): Clue Scrolls on Adventure Log and fix(content): Coal Trucks agility shortcut

- data/src/scripts/minigames/game_trail/scripts/easy/trail_clue_easy_reward.rs2
- data/src/scripts/minigames/game_trail/scripts/hard/trail_clue_hard_reward.rs2
- data/src/scripts/minigames/game_trail/scripts/medium/trail_clue_medium_reward.rs2
- data/src/scripts/skill_agility/scripts/shortcuts.rs2
Fixes ( original #1607 ) reported by _heart. on discord
> fix(content): Alog message once per clue opening, not once per item inside the clue reward

- data/src/scripts/macro events/scripts/macro_events.rs2
There is no proof of how this piece of content worked. But its particularly buggy if we dont check for untradeables. Lots of untradeables have custom opheld5 triggers, inv_dropslot would skip the custom behavior in these triggers.
> fix(content): only scatter tradables on genie fail

- data/src/scripts/skill_combat/scripts/npc/npc_combat_magic.rs2
- data/src/scripts/skill_combat/scripts/pvp/pvp_magic.rs2
- No "You are frozen!" mes. I believe this mes comes from ancients later on
From [video](https://youtu.be/1A_AITzasxE?t=431):
https://github.com/user-attachments/assets/4645e0dd-b564-46fd-88f6-571f2bd867e2
A potential issue with our engine code though...
https://github.com/user-attachments/assets/b73c3efd-9bb5-4703-bbab-5e6aeb2a2d4a
Our walktrigger runs twice, whilst the video it runs once?
> fix(content): remove "You've been frozen!" mes

- data/src/scripts/npc/scripts/barbarian.rs2
Osrs for some reason, they scream 100% of the time. This video looks like 1/4 https://youtu.be/RdilejVd-cQ
Also the barbarian women don't scream at all, unlucky? Or did only male barbarians scream
> fix(content): change barbarians to have a 1/4 chance to scream

- data/src/scripts/minigames/game_duelarena/scripts/duel_arena.rs2
You can duel players in this area, which are accessible in f2p. Also missing return for dueling players outside the arena
> fix(content): players shouldnt be able to duel on f2p worlds

- data/src/scripts/areas/area_gnome/scripts/gnome_gate.rs2
- src/engine/World.ts
- src/engine/entity/Loc.ts
- src/engine/entity/LocObjEvent.ts
- src/engine/entity/NonPathingEntity.ts
- src/engine/entity/Obj.ts
- src/engine/zone/Zone.ts
We need Loc and Obj events (specifically Loc) to be processed in the order they are initialized. Previously, they would process in the order that they exist within the Zone's LinkedList. This would give incorrect behavior when multiple events need to happen on the same tick. Specifically, gnome stronghold door was behaving erratically
Now the events are stored in a nice event queue LinkedList stored on World. This makes Loc and Obj events match RSProx output and osrs behavior. It also gets rid of the jank `duration -1` that existed inside of `trackLocObj`
> fix(engine): Loc and Obj events are now handled in the correct order (fixed the gnome stronghold door)

- data/src/scripts/minigames/game_trail/scripts/trail_puzzle.rs2
- src/network/rs225/client/handler/OpHeldHandler.ts
This will stop the puzzle box interface from closing and reopening on every move.
Discussed in https://github.com/2004Scape/Server/pull/1630
> fix(engine): Don't clearPendingAction on main modal ophelds (Puzzlebox fix)

- src/engine/entity/Player.ts
Tabs could have been updated while reconnecting, leaving clients in a broken tab state upon login
ie: disconnected while travelling to Entrana
> fix(engine): send tabs on reconnect

- data/src/pack/npc.pack
- data/src/scripts/areas/area_ardougne_east/configs/ardougne_east.npc
- data/src/scripts/areas/area_ardougne_east/scripts/rdpt_employee.rs2
- data/src/scripts/areas/area_ardougne_east/scripts/wizard_cromperty.rs2
- data/src/scripts/general_use/scripts/pickables.rs2
- data/src/scripts/quests/quest_arena/scripts/fightslave.rs2
- data/src/scripts/quests/quest_arena/scripts/jeremy_servil.rs2
- data/src/scripts/quests/quest_arena/scripts/quest_arena.rs2
- data/src/scripts/quests/quest_desertrescue/scripts/camp_guard.rs2
- data/src/scripts/quests/quest_ikov/scripts/guardian_of_armadyl.rs2
- change flax respawn times to be static (matches OSRS and old videos)
- fix a typo in the tourist trap quest
- change the ogre cutscene in fight arena to stop using npc_queue, fix the reversed conditions used for checking if the npcs are out of combat
> fix(content): static flax times, tourist trap typo, fight arena changes

- data/src/scripts/areas/area_varrock/scripts/gertrude.rs2
Added a check to see if you have an overgrown cat following you when talking to Gertrude. 
I haven't been able to find any sources of this bug but here's some saying you can't have two cats following you at once so I'm guessing just checking your follower is correct for the time: 
https://www.neoseeker.com/forums/2410/t537652-kittens/#m8451857
https://www.neoseeker.com/forums/2410/t646414-cats-dying/#m10567110
> fix(content): Gertrude won't override your overgrown cat

- data/src/scripts/_test/scripts/cheats/cheat_search.rs2
- data/src/scripts/engine.rs2
- data/src/scripts/quests/quest_mcannon/scripts/cannon_fire.rs2
- src/engine/CoordGrid.ts
- src/engine/script/ScriptIterators.ts
- src/engine/script/ScriptOpcode.ts
- src/engine/script/ScriptOpcodePointers.ts
- src/engine/script/ScriptState.ts
- src/engine/script/handlers/LocOps.ts
- src/engine/script/handlers/NpcOps.ts
- src/engine/script/handlers/ObjOps.ts
- src/engine/script/handlers/ServerOps.ts
- src/engine/zone/Zone.ts
So a few things here:
- All entity lookups now iterate in 'reverse' order. This matches OSRS targeting
- There are two new commands: 
- `obj_findallzone` mirrors `loc_findallzone` behavior but for `Obj`s
- `npc_hunt` mirrors `npc_find` but it checks if the `Npc` is attackable
- `npc_hunt` and `npc_find` now will return the `Npc` with the shortest Euclidean distance, which matches osrs behavior
- Dwarf multicannon now uses `npc_hunt` to do its targeting. This allows the cannon to fully match osrs behavior for targeting
Here's some stuff from osrs:
Dwarf cannon priority map showing Euclidean distance
Barb assault cannon priority map showing Euclidean distance
A fun osrs clip that you can make sense of if you want (04 will match this behavior and others) …
> fix(engine): Entity searches now match RuneScape behavior. Dwarf cannon targeting is now fully authentic!

- data/src/scripts/general_use/scripts/tables.rs2
- data/src/scripts/player/scripts/drop.rs2
- src/engine/World.ts
Previously we were adding 100 ticks onto `duration` when dropping items on the ground
We checked the available runescript leaks that we have and this didn't match observable osrs behavior (npc drops last a total of 200 ticks, not 200 +100)
It looks like (almost) all of our content was written with the assumption that `duration` is 1:1 with despawn time, so we don't need to do a bunch of content changes to match new engine behavior. I did change tables specifically to match new behavior though
> fix(engine): Ground item despawn time is sped up across the board by 100 ticks

- data/src/scripts/levelup/scripts/levelup_unlocks_herblore.rs2
No source showing incorrect spelling, assuming just a typo
Reported by clayton_c on discord: https://discord.com/channels/953326730632904844/1358519718088278036
> fix(content): Typo in level up message

- data/src/scripts/skill_thieving/scripts/thieving.rs2
Similar to https://github.com/2004Scape/Server/pull/1368
They added a 1t p_delay to produce this behavior described in the [blog post](https://oldschool.runescape.wiki/w/Update:Special_Attacks):
`The new RuneScape launch inadventantly made it harder to gain resources from these in competative situations (where two or more people are trying to get the resource at once), since only one person could ever get the resource at a time. We have now fixed it back to the old behaviour where if both people are successful at the exact same instant, they will both get the resource.`
> fix(content): no longer delay the player when stealing from thieving stalls

- data/src/scripts/player/scripts/equip.rs2
From [video](https://youtu.be/AVpqoWjsT1E?t=34):
https://github.com/user-attachments/assets/8a7d7268-e964-4f50-8fdb-a04d3533377b
Makes me question... Did every protected if_button/inv_button in the engine clear pending action and close interface?
> fix(content): clear pending action when unequipping items

- data/src/scripts/areas/area_brimhaven/scripts/kangai_mau.rs2
- data/src/scripts/quests/quest_ikov/scripts/lucien.rs2
- data/src/scripts/quests/quest_ikov/scripts/quest_ikov.rs2
- data/src/scripts/skill_herblore/configs/brewing/potions.obj
- fix incorrect open door being used for luciens house
- stop lucien from attacking you after ai_queue3 runs, also add another check to the queue for safety
- fix typo in kangai mau's dialogue
> fix(content): lucien door and death, kangai mau dialogue typo

- data/src/scripts/skill_magic/configs/magic_spells.dbrow
enchanting d ammies were giving charged glories, changed to uncharged as per osrs and classic
> fix(content): level 5 enchant fix

- data/src/scripts/skill_combat/scripts/player/player_ranged.rs2
The ~update_all proc in:
https://github.com/2004Scape/Server/blob/728267a226bdefb858a153660b16d3706a2b4824/data/src/scripts/skill_combat/scripts/player/player_ranged.rs2#L122-L125
Sets the %com values to unarmed... so anim() and sound_synth need to go before this
> fix(content): last knife/dart does unarmed animation

- data/src/scripts/areas/area_alkharid/scripts/shantay.rs2
- data/src/scripts/areas/area_alkharid/scripts/shantay_pass.rs2
- data/src/scripts/skill_cooking/scripts/cooking_inv/scripts/stew/stew.rs2
This covers the rest of the ophelds we are missing. Some guessing based on osrs.
Doesn't include the following:
display_tea (unobtainable)
tray_gold, (unobtainable? I couldn't find anything about this obj)
obj_2715, obj_2718, obj_2721 (not used)
> fix(content): Missing ophelds

- data/src/scripts/quests/quest_tree/scripts/quest_tree.rs2
This chest is also placed in west ardougne and can be accessed before firing the ballista during the quest, and you can still get the orb from it (confirmed on RS3)
> fix(content): extra stage check on orb of protection chest

- src/engine/entity/Npc.ts
- src/engine/script/handlers/NpcOps.ts
Reverts a small change from https://github.com/2004Scape/Server/pull/1613 . Some content was relying on `npc_setmode(null)` to clean up a bunch of npc variables. The previous PR took that behavior away, but this PR adds it back
We might revisit this in the future and flesh it out a bit more. It's a little unintuitive that `npc_setmode(null)`  should have a bunch of side effects. It's possible that jagex uses a command like `npc_reset()` to achieve this behavior instead. Further, there's a few examples where we *do not* want this side effect, like failing a pickpocket, which is why the side effect was removed in the first place
For now, failing a pickpocket will reset a bunch of Npc state (inauthentically) until we can revisit this. This PR is essentially a temporary solution for …
> chore(engine): Housekeeping for reset defaults

- data/src/scripts/skill_combat/scripts/player/player_ranged.rs2
- data/src/scripts/skill_combat/scripts/pvp/pvp_ranged.rs2
Reverting changes added on March 7 in this [PR](https://github.com/2004Scape/Server/commit/412eeaade9d52413d88fbb1d0a230a0864d41597) now that the engine is accounting for the additional 100 ticks.
> fix(content): Arrows despawning too quickly

- data/src/scripts/player/scripts/appearance.rs2
- data/src/scripts/skill_agility/scripts/agility.rs2
- data/src/scripts/skill_agility/scripts/shortcuts.rs2
- update monkeybars to closer match this 2006 video https://www.youtube.com/watch?v=jdcT9ogpMwE&t=166s, also now correctly sets bas which prevents the wrong stand animation being used when delayed for the tick after the teleport
- Create a proc for updating each bas, update existing procs to call this
> fix(content): monkeybars changes

- data/src/scripts/areas/area_draynor/scripts/professor_oddenstein.rs2
- data/src/scripts/general/scripts/quests.rs2
- data/src/scripts/quests/quest_crest/scripts/crest_dimintheis.rs2
- data/src/scripts/quests/quest_haunted/scripts/quest_haunted.rs2
- data/src/scripts/quests/quest_itwatchtower/scripts/quest_itwatchtower.rs2
- Recalculate quest points on completion instead of adding, matches https://youtu.be/v2f-IjVObLs?si=PFG7Vxrfz7b5iQhG&t=1393
- set haunted completion var when completion is queued instead of in queue
- change family crest and watchtower to delete all crest/crystals from inv/bank when completion is queued
> fix(content): queued quest complete changes

- data/src/scripts/areas/area_edgeville/scripts/oziach.rs2
- data/src/scripts/areas/area_falador/scripts/goblin_village/general_bentnoze.rs2
- data/src/scripts/areas/area_lumbridge/scripts/duke_horacio.rs2
- data/src/scripts/tutorial/scripts/tut_chatbox_steps.rs2
- match linebreaks on initial tutorial message with https://web.archive.org/web/20060328131241/http://www.runescape.com/lang/en/aff/runescape/screenshots/free_chardesign.ws
- remove linebreak character from ~p_choice in bentnoze dialogue
- don't increase dragonslayer varp after telling oziach you've slain elvarg
> fix(content): dialogue fixes for tutorial island, dragon slayer

- data/src/scripts/quests/quest_doric/scripts/quest_doric.rs2
> fix(content): Typo - missing comma in Doric easy clue dialogue

- data/src/scripts/quests/quest_legends/scripts/jungle_tree.rs2
- data/src/scripts/quests/quest_mcannon/scripts/locs/mcannon_crate.rs2
- data/src/scripts/skill_thieving/configs/chests/trapped_chest.dbrow
- data/src/scripts/skill_thieving/scripts/chest/trapped_chest.rs2
- data/src/scripts/skill_thieving/scripts/thieving.rs2
- data/src/scripts/skill_woodcutting/configs/trees.dbrow
- fixes to timing, sounds, and locs used for trapped/locked thieving chests
- fix respawnrates of chests to match OSRS, and multiply all by 2 to use playercount scaling instead (old videos show longer times, e.g. https://www.youtube.com/watch?v=Mwg4q__B2Z4)
- fix jungle bushes/trees giving 10 xp instead of 100, increase odds of rolling logs on chop
> fix(content): Skilling fixes

- data/src/scripts/general/configs/free_to_play.constant
- data/src/scripts/skill_fishing/scripts/fishing_spots/lavafish.rs2
In osrs it just lets you fish in f2p, no members check at all
https://github.com/user-attachments/assets/18e874c2-1716-442d-879c-8a1445486b63
> fix(content): remove members check from lava eel fishing to match osrs

- data/src/scripts/areas/monastery/scripts/monk.rs2
matches osrs:
- monks can self heal the same tick their hp reaches 0 and ai_queue3 is called
https://github.com/user-attachments/assets/ce1c6f2d-7720-40e8-bc95-e4fdfc7a3ee0
- monks can also naturally regenerate the same tick ai_queue3 runs. Normally the death script will still run for other npcs, but monks differ in this case
https://github.com/user-attachments/assets/5fdacef5-63dc-46a0-8922-f6ba363fa5c0
> fix(content): monks no longer heal and die at the same time

- data/src/scripts/minigames/game_gnomeball/scripts/gnomeball_pass.rs2
> fix(content): no longer pass gnomeballs if equipping something in your right hand

- data/src/scripts/macro events/scripts/general/macro_event_drunken_dwarf.rs2
- data/src/scripts/macro events/scripts/general/macro_event_genie.rs2
- data/src/scripts/macro events/scripts/general/macro_event_mysterious_old_man.rs2
> fix(content): add authentic line breaks in random event dialogue

- src/engine/entity/Player.ts
matches from early osrs [video](https://youtu.be/gUB1rS53IFc?t=1803):
https://github.com/user-attachments/assets/ca201831-e8a1-4158-89bc-52986ce01f21
before:
https://github.com/user-attachments/assets/a86780c6-821a-4247-b280-2160629191fc
after: 
https://github.com/user-attachments/assets/c738cd7b-a6ae-407a-8dee-a8388ba6e336
some other relevant vids:
- dont retal if moving: https://youtu.be/-zOKqWTUM40?t=77
> fix(engine): hasInteraction() to return false if targetOp is following

- data/src/scripts/minigames/game_trail/scripts/easy/trail_clue_easy_reward.rs2
- data/src/scripts/minigames/game_trail/scripts/medium/trail_clue_medium_reward.rs2
- only mentioned in level 1s on official sites knowledge base https://web.archive.org/web/20060415002328/http://kbase.runescape.com:80/lang/en/aff/runescape/viewarticle.ws?article_id=1989
- moved to level 2 at some point after Oct 2006, the Dec 2006 clue expansion seems likely, costume room was updated here https://oldschool.runescape.wiki/w/Update:Game_Improvements, https://x.com/JagexAsh/status/808118338908024832
- old guides mention it in level 1, some have it in both tiers, likely a mistake since no other clue unique shares tiers
- https://www.neoseeker.com/runescape/faqs/125252-treasure-trail.html, 
- https://web.archive.org/web/20040813233712/http://runehq.com/viewguidedb.php?id=00350#rewards
- https://web.archive.org/web/20050412082313/http://www.tip.it/runescape/?page=treasure_trai …
> fix(content): move wizard boots to level 1 clues

- data/src/scripts/levelup/scripts/levelup_unlocks_fishing.rs2
- data/src/scripts/levelup/scripts/levelup_unlocks_smithing.rs2
----
You can see that Smithing had a change in these dagger messages where smelting was a newer addition:
> fix(content): some levelup unlock messages

- data/src/scripts/tutorial/scripts/tutorial.rs2
from [blog](https://oldschool.runescape.wiki/w/Update:Calling_Pets_%26_Deadman_Death):
`Run energy is now restored at the end of the tutorial.`
> fix(content): remove run energy restore on tutorial island completion

- data/src/scripts/areas/area_alkharid/scripts/al_kharid_warrior.rs2
- data/src/scripts/areas/area_barbarian_village/scripts/beer_barrels.rs2
- data/src/scripts/areas/area_draynor/scripts/witch.rs2
- data/src/scripts/areas/area_mage_arena/scripts/battle_mage.rs2
- data/src/scripts/areas/area_wilderness/scripts/king_black_dragon.rs2
- data/src/scripts/macro events/scripts/general/macro_event_drunken_dwarf.rs2
- data/src/scripts/macro events/scripts/mining/macro_event_rock_golem.rs2
- data/src/scripts/npc/scripts/chaos_druid.rs2
- data/src/scripts/npc/scripts/dark_wizard.rs2
- data/src/scripts/npc/scripts/dragon.rs2
- data/src/scripts/npc/scripts/shadow_spider.rs2
- data/src/scripts/quests/quest_arena/scripts/bouncer.rs2
- data/src/scripts/quests/quest_arena/scripts/general_khazard.rs2
- data/src/scripts/quests/quest_dragon/scripts/elvarg.rs2
- data/src/scripts/quests/quest_dragon/scripts/melzar_the_mad.rs2
- data/src/scripts/quests/quest_vampire/scripts/count_draynor.rs2
- data/src/scripts/skill_combat/scripts/npc/npc_combat.rs2
- data/src/scripts/skill_combat/scripts/npc/npc_combat_magic.rs2
- data/src/scripts/skill_combat/scripts/npc/npc_combat_ranged.rs2
- data/src/scripts/tutorial/scripts/npcs/tut_giant_rat.rs2
- renames `~npc_can_attack_player` to `~npc_check_notcombat`
- adds new proc to check if the npc itself is in combat, `~npc_check_notcombat_self` (amazing how our combat managed to work as well as it did without this!)
- Partially removes %npc_lastattack, unnecessary varn.
- Refactors retal code to account for osrs edgecases
- adds opplayer2 mode check before aggroing barbarians when stealing their beer
- removes the flinching from al kharid warriors to match https://youtu.be/D8VG03tRR1w?t=60
Some edge cases that match osrs:
- ragging someones guard in singles
https://github.com/user-attachments/assets/f8ea75ca-f8f3-47e3-805f-6ff963664ff9
https://github.com/user-attachments/assets/edf29a91-86eb-44b5-b22a-807944df3592
- ranging highwayman defaults to ap …
> fix(content): add self combat check to ai_opplayer2, and match npc retal edgecases

- data/src/scripts/player/scripts/consumption/effects/scripts/kebab.rs2
- src/engine/script/handlers/PlayerOps.ts
before:
https://github.com/user-attachments/assets/6637f4b8-c6bf-4af9-ae3c-081ecffdb220
after:
https://github.com/user-attachments/assets/6320a5ae-4580-4a12-82ed-26beec00ebf2
> fix(engine): prevent smaller stat_boosts from overriding bigger stat_boosts

- data/src/scripts/music/configs/musicregion.dbrow
- data/src/scripts/music/scripts/move.rs2
When I originally wrote the wilderness warning code, I didnt take into account getting into the wilderness without crossing the wilderness border! Such as, logging in, using the ardy lever, and entrana door. I now set %wilderness = ^true for each wilderness mapsquare.
Was also missing 0_46_161 music track:
> feat(content): wilderness mapsquares, and missing 0_46_161 mapsquare trigger

- data/src/scripts/general_use/scripts/spade.rs2
Digging at `trail_coord` for clues can cause the server to crash with error:
```
script error: inv_add An input for a Obj type was not valid to use. Input was -1.
file: spade.rs2
stack backtrace:
1: [opheld1,spade] - spade.rs2:64
```
This is because the `trail_casket` param is assumed to exist but might be undefined:
```
def_namedobj $casket = oc_param($clue, trail_casket);
inv_add(inv, $casket, 1);
```
This PR updates the logic to ensure that both then trail_coord and trail_casket params are defined before allowing the dig action.
> fix(content): Potential crash when digging for clues

- data/src/scripts/areas/area_karamja/scripts/captain_shanks.rs2
- data/src/scripts/engine.rs2
- data/src/scripts/general/scripts/quests.rs2
- data/src/scripts/interface_boat/scripts/sail.rs2
- data/src/scripts/levelup/scripts/levelup.rs2
- data/src/scripts/minigames/game_duelarena/scripts/duel_arena_finish.rs2
- data/src/scripts/minigames/game_duelarena/scripts/duel_arena_start.rs2
- data/src/scripts/minigames/game_trail/scripts/trail_clue_helper.rs2
- data/src/scripts/minigames/game_trawler/scripts/trawler_start.rs2
- data/src/scripts/minigames/game_trawler/scripts/trawler_win.rs2
- data/src/scripts/music/scripts/music.rs2
- data/src/scripts/player/scripts/death.rs2
- data/src/scripts/quests/quest_dragon/scripts/dragonslayer_ned.rs2
- data/src/scripts/quests/quest_fluffs/scripts/quest_fluffs.rs2
- data/src/scripts/quests/quest_hazeelcult/scripts/quest_hazeelcult.rs2
- data/src/scripts/quests/quest_itgronigen/scripts/quest_itgronigen.rs2
- data/src/scripts/quests/quest_itwatchtower/scripts/quest_itwatchtower.rs2
- data/src/scripts/quests/quest_seaslug/scripts/quest_seaslug.rs2
- data/src/scripts/tutorial/scripts/locs/tut_organ.rs2
- src/engine/script/handlers/PlayerOps.ts
- Completely prevent any packets from going out to the client for music/sounds if the player is on low memory mode.
- Refactor all uses of `midi_jingle` and `midi_song` to check for music volume and prevent packets from going out if the music volume is set to 0.
- This will lower overall network/internet usage like for example being on mobile/cell data. And from the server side obv. We are causing players to unnecessarily download these files and such when they don't want to play with the midi's.
> feat(engine): prevent packet sending midi if on lowmem or have volume off

- data/src/scripts/_unpack/all.inv
- data/src/scripts/general/scripts/misc/coord_procs.rs2
- data/src/scripts/general/scripts/misc/inv_procs.rs2
- data/src/scripts/minigames/game_duelarena/configs/duelarena.constant
- data/src/scripts/minigames/game_duelarena/configs/duelarena.dbrow
- data/src/scripts/minigames/game_duelarena/configs/duelarena.inv
- data/src/scripts/minigames/game_duelarena/scripts/duel_arena.rs2
- data/src/scripts/minigames/game_duelarena/scripts/duel_arena_finish.rs2
- data/src/scripts/minigames/game_duelarena/scripts/duel_arena_start.rs2
- data/src/scripts/minigames/game_duelarena/scripts/duel_forfeit.rs2
- data/src/scripts/skill_combat/scripts/pvp/pvp_ranged.rs2
- src/engine/script/handlers/InvOps.ts
Main source used: https://www.se7ensins.com/forums/threads/svews-bug-abuse-notes-everything-about-glitches-and-finding-them-in-runescape.437147/
- When your inventory is full, and you win the stake. The items *you* put up in the stake instantly drop to the floor (engine), visible to you for 2 minutes. If the duelwinnings wont fit into your inventory (checked in runescript), then `inv_dropall` runs, which will drop the entire winnings visible to everyone instantly. This matches: https://youtu.be/RYhIaNoP3Q8, https://youtu.be/GpPx9GmTvRo
https://github.com/user-attachments/assets/8a3b2cb0-05a6-4fe3-bbd4-25cc42e9cd1e
- allow smuggling food items into the duel arena by overflowing the duelwinnings inventory https://youtu.be/QkamyLQ52F8
- removes the ~in_duel_arena coord check when teleporting …
> feat(content): implement historical duel arena bugs, and some other duel arena fixes

- data/src/pack/varp.pack
- data/src/scripts/_unpack/all.varp
- data/src/scripts/macro events/scripts/general/macro_event_drunken_dwarf.rs2
- data/src/scripts/npc/scripts/dragon.rs2
- data/src/scripts/npc/scripts/shadow_spider.rs2
- data/src/scripts/player/scripts/death.rs2
- data/src/scripts/quests/quest_legends/scripts/nezikchened.rs2
- data/src/scripts/quests/quest_upass/scripts/kalrag.rs2
- data/src/scripts/quests/quest_vampire/scripts/count_draynor.rs2
- data/src/scripts/skill_combat/scripts/npc/npc_combat.rs2
- data/src/scripts/skill_combat/scripts/pvp/pvp_magic.rs2
- data/src/scripts/skill_combat/scripts/pvp/pvp_melee.rs2
- data/src/scripts/skill_combat/scripts/pvp/pvp_ranged.rs2
- data/src/scripts/tutorial/scripts/npcs/tut_giant_rat.rs2
- throwing knives is the perfect speed to attack your opponent between their health being 0, and their death queue running.
2006:
https://github.com/user-attachments/assets/d996216f-4644-4a94-8cf8-9fe809142957
Before my changes:
https://github.com/user-attachments/assets/c939ad2f-45a4-449e-92fd-e0bf99f69d18
After my changes:
https://github.com/user-attachments/assets/5acf716f-21b7-48a7-b994-a5c68235c242
- Npc's can hit you on the tick you die 
OSRS:
https://github.com/user-attachments/assets/6d8a551b-6ff0-4d06-a92b-92a03f5c721f
Before my changes:
https://github.com/user-attachments/assets/a0e6c997-a662-4f3e-9f9f-d37f68b4518c
After my changes:
https://github.com/user-attachments/assets/7531b225-48bc-49b0-8701-0b6dba188d00
> fix(content): check if the player is dying with a varp instead of a hitpoints check

- data/src/scripts/areas/area_alkharid/scripts/shantay_pass.rs2
- data/src/scripts/skill_magic/scripts/spells/teleport.rs2
From https://www.se7ensins.com/forums/threads/svews-bug-abuse-notes-everything-about-glitches-and-finding-them-in-runescape.437147/:
`Hipi was kind enough to notice that if you were trying to enter the shanty pass, and you teleported somewhere right as the disclaimer was placed in your inventory, it would tele you there, then immediately teleport you back to the pass. This works in a few other situations as well, i don't want go into detail explaining why, so we'll just leave it at that. I had the bright idea that you could teleport to you house, then be transported back to the pass, tricking the game into thinking your still inside the house. It worked perfectly, and as a result whenever you turned on build mode, it would take you into the build mode of your house.`
This behavior makes …
> fix(content): queue shantay pass enter to match old bug, move ana barrel tele check

- data/src/scripts/interface_chat/scripts/chat.rs2
- data/src/scripts/levelup/scripts/levelup_unlocks_crafting.rs2
- "Rings" for some of our unlocks were black instead of blue because of the line break. Not sure what it should be... but I made it blue. I'm 50/50 split on this
- Amulets, and necklaces' $y & $scale were off. Went ahead and applied the fix to all necklaces and amulets in our crafting unlock messages
Old screenshot:
Ours before:
Ours after:
- Our crafting guild unlock was wrong, they added ruby necklaces to it sometime in 2007.
Old screenshot:
- added `~doubleobjbox2` with $x, $y, and $scale args for each obj. Needed to add this if I wanted to adjust the gold amulet (guess):
Ours before:
Ours after:
> fix(content): some crafting levelups adjusted

- data/src/scripts/skill_combat/configs/pvp.constant
- data/src/scripts/skill_combat/scripts/pvp/pk_skull.rs2
Seems to have been an osrs change to change it from 20 min -> 30 min.
- it was 20 min in [rsc](https://web.archive.org/web/20020204232538/http://www.jagex.com/manual/pk.html) (ty Mainely on discord)
- 20 min in [2006](https://web.archive.org/web/20060712071445/http://kbase.runescape.com/lang/en/aff/runescape/viewarticle.ws?article_id=1699)
- 20 min according to a forum post on [rsbandb](https://www.rsbandb.com/forums/viewtopic.php?f=17&t=17380)
Perhaps it was changed in this [osrs update](https://oldschool.runescape.wiki/w/Skull_(status)). But the wording makes it seem like its already 30 minutes
> fix(content): pk_skull should be 20 min not 30 min

- data/src/scripts/skill_combat/scripts/player/player_magic.rs2
- data/src/scripts/skill_combat/scripts/player/spells/scripts/claws_of_guthix.rs2
- data/src/scripts/skill_combat/scripts/player/spells/scripts/crumble_undead.rs2
- data/src/scripts/skill_combat/scripts/player/spells/scripts/flames_of_zamorak.rs2
- data/src/scripts/skill_combat/scripts/player/spells/scripts/saradomin_strike.rs2
- data/src/scripts/skill_combat/scripts/pvp/pvp_magic.rs2
- data/src/scripts/skill_combat/scripts/pvp/spells/scripts/claws_of_guthix.rs2
- data/src/scripts/skill_combat/scripts/pvp/spells/scripts/flames_of_zamorak.rs2
- data/src/scripts/skill_combat/scripts/pvp/spells/scripts/saradomin_strike.rs2
- data/src/scripts/skill_magic/scripts/spells/charge.rs2
So our pvp was using stat_sub, which drains by your *base stat*. In osrs pvp spells drain by your *current stat*.
-5 strength at 99;
https://github.com/user-attachments/assets/b18718ae-7fd0-42be-90e4-7bfc02a6b9a9
-6 strength at 111:
https://github.com/user-attachments/assets/cc2adce1-52bf-44d8-9cab-de193707fbae
Additionally, I found a [blog post](https://oldschool.runescape.wiki/w/Update:Contact!) from 2007 that states:
`The effect of the Flames of Zamorak spell is to temporarily reduce its victim's magic level. This was not working against players who'd boosted their magic levels (such as by drinking a potion). We have now fixed the spell to make it drain its victim's magic level, even if that level had been boosted. A corresponding bug has been fixed with the Claws of Guthix.`
So I went …
> fix(content): use stat_boost and stat_drain for pvp/pvm magic

- data/src/scripts/areas/area_alkharid/scripts/shantay_pass.rs2
- data/src/scripts/areas/area_alkharid/scripts/thkebabinstructs.rs2
- data/src/scripts/areas/area_alkharid/scripts/thshantaydisc.rs2
- Found a screenshot for the shantay disclaimer (finally!). This matches rsc a little bit. Decided to add line breaks to it.
- I find it likely it wasnt originally fully red since the shantay pass text was changed from black to red:
- I think there was also a ~objbox after clicking `Click here to continue`, since this is rsc:
- So ultimately this is what I came up with:
- I also added a line break to the title of the kebab paper:
> feat(content): thshantaydisc text

- data/src/scripts/areas/area_wilderness/scripts/wilderness_warning.rs2
- data/src/scripts/login_logout/login.rs2
Matches the behavior in this [video](https://youtu.be/hiUfg8MsKMo?t=5).... Not sure if this is the correct way to implement it:
https://github.com/user-attachments/assets/b40ac59d-b0a7-4e75-992a-a7e7d51086ea
> fix(content): dont show wildy warning when logging into wildy warning zones

- src/network/game/client/handler/MessagePublicHandler.ts
Staff names should appear white in public chat, as stated in the Rules of Conduct (April 15th, 2004).
Source: https://web.archive.org/web/20040415002858/http://runescape.com/ (Rules & Security -> "Please *Click here* to learn our rules")
Listed under **Rule 5: Jagex Staff impersonation**
> fix(engine): include staffmodlevel in MessagePublicHandler

- data/src/scripts/quests/quest_legends/scripts/quest_legends.rs2
matches https://www.youtube.com/watch?v=J30Q4Sr9Npk&t=351s
> fix(content): reset golden bowl charges when a bowl obj runs out

- data/src/scripts/quests/quest_hazeelcult/scripts/quest_hazeelcult.rs2
As per below video & image, 'cupbaord' should be 'cupboard':
https://youtu.be/Kf95y-YdviA?si=cZv2pC5sqafelQsw&t=337
> fix(content): Fix spelling error during Hazeel Cult quest

- data/src/scripts/quests/quest_sheepherder/scripts/npcs/doctor_orbon.rs2
When talking to Dr. Orbon the quest stage currently would increment after the mesbox telling the player they bought the protective suit. This lead to a lot of players getting confused as to why they could burn the sheep but not complete the quest. 
I've moved the quest stage incrementing up to before the mesbox when the gear is added to the inventory.
> fix(content): Update Sheep Herder Quest Stage Cleaner Incrementing
